// Code generated by scripts/registry/generate_registry.go — DO NOT EDIT.
package main

import (
	"context"
	"fmt"
	"os"

	"github.com/pulumi/pulumi-go-provider/infer"
	awsbucket "github.com/anvil/pulumi-anvil/aws/bucket"
	awslambda "github.com/anvil/pulumi-anvil/aws/lambda"
	gcpbucket "github.com/anvil/pulumi-anvil/gcp/bucket"
	gcpfunction "github.com/anvil/pulumi-anvil/gcp/function"
)

func main() {
	p, err := infer.NewProviderBuilder().
		WithComponents(
			infer.ComponentF(awsbucket.NewBucket),
			infer.ComponentF(awslambda.NewLambda),
			infer.ComponentF(gcpbucket.NewBucket),
			infer.ComponentF(gcpfunction.NewFunction),
		).
		Build()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	p.Run(context.Background(), "anvil", "0.0.1")
}
