// Code generated by scripts/registry/generate_registry.go — DO NOT EDIT.
package main

import (
	"context"
	"fmt"
	"os"

	"github.com/pulumi/pulumi-go-provider/infer"
	awsbucket "github.com/DamienPace15/anvil/provider/aws/bucket"
	awseventBridge "github.com/DamienPace15/anvil/provider/aws/eventBridge"
	awshttpapi "github.com/DamienPace15/anvil/provider/aws/httpapi"
	awslambda "github.com/DamienPace15/anvil/provider/aws/lambda"
	awsqueue "github.com/DamienPace15/anvil/provider/aws/queue"
	awssveltekitsite "github.com/DamienPace15/anvil/provider/aws/sveltekitsite"
	awsvpc "github.com/DamienPace15/anvil/provider/aws/vpc"
	awsvpcEndpoint "github.com/DamienPace15/anvil/provider/aws/vpcEndpoint"
	gcpbucket "github.com/DamienPace15/anvil/provider/gcp/bucket"
	gcpfunction "github.com/DamienPace15/anvil/provider/gcp/function"
)

func main() {
	p, err := infer.NewProviderBuilder().
		WithComponents(
			infer.ComponentF(awsbucket.NewBucket),
			infer.ComponentF(awseventBridge.NewEventBus),
			infer.ComponentF(awshttpapi.NewHttpApi),
			infer.ComponentF(awslambda.NewLambda),
			infer.ComponentF(awsqueue.NewQueue),
			infer.ComponentF(awssveltekitsite.NewSvelteKitSite),
			infer.ComponentF(awsvpc.NewVpc),
			infer.ComponentF(awsvpcEndpoint.NewVpcEndpoint),
			infer.ComponentF(gcpbucket.NewBucket),
			infer.ComponentF(gcpfunction.NewFunction),
		).
		Build()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	p.Run(context.Background(), "anvil", "0.0.1")
}
