# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    'CognitoUserPoolCustomAttributeType',
    'CognitoUserPoolIdentityProviderType',
    'CognitoUserPoolMfaMethod',
    'CognitoUserPoolMfaMode',
    'CognitoUserPoolOAuthFlow',
    'CognitoUserPoolUsernameAttribute',
    'HttpApiMethod',
    'LambdaArchitecture',
    'LambdaLogRetention',
    'LambdaRuntime',
    'S3FlowLogLifecycle',
    'SiteOriginProtectionProvider',
    'VpcNatType',
]


@pulumi.type_token("anvil:aws:CognitoUserPoolCustomAttributeType")
class CognitoUserPoolCustomAttributeType(_builtins.str, Enum):
    STRING = "String"
    NUMBER = "Number"
    DATE_TIME = "DateTime"
    BOOLEAN = "Boolean"


@pulumi.type_token("anvil:aws:CognitoUserPoolIdentityProviderType")
class CognitoUserPoolIdentityProviderType(_builtins.str, Enum):
    GOOGLE = "Google"
    """
    Google OAuth 2.0. Requires clientId and clientSecret.
    """
    FACEBOOK = "Facebook"
    """
    Facebook OAuth 2.0. Requires clientId and clientSecret.
    """
    LOGIN_WITH_AMAZON = "LoginWithAmazon"
    """
    Login with Amazon. Requires clientId and clientSecret.
    """
    SIGN_IN_WITH_APPLE = "SignInWithApple"
    """
    Sign in with Apple. Requires clientId and clientSecret.
    """
    OIDC = "OIDC"
    """
    Generic OIDC provider (Okta, Auth0, Microsoft Entra, etc.). Requires clientId, clientSecret, and oidcIssuer.
    """
    SAML = "SAML"
    """
    SAML 2.0 provider (corporate SSO, Active Directory Federation Services etc.). Requires metadataUrl or metadataContent.
    """


@pulumi.type_token("anvil:aws:CognitoUserPoolMfaMethod")
class CognitoUserPoolMfaMethod(_builtins.str, Enum):
    TOTP = "TOTP"
    """
    Time-based one-time password (authenticator app). No additional AWS resources required.
    """
    SMS = "SMS"
    """
    SMS one-time password via SNS. Requires snsCallerArn.
    """


@pulumi.type_token("anvil:aws:CognitoUserPoolMfaMode")
class CognitoUserPoolMfaMode(_builtins.str, Enum):
    OFF = "OFF"
    """
    MFA disabled. Default.
    """
    OPTIONAL = "OPTIONAL"
    """
    MFA available but not required. Users opt in.
    """
    REQUIRED = "REQUIRED"
    """
    MFA required for all users.
    """


@pulumi.type_token("anvil:aws:CognitoUserPoolOAuthFlow")
class CognitoUserPoolOAuthFlow(_builtins.str, Enum):
    CODE = "code"
    """
    Authorization code grant (PKCE). Most secure — use for all browser and server apps.
    """
    IMPLICIT = "implicit"
    """
    Implicit grant. Deprecated — tokens visible in browser URL. Avoid for new applications.
    """
    CLIENT_CREDENTIALS = "client_credentials"
    """
    Client credentials grant. M2M only — no user interaction.
    """


@pulumi.type_token("anvil:aws:CognitoUserPoolUsernameAttribute")
class CognitoUserPoolUsernameAttribute(_builtins.str, Enum):
    EMAIL = "email"
    """
    Users sign in with their email address.
    """
    PHONE_NUMBER = "phone_number"
    """
    Users sign in with their phone number.
    """


@pulumi.type_token("anvil:aws:HttpApiMethod")
class HttpApiMethod(_builtins.str, Enum):
    """
    HTTP method for an API route.
    """
    GET = "GET"
    """
    HTTP GET — read operations.
    """
    POST = "POST"
    """
    HTTP POST — create operations and async consumers (SQS, EventBridge, Step Functions).
    """
    PUT = "PUT"
    """
    HTTP PUT — replace operations.
    """
    PATCH = "PATCH"
    """
    HTTP PATCH — partial update operations.
    """
    DELETE = "DELETE"
    """
    HTTP DELETE — delete operations.
    """
    ANY = "ANY"
    """
    Matches all HTTP methods. Maps to the $default route key.
    """


@pulumi.type_token("anvil:aws:LambdaArchitecture")
class LambdaArchitecture(_builtins.str, Enum):
    ARM64 = "arm64"
    """
    Graviton - 20% cheaper, better performance. Default.
    """
    X86_64 = "x86_64"
    """
    Intel/AMD - use for x86-specific native dependencies.
    """


@pulumi.type_token("anvil:aws:LambdaLogRetention")
class LambdaLogRetention(_builtins.str, Enum):
    LAMBDA_LOG_RETENTION_7D = "7d"
    """
    7 days
    """
    LAMBDA_LOG_RETENTION_30D = "30d"
    """
    30 days (1 month)
    """
    LAMBDA_LOG_RETENTION_90D = "90d"
    """
    90 days (3 months)
    """
    LAMBDA_LOG_RETENTION_1Y = "1y"
    """
    1 year (365 days) - SOC 2 / ISO 27001 / PCI-DSS baseline. Default.
    """
    LAMBDA_LOG_RETENTION_3Y = "3y"
    """
    3 years (1095 days) - FedRAMP minimum
    """
    LAMBDA_LOG_RETENTION_6Y = "6y"
    """
    6 years (2190 days) - HIPAA minimum
    """
    LAMBDA_LOG_RETENTION_7Y = "7y"
    """
    7 years (2555 days) - IRAP minimum
    """


@pulumi.type_token("anvil:aws:LambdaRuntime")
class LambdaRuntime(_builtins.str, Enum):
    NODEJS24_X = "nodejs24.x"
    """
    Node.js 24 (LTS) - recommended
    """
    NODEJS22_X = "nodejs22.x"
    """
    Node.js 22 (LTS)
    """


@pulumi.type_token("anvil:aws:S3FlowLogLifecycle")
class S3FlowLogLifecycle(_builtins.str, Enum):
    STANDARD = "standard"
    """
    Auto-tiered: Standard (0-30d) → Standard-IA (30-90d) → Glacier Instant Retrieval (90d+). Suitable for compliance retention at minimal long-term cost.
    """


@pulumi.type_token("anvil:aws:SiteOriginProtectionProvider")
class SiteOriginProtectionProvider(_builtins.str, Enum):
    """
    The CDN/proxy provider sitting in front of CloudFront.
    """
    CLOUDFLARE = "cloudflare"
    """
    Cloudflare — inject x-origin-secret via a Cloudflare Transform Rule.
    """


@pulumi.type_token("anvil:aws:VpcNatType")
class VpcNatType(_builtins.str, Enum):
    GATEWAY = "gateway"
    """
    AWS managed NAT Gateway. One per AZ for true HA. ~$32/month per AZ plus $0.045/GB data processed.
    """
    FCK_NAT = "fck-nat"
    """
    fck-nat EC2 instance. Single instance regardless of AZ count. ~$4-6/month for t4g.small. Accepted single point of failure tradeoff for cost savings.
    """
