# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from ._inputs import *
import pulumi_aws
from typing import Optional
from anvil_cloud import grants


__all__ = ['BucketArgs', 'Bucket']

@pulumi.input_type
class BucketArgs:
    def __init__(__self__, *,
                 data_classification: pulumi.Input[_builtins.str],
                 lifecycle: Optional[pulumi.Input[_builtins.int]] = None,
                 transform: Optional[pulumi.Input['BucketTransformArgsArgs']] = None):
        """
        The set of arguments for constructing a Bucket resource.
        """
        pulumi.set(__self__, "data_classification", data_classification)
        if lifecycle is not None:
            pulumi.set(__self__, "lifecycle", lifecycle)
        if transform is not None:
            pulumi.set(__self__, "transform", transform)

    @_builtins.property
    @pulumi.getter(name="dataClassification")
    def data_classification(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "data_classification")

    @data_classification.setter
    def data_classification(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "data_classification", value)

    @_builtins.property
    @pulumi.getter
    def lifecycle(self) -> Optional[pulumi.Input[_builtins.int]]:
        return pulumi.get(self, "lifecycle")

    @lifecycle.setter
    def lifecycle(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "lifecycle", value)

    @_builtins.property
    @pulumi.getter
    def transform(self) -> Optional[pulumi.Input['BucketTransformArgsArgs']]:
        return pulumi.get(self, "transform")

    @transform.setter
    def transform(self, value: Optional[pulumi.Input['BucketTransformArgsArgs']]):
        pulumi.set(self, "transform", value)


@pulumi.type_token("anvil:aws:Bucket")
class Bucket(pulumi.ComponentResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 data_classification: Optional[pulumi.Input[_builtins.str]] = None,
                 lifecycle: Optional[pulumi.Input[_builtins.int]] = None,
                 transform: Optional[pulumi.Input[Union['BucketTransformArgsArgs', 'BucketTransformArgsArgsDict']]] = None,
                 __props__=None):
        """
        Create a Bucket resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: BucketArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Bucket resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param BucketArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(BucketArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 data_classification: Optional[pulumi.Input[_builtins.str]] = None,
                 lifecycle: Optional[pulumi.Input[_builtins.int]] = None,
                 transform: Optional[pulumi.Input[Union['BucketTransformArgsArgs', 'BucketTransformArgsArgsDict']]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is not None:
            raise ValueError('ComponentResource classes do not support opts.id')
        else:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = BucketArgs.__new__(BucketArgs)

            if data_classification is None and not opts.urn:
                raise TypeError("Missing required property 'data_classification'")
            __props__.__dict__["data_classification"] = data_classification
            __props__.__dict__["lifecycle"] = lifecycle
            __props__.__dict__["transform"] = transform
            __props__.__dict__["arn"] = None
            __props__.__dict__["bucket_name"] = None
        super(Bucket, __self__).__init__(
            'anvil:aws:Bucket',
            resource_name,
            __props__,
            opts,
            remote=True)

    @_builtins.property
    @pulumi.getter
    def arn(self) -> pulumi.Output[_builtins.str]:
        """
        The ARN of the S3 bucket.
        """
        return pulumi.get(self, "arn")

    @_builtins.property
    @pulumi.getter(name="bucketName")
    def bucket_name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the S3 bucket.
        """
        return pulumi.get(self, "bucket_name")

    def grant_read(self, target: "grants.GrantTarget", paths: Optional[list] = None, opts: Optional["grants.GrantOptions"] = None) -> None:
        """Grants read access on this resource."""
        name = f"{self._name}-{target.grant_name()}-read"
        arns = grants.build_resource_arns(self.arn, paths)
        grants.create_grant(self, name, target, ["s3:GetObject", "s3:ListBucket"], arns, opts)

    def grant_write(self, target: "grants.GrantTarget", paths: Optional[list] = None, opts: Optional["grants.GrantOptions"] = None) -> None:
        """Grants write access on this resource."""
        name = f"{self._name}-{target.grant_name()}-write"
        arns = grants.build_resource_arns(self.arn, paths)
        grants.create_grant(self, name, target, ["s3:PutObject"], arns, opts)

    def grant_read_write(self, target: "grants.GrantTarget", paths: Optional[list] = None, opts: Optional["grants.GrantOptions"] = None) -> None:
        """Grants read_write access on this resource."""
        name = f"{self._name}-{target.grant_name()}-read_write"
        arns = grants.build_resource_arns(self.arn, paths)
        grants.create_grant(self, name, target, ["s3:GetObject", "s3:ListBucket", "s3:PutObject"], arns, opts)

    def grant_delete(self, target: "grants.GrantTarget", paths: Optional[list] = None, opts: Optional["grants.GrantOptions"] = None) -> None:
        """Grants delete access on this resource."""
        name = f"{self._name}-{target.grant_name()}-delete"
        arns = grants.build_resource_arns(self.arn, paths)
        grants.create_grant(self, name, target, ["s3:DeleteObject"], arns, opts)

    def grant_full_access(self, target: "grants.GrantTarget", opts: Optional["grants.GrantOptions"] = None) -> None:
        """Grants full access on this resource. Prefer scoped grants."""
        if not opts or not opts.justification:
            pulumi.log.warn(
                f"⚠ {self._name} → {target.grant_name()}: full access granted with no justification.",
                self,
            )
        else:
            pulumi.log.info(
                f"ℹ {self._name} → {target.grant_name()}: full access granted. Justification: \"{opts.justification}\"",
                self,
            )
        name = f"{self._name}-{target.grant_name()}-fullaccess"
        arns = grants.build_resource_arns(self.arn, None)
        grants.create_grant(self, name, target, ["s3:GetObject", "s3:ListBucket", "s3:PutObject", "s3:DeleteObject"], arns, opts)

