# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from ._enums import *
from ._inputs import *
import pulumi_aws

__all__ = ['CognitoUserPoolArgs', 'CognitoUserPool']

@pulumi.input_type
class CognitoUserPoolArgs:
    def __init__(__self__, *,
                 app_client: Optional[pulumi.Input['CognitoUserPoolAppClientArgs']] = None,
                 attributes: Optional[pulumi.Input['CognitoUserPoolAttributesArgs']] = None,
                 email_configuration: Optional[pulumi.Input['CognitoUserPoolEmailConfigurationArgs']] = None,
                 hosted_ui: Optional[pulumi.Input['CognitoUserPoolHostedUiArgs']] = None,
                 identity_providers: Optional[pulumi.Input[Sequence[pulumi.Input['CognitoUserPoolIdentityProviderArgs']]]] = None,
                 mfa: Optional[pulumi.Input['CognitoUserPoolMfaArgs']] = None,
                 password_policy: Optional[pulumi.Input['CognitoUserPoolPasswordPolicyArgs']] = None,
                 transform: Optional[pulumi.Input['CognitoUserPoolTransformArgsArgs']] = None):
        """
        The set of arguments for constructing a CognitoUserPool resource.

        :param pulumi.Input['CognitoUserPoolAppClientArgs'] app_client: Default app client created with the user pool. Covers the 80% case of one application per pool. Use transform for additional clients.
        :param pulumi.Input['CognitoUserPoolAttributesArgs'] attributes: User attribute configuration. Controls sign-in identifiers and required attributes on sign-up.
        :param pulumi.Input['CognitoUserPoolEmailConfigurationArgs'] email_configuration: Email delivery configuration. Default: Cognito-managed email (5 emails/day limit). Set sesFromAddress for SES delivery in production.
        :param pulumi.Input['CognitoUserPoolHostedUiArgs'] hosted_ui: Hosted UI / Managed Login configuration. Omit to use the Cognito user pools API directly without a hosted sign-in page.
        :param pulumi.Input[Sequence[pulumi.Input['CognitoUserPoolIdentityProviderArgs']]] identity_providers: External identity providers to federate with this user pool. Supports Google, Facebook, LoginWithAmazon, SignInWithApple, OIDC, and SAML. Schema never changes per provider — add new providers by extending this array.
        :param pulumi.Input['CognitoUserPoolMfaArgs'] mfa: MFA configuration. TOTP requires no additional AWS resources. SMS requires an SNS caller ARN.
        :param pulumi.Input['CognitoUserPoolPasswordPolicyArgs'] password_policy: Password policy for the user pool. Anvil enforces a secure baseline by default — override only to strengthen.
        """
        if app_client is not None:
            pulumi.set(__self__, "app_client", app_client)
        if attributes is not None:
            pulumi.set(__self__, "attributes", attributes)
        if email_configuration is not None:
            pulumi.set(__self__, "email_configuration", email_configuration)
        if hosted_ui is not None:
            pulumi.set(__self__, "hosted_ui", hosted_ui)
        if identity_providers is not None:
            pulumi.set(__self__, "identity_providers", identity_providers)
        if mfa is not None:
            pulumi.set(__self__, "mfa", mfa)
        if password_policy is not None:
            pulumi.set(__self__, "password_policy", password_policy)
        if transform is not None:
            pulumi.set(__self__, "transform", transform)

    @_builtins.property
    @pulumi.getter(name="appClient")
    def app_client(self) -> Optional[pulumi.Input['CognitoUserPoolAppClientArgs']]:
        """
        Default app client created with the user pool. Covers the 80% case of one application per pool. Use transform for additional clients.
        """
        return pulumi.get(self, "app_client")

    @app_client.setter
    def app_client(self, value: Optional[pulumi.Input['CognitoUserPoolAppClientArgs']]):
        pulumi.set(self, "app_client", value)

    @_builtins.property
    @pulumi.getter
    def attributes(self) -> Optional[pulumi.Input['CognitoUserPoolAttributesArgs']]:
        """
        User attribute configuration. Controls sign-in identifiers and required attributes on sign-up.
        """
        return pulumi.get(self, "attributes")

    @attributes.setter
    def attributes(self, value: Optional[pulumi.Input['CognitoUserPoolAttributesArgs']]):
        pulumi.set(self, "attributes", value)

    @_builtins.property
    @pulumi.getter(name="emailConfiguration")
    def email_configuration(self) -> Optional[pulumi.Input['CognitoUserPoolEmailConfigurationArgs']]:
        """
        Email delivery configuration. Default: Cognito-managed email (5 emails/day limit). Set sesFromAddress for SES delivery in production.
        """
        return pulumi.get(self, "email_configuration")

    @email_configuration.setter
    def email_configuration(self, value: Optional[pulumi.Input['CognitoUserPoolEmailConfigurationArgs']]):
        pulumi.set(self, "email_configuration", value)

    @_builtins.property
    @pulumi.getter(name="hostedUi")
    def hosted_ui(self) -> Optional[pulumi.Input['CognitoUserPoolHostedUiArgs']]:
        """
        Hosted UI / Managed Login configuration. Omit to use the Cognito user pools API directly without a hosted sign-in page.
        """
        return pulumi.get(self, "hosted_ui")

    @hosted_ui.setter
    def hosted_ui(self, value: Optional[pulumi.Input['CognitoUserPoolHostedUiArgs']]):
        pulumi.set(self, "hosted_ui", value)

    @_builtins.property
    @pulumi.getter(name="identityProviders")
    def identity_providers(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['CognitoUserPoolIdentityProviderArgs']]]]:
        """
        External identity providers to federate with this user pool. Supports Google, Facebook, LoginWithAmazon, SignInWithApple, OIDC, and SAML. Schema never changes per provider — add new providers by extending this array.
        """
        return pulumi.get(self, "identity_providers")

    @identity_providers.setter
    def identity_providers(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['CognitoUserPoolIdentityProviderArgs']]]]):
        pulumi.set(self, "identity_providers", value)

    @_builtins.property
    @pulumi.getter
    def mfa(self) -> Optional[pulumi.Input['CognitoUserPoolMfaArgs']]:
        """
        MFA configuration. TOTP requires no additional AWS resources. SMS requires an SNS caller ARN.
        """
        return pulumi.get(self, "mfa")

    @mfa.setter
    def mfa(self, value: Optional[pulumi.Input['CognitoUserPoolMfaArgs']]):
        pulumi.set(self, "mfa", value)

    @_builtins.property
    @pulumi.getter(name="passwordPolicy")
    def password_policy(self) -> Optional[pulumi.Input['CognitoUserPoolPasswordPolicyArgs']]:
        """
        Password policy for the user pool. Anvil enforces a secure baseline by default — override only to strengthen.
        """
        return pulumi.get(self, "password_policy")

    @password_policy.setter
    def password_policy(self, value: Optional[pulumi.Input['CognitoUserPoolPasswordPolicyArgs']]):
        pulumi.set(self, "password_policy", value)

    @_builtins.property
    @pulumi.getter
    def transform(self) -> Optional[pulumi.Input['CognitoUserPoolTransformArgsArgs']]:
        return pulumi.get(self, "transform")

    @transform.setter
    def transform(self, value: Optional[pulumi.Input['CognitoUserPoolTransformArgsArgs']]):
        pulumi.set(self, "transform", value)


@pulumi.type_token("anvil:aws:CognitoUserPool")
class CognitoUserPool(pulumi.ComponentResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 app_client: Optional[pulumi.Input[Union['CognitoUserPoolAppClientArgs', 'CognitoUserPoolAppClientArgsDict']]] = None,
                 attributes: Optional[pulumi.Input[Union['CognitoUserPoolAttributesArgs', 'CognitoUserPoolAttributesArgsDict']]] = None,
                 email_configuration: Optional[pulumi.Input[Union['CognitoUserPoolEmailConfigurationArgs', 'CognitoUserPoolEmailConfigurationArgsDict']]] = None,
                 hosted_ui: Optional[pulumi.Input[Union['CognitoUserPoolHostedUiArgs', 'CognitoUserPoolHostedUiArgsDict']]] = None,
                 identity_providers: Optional[pulumi.Input[Sequence[pulumi.Input[Union['CognitoUserPoolIdentityProviderArgs', 'CognitoUserPoolIdentityProviderArgsDict']]]]] = None,
                 mfa: Optional[pulumi.Input[Union['CognitoUserPoolMfaArgs', 'CognitoUserPoolMfaArgsDict']]] = None,
                 password_policy: Optional[pulumi.Input[Union['CognitoUserPoolPasswordPolicyArgs', 'CognitoUserPoolPasswordPolicyArgsDict']]] = None,
                 transform: Optional[pulumi.Input[Union['CognitoUserPoolTransformArgsArgs', 'CognitoUserPoolTransformArgsArgsDict']]] = None,
                 __props__=None):
        """
        An Anvil-managed Cognito user pool. Tier 1 controls (deletion protection, enforced password policy, account recovery via email) are always on. Pair with CognitoAuth to protect API Gateway routes.


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Union['CognitoUserPoolAppClientArgs', 'CognitoUserPoolAppClientArgsDict']] app_client: Default app client created with the user pool. Covers the 80% case of one application per pool. Use transform for additional clients.
        :param pulumi.Input[Union['CognitoUserPoolAttributesArgs', 'CognitoUserPoolAttributesArgsDict']] attributes: User attribute configuration. Controls sign-in identifiers and required attributes on sign-up.
        :param pulumi.Input[Union['CognitoUserPoolEmailConfigurationArgs', 'CognitoUserPoolEmailConfigurationArgsDict']] email_configuration: Email delivery configuration. Default: Cognito-managed email (5 emails/day limit). Set sesFromAddress for SES delivery in production.
        :param pulumi.Input[Union['CognitoUserPoolHostedUiArgs', 'CognitoUserPoolHostedUiArgsDict']] hosted_ui: Hosted UI / Managed Login configuration. Omit to use the Cognito user pools API directly without a hosted sign-in page.
        :param pulumi.Input[Sequence[pulumi.Input[Union['CognitoUserPoolIdentityProviderArgs', 'CognitoUserPoolIdentityProviderArgsDict']]]] identity_providers: External identity providers to federate with this user pool. Supports Google, Facebook, LoginWithAmazon, SignInWithApple, OIDC, and SAML. Schema never changes per provider — add new providers by extending this array.
        :param pulumi.Input[Union['CognitoUserPoolMfaArgs', 'CognitoUserPoolMfaArgsDict']] mfa: MFA configuration. TOTP requires no additional AWS resources. SMS requires an SNS caller ARN.
        :param pulumi.Input[Union['CognitoUserPoolPasswordPolicyArgs', 'CognitoUserPoolPasswordPolicyArgsDict']] password_policy: Password policy for the user pool. Anvil enforces a secure baseline by default — override only to strengthen.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[CognitoUserPoolArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        An Anvil-managed Cognito user pool. Tier 1 controls (deletion protection, enforced password policy, account recovery via email) are always on. Pair with CognitoAuth to protect API Gateway routes.


        :param str resource_name: The name of the resource.
        :param CognitoUserPoolArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(CognitoUserPoolArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 app_client: Optional[pulumi.Input[Union['CognitoUserPoolAppClientArgs', 'CognitoUserPoolAppClientArgsDict']]] = None,
                 attributes: Optional[pulumi.Input[Union['CognitoUserPoolAttributesArgs', 'CognitoUserPoolAttributesArgsDict']]] = None,
                 email_configuration: Optional[pulumi.Input[Union['CognitoUserPoolEmailConfigurationArgs', 'CognitoUserPoolEmailConfigurationArgsDict']]] = None,
                 hosted_ui: Optional[pulumi.Input[Union['CognitoUserPoolHostedUiArgs', 'CognitoUserPoolHostedUiArgsDict']]] = None,
                 identity_providers: Optional[pulumi.Input[Sequence[pulumi.Input[Union['CognitoUserPoolIdentityProviderArgs', 'CognitoUserPoolIdentityProviderArgsDict']]]]] = None,
                 mfa: Optional[pulumi.Input[Union['CognitoUserPoolMfaArgs', 'CognitoUserPoolMfaArgsDict']]] = None,
                 password_policy: Optional[pulumi.Input[Union['CognitoUserPoolPasswordPolicyArgs', 'CognitoUserPoolPasswordPolicyArgsDict']]] = None,
                 transform: Optional[pulumi.Input[Union['CognitoUserPoolTransformArgsArgs', 'CognitoUserPoolTransformArgsArgsDict']]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is not None:
            raise ValueError('ComponentResource classes do not support opts.id')
        else:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = CognitoUserPoolArgs.__new__(CognitoUserPoolArgs)

            __props__.__dict__["app_client"] = app_client
            __props__.__dict__["attributes"] = attributes
            __props__.__dict__["email_configuration"] = email_configuration
            __props__.__dict__["hosted_ui"] = hosted_ui
            __props__.__dict__["identity_providers"] = identity_providers
            __props__.__dict__["mfa"] = mfa
            __props__.__dict__["password_policy"] = password_policy
            __props__.__dict__["transform"] = transform
            __props__.__dict__["app_client_id"] = None
            __props__.__dict__["app_client_secret"] = None
            __props__.__dict__["cloud_front_domain"] = None
            __props__.__dict__["endpoint"] = None
            __props__.__dict__["hosted_ui_domain"] = None
            __props__.__dict__["user_pool_arn"] = None
            __props__.__dict__["user_pool_id"] = None
        super(CognitoUserPool, __self__).__init__(
            'anvil:aws:CognitoUserPool',
            resource_name,
            __props__,
            opts,
            remote=True)

    @_builtins.property
    @pulumi.getter(name="appClientId")
    def app_client_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the default app client. Pass to CognitoAuth audience.
        """
        return pulumi.get(self, "app_client_id")

    @_builtins.property
    @pulumi.getter(name="appClientSecret")
    def app_client_secret(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The client secret of the default app client. Only populated when appClient.generateSecret is true. Treat as sensitive.
        """
        return pulumi.get(self, "app_client_secret")

    @_builtins.property
    @pulumi.getter(name="cloudFrontDomain")
    def cloud_front_domain(self) -> pulumi.Output[_builtins.str]:
        """
        The CloudFront distribution domain for the custom hosted UI. Only populated when hostedUi.customDomain is true. Create a Route53 alias record pointing hostedUi.domain to this value to complete DNS setup. Empty string for Cognito-managed domains.
        """
        return pulumi.get(self, "cloud_front_domain")

    @_builtins.property
    @pulumi.getter
    def endpoint(self) -> pulumi.Output[_builtins.str]:
        """
        The Cognito OIDC issuer URL. Format: https://cognito-idp.{region}.amazonaws.com/{userPoolId}. Pass directly to CognitoAuth if building the authorizer manually.
        """
        return pulumi.get(self, "endpoint")

    @_builtins.property
    @pulumi.getter(name="hostedUiDomain")
    def hosted_ui_domain(self) -> pulumi.Output[_builtins.str]:
        """
        The full hosted UI domain (e.g. https://auth.myapp.com or https://myprefix.auth.us-east-1.amazoncognito.com). Empty string if hostedUi is not configured.
        """
        return pulumi.get(self, "hosted_ui_domain")

    @_builtins.property
    @pulumi.getter(name="userPoolArn")
    def user_pool_arn(self) -> pulumi.Output[_builtins.str]:
        """
        The ARN of the Cognito user pool.
        """
        return pulumi.get(self, "user_pool_arn")

    @_builtins.property
    @pulumi.getter(name="userPoolId")
    def user_pool_id(self) -> pulumi.Output[_builtins.str]:
        """
        The Cognito user pool ID. Pass to CognitoAuth.userPoolId.
        """
        return pulumi.get(self, "user_pool_id")

