# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from ._enums import *
from ._inputs import *
import pulumi_aws

__all__ = ['DSQLArgs', 'DSQL']

@pulumi.input_type
class DSQLArgs:
    def __init__(__self__, *,
                 backup: Optional[pulumi.Input['DSQLBackupArgsArgs']] = None,
                 multi_region: Optional[pulumi.Input['DSQLMultiRegionArgsArgs']] = None,
                 schemas: Optional[pulumi.Input[Sequence[pulumi.Input['DSQLSchemaArgs']]]] = None,
                 transform: Optional[pulumi.Input['DsqlTransformArgsArgs']] = None,
                 vpc: Optional[pulumi.Input['DSQLVpcArgsArgs']] = None):
        """
        The set of arguments for constructing a DSQL resource.

        :param pulumi.Input['DSQLBackupArgsArgs'] backup: AWS Backup configuration. Omit to disable. When set, Anvil opts in the DSQL resource type per region, creates a backup plan with retention and schedule, and for multi-region clusters automatically adds cross-region copy rules.
        :param pulumi.Input['DSQLMultiRegionArgsArgs'] multi_region: Opt-in multi-region configuration. When set, Anvil creates two clusters in the specified regions and links them via ClusterPeering. When omitted, a single-region cluster is created in the provider's default region.
        :param pulumi.Input[Sequence[pulumi.Input['DSQLSchemaArgs']]] schemas: Schemas and the tables within them. Anvil creates each schema and table (additive-only — new tables/columns/indexes are applied; removals are left to humans). Omit to skip table management.
        :param pulumi.Input['DSQLVpcArgsArgs'] vpc: Optional VPC configuration. When set without hasNat, Anvil creates interface VPC endpoints (PrivateLink) per region so traffic stays on the AWS backbone. When omitted, the Lambda connects to the public DSQL endpoint over the internet using IAM auth tokens over TLS.
        """
        if backup is not None:
            pulumi.set(__self__, "backup", backup)
        if multi_region is not None:
            pulumi.set(__self__, "multi_region", multi_region)
        if schemas is not None:
            pulumi.set(__self__, "schemas", schemas)
        if transform is not None:
            pulumi.set(__self__, "transform", transform)
        if vpc is not None:
            pulumi.set(__self__, "vpc", vpc)

    @_builtins.property
    @pulumi.getter
    def backup(self) -> Optional[pulumi.Input['DSQLBackupArgsArgs']]:
        """
        AWS Backup configuration. Omit to disable. When set, Anvil opts in the DSQL resource type per region, creates a backup plan with retention and schedule, and for multi-region clusters automatically adds cross-region copy rules.
        """
        return pulumi.get(self, "backup")

    @backup.setter
    def backup(self, value: Optional[pulumi.Input['DSQLBackupArgsArgs']]):
        pulumi.set(self, "backup", value)

    @_builtins.property
    @pulumi.getter(name="multiRegion")
    def multi_region(self) -> Optional[pulumi.Input['DSQLMultiRegionArgsArgs']]:
        """
        Opt-in multi-region configuration. When set, Anvil creates two clusters in the specified regions and links them via ClusterPeering. When omitted, a single-region cluster is created in the provider's default region.
        """
        return pulumi.get(self, "multi_region")

    @multi_region.setter
    def multi_region(self, value: Optional[pulumi.Input['DSQLMultiRegionArgsArgs']]):
        pulumi.set(self, "multi_region", value)

    @_builtins.property
    @pulumi.getter
    def schemas(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['DSQLSchemaArgs']]]]:
        """
        Schemas and the tables within them. Anvil creates each schema and table (additive-only — new tables/columns/indexes are applied; removals are left to humans). Omit to skip table management.
        """
        return pulumi.get(self, "schemas")

    @schemas.setter
    def schemas(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['DSQLSchemaArgs']]]]):
        pulumi.set(self, "schemas", value)

    @_builtins.property
    @pulumi.getter
    def transform(self) -> Optional[pulumi.Input['DsqlTransformArgsArgs']]:
        return pulumi.get(self, "transform")

    @transform.setter
    def transform(self, value: Optional[pulumi.Input['DsqlTransformArgsArgs']]):
        pulumi.set(self, "transform", value)

    @_builtins.property
    @pulumi.getter
    def vpc(self) -> Optional[pulumi.Input['DSQLVpcArgsArgs']]:
        """
        Optional VPC configuration. When set without hasNat, Anvil creates interface VPC endpoints (PrivateLink) per region so traffic stays on the AWS backbone. When omitted, the Lambda connects to the public DSQL endpoint over the internet using IAM auth tokens over TLS.
        """
        return pulumi.get(self, "vpc")

    @vpc.setter
    def vpc(self, value: Optional[pulumi.Input['DSQLVpcArgsArgs']]):
        pulumi.set(self, "vpc", value)


@pulumi.type_token("anvil:aws:DSQL")
class DSQL(pulumi.ComponentResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 backup: Optional[pulumi.Input[Union['DSQLBackupArgsArgs', 'DSQLBackupArgsArgsDict']]] = None,
                 multi_region: Optional[pulumi.Input[Union['DSQLMultiRegionArgsArgs', 'DSQLMultiRegionArgsArgsDict']]] = None,
                 schemas: Optional[pulumi.Input[Sequence[pulumi.Input[Union['DSQLSchemaArgs', 'DSQLSchemaArgsDict']]]]] = None,
                 transform: Optional[pulumi.Input[Union['DsqlTransformArgsArgs', 'DsqlTransformArgsArgsDict']]] = None,
                 vpc: Optional[pulumi.Input[Union['DSQLVpcArgsArgs', 'DSQLVpcArgsArgsDict']]] = None,
                 __props__=None):
        """
        Serverless distributed PostgreSQL-compatible database. Secure-by-default Aurora DSQL cluster with optional multi-region active-active replication, IAM authentication, deploy-time role bootstrapping, and AWS Backup integration. No VPC required — connect directly via IAM auth tokens.


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Union['DSQLBackupArgsArgs', 'DSQLBackupArgsArgsDict']] backup: AWS Backup configuration. Omit to disable. When set, Anvil opts in the DSQL resource type per region, creates a backup plan with retention and schedule, and for multi-region clusters automatically adds cross-region copy rules.
        :param pulumi.Input[Union['DSQLMultiRegionArgsArgs', 'DSQLMultiRegionArgsArgsDict']] multi_region: Opt-in multi-region configuration. When set, Anvil creates two clusters in the specified regions and links them via ClusterPeering. When omitted, a single-region cluster is created in the provider's default region.
        :param pulumi.Input[Sequence[pulumi.Input[Union['DSQLSchemaArgs', 'DSQLSchemaArgsDict']]]] schemas: Schemas and the tables within them. Anvil creates each schema and table (additive-only — new tables/columns/indexes are applied; removals are left to humans). Omit to skip table management.
        :param pulumi.Input[Union['DSQLVpcArgsArgs', 'DSQLVpcArgsArgsDict']] vpc: Optional VPC configuration. When set without hasNat, Anvil creates interface VPC endpoints (PrivateLink) per region so traffic stays on the AWS backbone. When omitted, the Lambda connects to the public DSQL endpoint over the internet using IAM auth tokens over TLS.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[DSQLArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Serverless distributed PostgreSQL-compatible database. Secure-by-default Aurora DSQL cluster with optional multi-region active-active replication, IAM authentication, deploy-time role bootstrapping, and AWS Backup integration. No VPC required — connect directly via IAM auth tokens.


        :param str resource_name: The name of the resource.
        :param DSQLArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(DSQLArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 backup: Optional[pulumi.Input[Union['DSQLBackupArgsArgs', 'DSQLBackupArgsArgsDict']]] = None,
                 multi_region: Optional[pulumi.Input[Union['DSQLMultiRegionArgsArgs', 'DSQLMultiRegionArgsArgsDict']]] = None,
                 schemas: Optional[pulumi.Input[Sequence[pulumi.Input[Union['DSQLSchemaArgs', 'DSQLSchemaArgsDict']]]]] = None,
                 transform: Optional[pulumi.Input[Union['DsqlTransformArgsArgs', 'DsqlTransformArgsArgsDict']]] = None,
                 vpc: Optional[pulumi.Input[Union['DSQLVpcArgsArgs', 'DSQLVpcArgsArgsDict']]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is not None:
            raise ValueError('ComponentResource classes do not support opts.id')
        else:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = DSQLArgs.__new__(DSQLArgs)

            __props__.__dict__["backup"] = backup
            __props__.__dict__["multi_region"] = multi_region
            __props__.__dict__["schemas"] = schemas
            __props__.__dict__["transform"] = transform
            __props__.__dict__["vpc"] = vpc
            __props__.__dict__["cluster_arns"] = None
            __props__.__dict__["endpoint"] = None
            __props__.__dict__["endpoints"] = None
            __props__.__dict__["roles_table_name"] = None
            __props__.__dict__["vpc_endpoint_ids"] = None
            __props__.__dict__["vpc_endpoint_security_group_ids"] = None
        super(DSQL, __self__).__init__(
            'anvil:aws:DSQL',
            resource_name,
            __props__,
            opts,
            remote=True)

    @_builtins.property
    @pulumi.getter(name="clusterArns")
    def cluster_arns(self) -> pulumi.Output[Mapping[str, _builtins.str]]:
        """
        Map of region to cluster ARN. Single-region: one entry. Multi-region: one entry per region. e.g. { "us-east-1": "arn:aws:dsql:us-east-1:..." }.
        """
        return pulumi.get(self, "cluster_arns")

    @_builtins.property
    @pulumi.getter
    def endpoint(self) -> pulumi.Output[_builtins.str]:
        """
        The single cluster endpoint for the provider's default region. Convenience for the common single-region case — pass straight to a Lambda env var: { DSQL_ENDPOINT: dsql.endpoint }. For multi-region this is the local-region endpoint; use endpoints[region] for another.
        """
        return pulumi.get(self, "endpoint")

    @_builtins.property
    @pulumi.getter
    def endpoints(self) -> pulumi.Output[Mapping[str, _builtins.str]]:
        """
        Map of region to cluster endpoint. Single-region: one entry keyed by the provider region. Multi-region: one entry per region. e.g. { "us-east-1": "abc123.dsql.us-east-1.on.aws" }. Pass the relevant endpoint to your Lambda via environment variables.
        """
        return pulumi.get(self, "endpoints")

    @_builtins.property
    @pulumi.getter(name="rolesTableName")
    def roles_table_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        DynamoDB table name for role bootstrap. Passed to DSQLConnect (via grantConnect) so it can create the IAM role-mapping item. Empty when no roles are configured.
        """
        return pulumi.get(self, "roles_table_name")

    @_builtins.property
    @pulumi.getter(name="vpcEndpointIds")
    def vpc_endpoint_ids(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        Map of region to VPC endpoint ID. Only populated when vpc is set and hasNat is false. Pass to LambdaVpcEndpointArgs.endpointId.
        """
        return pulumi.get(self, "vpc_endpoint_ids")

    @_builtins.property
    @pulumi.getter(name="vpcEndpointSecurityGroupIds")
    def vpc_endpoint_security_group_ids(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        Map of region to VPC endpoint security group ID. Only populated when vpc is set and hasNat is false. Pass to LambdaVpcEndpointArgs.securityGroupId so Anvil can wire the egress rule from the Lambda SG to the endpoint SG on port 5432.
        """
        return pulumi.get(self, "vpc_endpoint_security_group_ids")

