# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from ._enums import *
from ._inputs import *
import pulumi_aws
from typing import Optional
from anvil_cloud import grants


__all__ = ['DSQLArgs', 'DSQL']

@pulumi.input_type
class DSQLArgs:
    def __init__(__self__, *,
                 backup: Optional[pulumi.Input['DSQLBackupArgsArgs']] = None,
                 multi_region: Optional[pulumi.Input['DSQLMultiRegionArgsArgs']] = None,
                 roles: Optional[pulumi.Input[Sequence[pulumi.Input['DSQLRoleArgs']]]] = None,
                 transform: Optional[pulumi.Input['DsqlTransformArgsArgs']] = None,
                 vpc: Optional[pulumi.Input['DSQLVpcArgsArgs']] = None):
        """
        The set of arguments for constructing a DSQL resource.

        :param pulumi.Input['DSQLBackupArgsArgs'] backup: AWS Backup configuration. Omit to disable. When set, Anvil opts in the DSQL resource type per region, creates a backup plan with retention and schedule, and for multi-region clusters automatically adds cross-region copy rules.
        :param pulumi.Input['DSQLMultiRegionArgsArgs'] multi_region: Opt-in multi-region configuration. When set, Anvil creates two clusters in the specified regions and links them via ClusterPeering. When omitted, a single-region cluster is created in the provider's default region.
        :param pulumi.Input[Sequence[pulumi.Input['DSQLRoleArgs']]] roles: Database roles to bootstrap at deploy time. Anvil connects as admin using the deployer's credentials and runs the SQL to create schemas, roles, IAM grants, and table-level permissions. Only re-runs when role definitions change. Omit entirely to skip bootstrapping — useful when managing schema separately.
        :param pulumi.Input['DSQLVpcArgsArgs'] vpc: Optional VPC configuration. When set without hasNat, Anvil creates interface VPC endpoints (PrivateLink) per region so traffic stays on the AWS backbone. When omitted, the Lambda connects to the public DSQL endpoint over the internet using IAM auth tokens over TLS.
        """
        if backup is not None:
            pulumi.set(__self__, "backup", backup)
        if multi_region is not None:
            pulumi.set(__self__, "multi_region", multi_region)
        if roles is not None:
            pulumi.set(__self__, "roles", roles)
        if transform is not None:
            pulumi.set(__self__, "transform", transform)
        if vpc is not None:
            pulumi.set(__self__, "vpc", vpc)

    @_builtins.property
    @pulumi.getter
    def backup(self) -> Optional[pulumi.Input['DSQLBackupArgsArgs']]:
        """
        AWS Backup configuration. Omit to disable. When set, Anvil opts in the DSQL resource type per region, creates a backup plan with retention and schedule, and for multi-region clusters automatically adds cross-region copy rules.
        """
        return pulumi.get(self, "backup")

    @backup.setter
    def backup(self, value: Optional[pulumi.Input['DSQLBackupArgsArgs']]):
        pulumi.set(self, "backup", value)

    @_builtins.property
    @pulumi.getter(name="multiRegion")
    def multi_region(self) -> Optional[pulumi.Input['DSQLMultiRegionArgsArgs']]:
        """
        Opt-in multi-region configuration. When set, Anvil creates two clusters in the specified regions and links them via ClusterPeering. When omitted, a single-region cluster is created in the provider's default region.
        """
        return pulumi.get(self, "multi_region")

    @multi_region.setter
    def multi_region(self, value: Optional[pulumi.Input['DSQLMultiRegionArgsArgs']]):
        pulumi.set(self, "multi_region", value)

    @_builtins.property
    @pulumi.getter
    def roles(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['DSQLRoleArgs']]]]:
        """
        Database roles to bootstrap at deploy time. Anvil connects as admin using the deployer's credentials and runs the SQL to create schemas, roles, IAM grants, and table-level permissions. Only re-runs when role definitions change. Omit entirely to skip bootstrapping — useful when managing schema separately.
        """
        return pulumi.get(self, "roles")

    @roles.setter
    def roles(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['DSQLRoleArgs']]]]):
        pulumi.set(self, "roles", value)

    @_builtins.property
    @pulumi.getter
    def transform(self) -> Optional[pulumi.Input['DsqlTransformArgsArgs']]:
        return pulumi.get(self, "transform")

    @transform.setter
    def transform(self, value: Optional[pulumi.Input['DsqlTransformArgsArgs']]):
        pulumi.set(self, "transform", value)

    @_builtins.property
    @pulumi.getter
    def vpc(self) -> Optional[pulumi.Input['DSQLVpcArgsArgs']]:
        """
        Optional VPC configuration. When set without hasNat, Anvil creates interface VPC endpoints (PrivateLink) per region so traffic stays on the AWS backbone. When omitted, the Lambda connects to the public DSQL endpoint over the internet using IAM auth tokens over TLS.
        """
        return pulumi.get(self, "vpc")

    @vpc.setter
    def vpc(self, value: Optional[pulumi.Input['DSQLVpcArgsArgs']]):
        pulumi.set(self, "vpc", value)


@pulumi.type_token("anvil:aws:DSQL")
class DSQL(pulumi.ComponentResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 backup: Optional[pulumi.Input[Union['DSQLBackupArgsArgs', 'DSQLBackupArgsArgsDict']]] = None,
                 multi_region: Optional[pulumi.Input[Union['DSQLMultiRegionArgsArgs', 'DSQLMultiRegionArgsArgsDict']]] = None,
                 roles: Optional[pulumi.Input[Sequence[pulumi.Input[Union['DSQLRoleArgs', 'DSQLRoleArgsDict']]]]] = None,
                 transform: Optional[pulumi.Input[Union['DsqlTransformArgsArgs', 'DsqlTransformArgsArgsDict']]] = None,
                 vpc: Optional[pulumi.Input[Union['DSQLVpcArgsArgs', 'DSQLVpcArgsArgsDict']]] = None,
                 __props__=None):
        """
        Serverless distributed PostgreSQL-compatible database. Secure-by-default Aurora DSQL cluster with optional multi-region active-active replication, IAM authentication, deploy-time role bootstrapping, and AWS Backup integration. No VPC required — connect directly via IAM auth tokens.


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Union['DSQLBackupArgsArgs', 'DSQLBackupArgsArgsDict']] backup: AWS Backup configuration. Omit to disable. When set, Anvil opts in the DSQL resource type per region, creates a backup plan with retention and schedule, and for multi-region clusters automatically adds cross-region copy rules.
        :param pulumi.Input[Union['DSQLMultiRegionArgsArgs', 'DSQLMultiRegionArgsArgsDict']] multi_region: Opt-in multi-region configuration. When set, Anvil creates two clusters in the specified regions and links them via ClusterPeering. When omitted, a single-region cluster is created in the provider's default region.
        :param pulumi.Input[Sequence[pulumi.Input[Union['DSQLRoleArgs', 'DSQLRoleArgsDict']]]] roles: Database roles to bootstrap at deploy time. Anvil connects as admin using the deployer's credentials and runs the SQL to create schemas, roles, IAM grants, and table-level permissions. Only re-runs when role definitions change. Omit entirely to skip bootstrapping — useful when managing schema separately.
        :param pulumi.Input[Union['DSQLVpcArgsArgs', 'DSQLVpcArgsArgsDict']] vpc: Optional VPC configuration. When set without hasNat, Anvil creates interface VPC endpoints (PrivateLink) per region so traffic stays on the AWS backbone. When omitted, the Lambda connects to the public DSQL endpoint over the internet using IAM auth tokens over TLS.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[DSQLArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Serverless distributed PostgreSQL-compatible database. Secure-by-default Aurora DSQL cluster with optional multi-region active-active replication, IAM authentication, deploy-time role bootstrapping, and AWS Backup integration. No VPC required — connect directly via IAM auth tokens.


        :param str resource_name: The name of the resource.
        :param DSQLArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(DSQLArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 backup: Optional[pulumi.Input[Union['DSQLBackupArgsArgs', 'DSQLBackupArgsArgsDict']]] = None,
                 multi_region: Optional[pulumi.Input[Union['DSQLMultiRegionArgsArgs', 'DSQLMultiRegionArgsArgsDict']]] = None,
                 roles: Optional[pulumi.Input[Sequence[pulumi.Input[Union['DSQLRoleArgs', 'DSQLRoleArgsDict']]]]] = None,
                 transform: Optional[pulumi.Input[Union['DsqlTransformArgsArgs', 'DsqlTransformArgsArgsDict']]] = None,
                 vpc: Optional[pulumi.Input[Union['DSQLVpcArgsArgs', 'DSQLVpcArgsArgsDict']]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is not None:
            raise ValueError('ComponentResource classes do not support opts.id')
        else:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = DSQLArgs.__new__(DSQLArgs)

            __props__.__dict__["backup"] = backup
            __props__.__dict__["multi_region"] = multi_region
            __props__.__dict__["roles"] = roles
            __props__.__dict__["transform"] = transform
            __props__.__dict__["vpc"] = vpc
            __props__.__dict__["cluster_arns"] = None
            __props__.__dict__["endpoints"] = None
            __props__.__dict__["vpc_endpoint_ids"] = None
            __props__.__dict__["vpc_endpoint_security_group_ids"] = None
        super(DSQL, __self__).__init__(
            'anvil:aws:DSQL',
            resource_name,
            __props__,
            opts,
            remote=True)

    @_builtins.property
    @pulumi.getter(name="clusterArns")
    def cluster_arns(self) -> pulumi.Output[Mapping[str, _builtins.str]]:
        """
        Map of region to cluster ARN. Single-region: one entry. Multi-region: one entry per region. e.g. { "us-east-1": "arn:aws:dsql:us-east-1:..." }.
        """
        return pulumi.get(self, "cluster_arns")

    @_builtins.property
    @pulumi.getter
    def endpoints(self) -> pulumi.Output[Mapping[str, _builtins.str]]:
        """
        Map of region to cluster endpoint. Single-region: one entry keyed by the provider region. Multi-region: one entry per region. e.g. { "us-east-1": "abc123.dsql.us-east-1.on.aws" }. Pass the relevant endpoint to your Lambda via environment variables.
        """
        return pulumi.get(self, "endpoints")

    @_builtins.property
    @pulumi.getter(name="vpcEndpointIds")
    def vpc_endpoint_ids(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        Map of region to VPC endpoint ID. Only populated when vpc is set and hasNat is false. Pass to LambdaVpcEndpointArgs.endpointId.
        """
        return pulumi.get(self, "vpc_endpoint_ids")

    @_builtins.property
    @pulumi.getter(name="vpcEndpointSecurityGroupIds")
    def vpc_endpoint_security_group_ids(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        Map of region to VPC endpoint security group ID. Only populated when vpc is set and hasNat is false. Pass to LambdaVpcEndpointArgs.securityGroupId so Anvil can wire the egress rule from the Lambda SG to the endpoint SG on port 5432.
        """
        return pulumi.get(self, "vpc_endpoint_security_group_ids")

    def grant_connect(self, target: "grants.GrantTarget", db_role: str, opts: Optional["grants.GrantOptions"] = None) -> None:
        """Grants connect access on this dsql to the target's execution role.
        Scoped to all ARNs in cluster_arns — one per region.
        """
        import json
        import pulumi_aws as aws
        name = f"{self._name}-{target.grant_name()}-connect"
        policy_document = self.cluster_arns.apply(
            lambda arns: json.dumps({
                "Version": "2012-10-17",
                "Statement": [{"Effect": "Allow", "Action": ["dsql:DbConnect"], "Resource": list(arns.values())}],
            })
        )
        role_name = target.grant_role_arn().apply(
            lambda arn: arn[arn.rfind("/") + 1:] if "/" in arn else arn
        )
        aws.iam.RolePolicy(name, role=role_name, policy=policy_document, opts=pulumi.ResourceOptions(parent=self))

