# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from ._enums import *
from ._inputs import *
import pulumi_aws
from typing import Optional
from anvil_cloud import grants


__all__ = ['DynamoDBArgs', 'DynamoDB']

@pulumi.input_type
class DynamoDBArgs:
    def __init__(__self__, *,
                 hash_key: pulumi.Input['DynamoDBKeyAttributeArgs'],
                 global_secondary_indexes: Optional[pulumi.Input[Sequence[pulumi.Input['DynamoDBGlobalSecondaryIndexArgs']]]] = None,
                 kms_key_arn: Optional[pulumi.Input[_builtins.str]] = None,
                 range_key: Optional[pulumi.Input['DynamoDBKeyAttributeArgs']] = None,
                 stream: Optional[pulumi.Input['DynamoDBStreamArgs']] = None,
                 transform: Optional[pulumi.Input['DynamoTransformArgsArgs']] = None,
                 ttl_attribute: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a DynamoDB resource.

        :param pulumi.Input['DynamoDBKeyAttributeArgs'] hash_key: Primary hash (partition) key. Required.
        :param pulumi.Input[Sequence[pulumi.Input['DynamoDBGlobalSecondaryIndexArgs']]] global_secondary_indexes: Global Secondary Indexes. All GSI key types must be explicitly declared — Anvil derives attributeDefinitions automatically from all declared keys.
        :param pulumi.Input[_builtins.str] kms_key_arn: Tier 2 opt-in. ARN of a KMS CMK for encryption at rest. If omitted, AWS_OWNED_KMS is used (Tier 1 default — always on, zero cost). Use this for compliance workloads requiring key rotation control, audit trail, or the ability to revoke access by disabling the key.
        :param pulumi.Input['DynamoDBKeyAttributeArgs'] range_key: Primary range (sort) key. Optional.
        :param pulumi.Input['DynamoDBStreamArgs'] stream: DynamoDB Streams configuration. Opt-in. Enables change data capture on the table.
        :param pulumi.Input[_builtins.str] ttl_attribute: Name of the attribute used for TTL (time-to-live). Items with this attribute set to a past Unix timestamp are automatically deleted by DynamoDB.
        """
        pulumi.set(__self__, "hash_key", hash_key)
        if global_secondary_indexes is not None:
            pulumi.set(__self__, "global_secondary_indexes", global_secondary_indexes)
        if kms_key_arn is not None:
            pulumi.set(__self__, "kms_key_arn", kms_key_arn)
        if range_key is not None:
            pulumi.set(__self__, "range_key", range_key)
        if stream is not None:
            pulumi.set(__self__, "stream", stream)
        if transform is not None:
            pulumi.set(__self__, "transform", transform)
        if ttl_attribute is not None:
            pulumi.set(__self__, "ttl_attribute", ttl_attribute)

    @_builtins.property
    @pulumi.getter(name="hashKey")
    def hash_key(self) -> pulumi.Input['DynamoDBKeyAttributeArgs']:
        """
        Primary hash (partition) key. Required.
        """
        return pulumi.get(self, "hash_key")

    @hash_key.setter
    def hash_key(self, value: pulumi.Input['DynamoDBKeyAttributeArgs']):
        pulumi.set(self, "hash_key", value)

    @_builtins.property
    @pulumi.getter(name="globalSecondaryIndexes")
    def global_secondary_indexes(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['DynamoDBGlobalSecondaryIndexArgs']]]]:
        """
        Global Secondary Indexes. All GSI key types must be explicitly declared — Anvil derives attributeDefinitions automatically from all declared keys.
        """
        return pulumi.get(self, "global_secondary_indexes")

    @global_secondary_indexes.setter
    def global_secondary_indexes(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['DynamoDBGlobalSecondaryIndexArgs']]]]):
        pulumi.set(self, "global_secondary_indexes", value)

    @_builtins.property
    @pulumi.getter(name="kmsKeyArn")
    def kms_key_arn(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Tier 2 opt-in. ARN of a KMS CMK for encryption at rest. If omitted, AWS_OWNED_KMS is used (Tier 1 default — always on, zero cost). Use this for compliance workloads requiring key rotation control, audit trail, or the ability to revoke access by disabling the key.
        """
        return pulumi.get(self, "kms_key_arn")

    @kms_key_arn.setter
    def kms_key_arn(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "kms_key_arn", value)

    @_builtins.property
    @pulumi.getter(name="rangeKey")
    def range_key(self) -> Optional[pulumi.Input['DynamoDBKeyAttributeArgs']]:
        """
        Primary range (sort) key. Optional.
        """
        return pulumi.get(self, "range_key")

    @range_key.setter
    def range_key(self, value: Optional[pulumi.Input['DynamoDBKeyAttributeArgs']]):
        pulumi.set(self, "range_key", value)

    @_builtins.property
    @pulumi.getter
    def stream(self) -> Optional[pulumi.Input['DynamoDBStreamArgs']]:
        """
        DynamoDB Streams configuration. Opt-in. Enables change data capture on the table.
        """
        return pulumi.get(self, "stream")

    @stream.setter
    def stream(self, value: Optional[pulumi.Input['DynamoDBStreamArgs']]):
        pulumi.set(self, "stream", value)

    @_builtins.property
    @pulumi.getter
    def transform(self) -> Optional[pulumi.Input['DynamoTransformArgsArgs']]:
        return pulumi.get(self, "transform")

    @transform.setter
    def transform(self, value: Optional[pulumi.Input['DynamoTransformArgsArgs']]):
        pulumi.set(self, "transform", value)

    @_builtins.property
    @pulumi.getter(name="ttlAttribute")
    def ttl_attribute(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Name of the attribute used for TTL (time-to-live). Items with this attribute set to a past Unix timestamp are automatically deleted by DynamoDB.
        """
        return pulumi.get(self, "ttl_attribute")

    @ttl_attribute.setter
    def ttl_attribute(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "ttl_attribute", value)


@pulumi.type_token("anvil:aws:DynamoDB")
class DynamoDB(pulumi.ComponentResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 global_secondary_indexes: Optional[pulumi.Input[Sequence[pulumi.Input[Union['DynamoDBGlobalSecondaryIndexArgs', 'DynamoDBGlobalSecondaryIndexArgsDict']]]]] = None,
                 hash_key: Optional[pulumi.Input[Union['DynamoDBKeyAttributeArgs', 'DynamoDBKeyAttributeArgsDict']]] = None,
                 kms_key_arn: Optional[pulumi.Input[_builtins.str]] = None,
                 range_key: Optional[pulumi.Input[Union['DynamoDBKeyAttributeArgs', 'DynamoDBKeyAttributeArgsDict']]] = None,
                 stream: Optional[pulumi.Input[Union['DynamoDBStreamArgs', 'DynamoDBStreamArgsDict']]] = None,
                 transform: Optional[pulumi.Input[Union['DynamoTransformArgsArgs', 'DynamoTransformArgsArgsDict']]] = None,
                 ttl_attribute: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Serverless key-value and document store. Secure-by-default DynamoDB table with GSI support, optional streams, and Lambda/EventBridge consumers. First data layer component — pairs naturally with anvil.aws.Lambda.


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[Union['DynamoDBGlobalSecondaryIndexArgs', 'DynamoDBGlobalSecondaryIndexArgsDict']]]] global_secondary_indexes: Global Secondary Indexes. All GSI key types must be explicitly declared — Anvil derives attributeDefinitions automatically from all declared keys.
        :param pulumi.Input[Union['DynamoDBKeyAttributeArgs', 'DynamoDBKeyAttributeArgsDict']] hash_key: Primary hash (partition) key. Required.
        :param pulumi.Input[_builtins.str] kms_key_arn: Tier 2 opt-in. ARN of a KMS CMK for encryption at rest. If omitted, AWS_OWNED_KMS is used (Tier 1 default — always on, zero cost). Use this for compliance workloads requiring key rotation control, audit trail, or the ability to revoke access by disabling the key.
        :param pulumi.Input[Union['DynamoDBKeyAttributeArgs', 'DynamoDBKeyAttributeArgsDict']] range_key: Primary range (sort) key. Optional.
        :param pulumi.Input[Union['DynamoDBStreamArgs', 'DynamoDBStreamArgsDict']] stream: DynamoDB Streams configuration. Opt-in. Enables change data capture on the table.
        :param pulumi.Input[_builtins.str] ttl_attribute: Name of the attribute used for TTL (time-to-live). Items with this attribute set to a past Unix timestamp are automatically deleted by DynamoDB.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: DynamoDBArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Serverless key-value and document store. Secure-by-default DynamoDB table with GSI support, optional streams, and Lambda/EventBridge consumers. First data layer component — pairs naturally with anvil.aws.Lambda.


        :param str resource_name: The name of the resource.
        :param DynamoDBArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(DynamoDBArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 global_secondary_indexes: Optional[pulumi.Input[Sequence[pulumi.Input[Union['DynamoDBGlobalSecondaryIndexArgs', 'DynamoDBGlobalSecondaryIndexArgsDict']]]]] = None,
                 hash_key: Optional[pulumi.Input[Union['DynamoDBKeyAttributeArgs', 'DynamoDBKeyAttributeArgsDict']]] = None,
                 kms_key_arn: Optional[pulumi.Input[_builtins.str]] = None,
                 range_key: Optional[pulumi.Input[Union['DynamoDBKeyAttributeArgs', 'DynamoDBKeyAttributeArgsDict']]] = None,
                 stream: Optional[pulumi.Input[Union['DynamoDBStreamArgs', 'DynamoDBStreamArgsDict']]] = None,
                 transform: Optional[pulumi.Input[Union['DynamoTransformArgsArgs', 'DynamoTransformArgsArgsDict']]] = None,
                 ttl_attribute: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is not None:
            raise ValueError('ComponentResource classes do not support opts.id')
        else:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = DynamoDBArgs.__new__(DynamoDBArgs)

            __props__.__dict__["global_secondary_indexes"] = global_secondary_indexes
            if hash_key is None and not opts.urn:
                raise TypeError("Missing required property 'hash_key'")
            __props__.__dict__["hash_key"] = hash_key
            __props__.__dict__["kms_key_arn"] = kms_key_arn
            __props__.__dict__["range_key"] = range_key
            __props__.__dict__["stream"] = stream
            __props__.__dict__["transform"] = transform
            __props__.__dict__["ttl_attribute"] = ttl_attribute
            __props__.__dict__["stream_arn"] = None
            __props__.__dict__["table_arn"] = None
            __props__.__dict__["table_name"] = None
        super(DynamoDB, __self__).__init__(
            'anvil:aws:DynamoDB',
            resource_name,
            __props__,
            opts,
            remote=True)

    @_builtins.property
    @pulumi.getter(name="streamArn")
    def stream_arn(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The ARN of the DynamoDB stream. Only present when stream is enabled.
        """
        return pulumi.get(self, "stream_arn")

    @_builtins.property
    @pulumi.getter(name="tableArn")
    def table_arn(self) -> pulumi.Output[_builtins.str]:
        """
        The ARN of the DynamoDB table.
        """
        return pulumi.get(self, "table_arn")

    @_builtins.property
    @pulumi.getter(name="tableName")
    def table_name(self) -> pulumi.Output[_builtins.str]:
        """
        The physical DynamoDB table name. Scoped as {name}-{stage}.
        """
        return pulumi.get(self, "table_name")

      def grant_read(self, target: "grants.GrantTarget", indexes: Optional[list] = None, justification: Optional[str] = None) -> None:
          """Grants read access on this resource.

          Args:
              target: The compute resource to grant access to.
              indexes: Optional list of GSI names to scope access (e.g. ["by_status"]).
                       If omitted, grants table access only — no index access.
              justification: Optional audit trail note.
          """
          name = f"{self._name}-{target.grant_name()}-read"
          index_paths = [f"index/{i}" for i in indexes] if indexes else None
          arns = grants.build_resource_arns(self.tableArn, index_paths)
          grants.create_grant(self, name, target, ["dynamodb:GetItem", "dynamodb:BatchGetItem", "dynamodb:Query", "dynamodb:Scan"], arns, grants.GrantOptions(justification=justification) if justification else None)
  
      def grant_write(self, target: "grants.GrantTarget", indexes: Optional[list] = None, justification: Optional[str] = None) -> None:
          """Grants write access on this resource.

          Args:
              target: The compute resource to grant access to.
              indexes: Optional list of GSI names to scope access (e.g. ["by_status"]).
                       If omitted, grants table access only — no index access.
              justification: Optional audit trail note.
          """
          name = f"{self._name}-{target.grant_name()}-write"
          index_paths = [f"index/{i}" for i in indexes] if indexes else None
          arns = grants.build_resource_arns(self.tableArn, index_paths)
          grants.create_grant(self, name, target, ["dynamodb:PutItem", "dynamodb:UpdateItem", "dynamodb:BatchWriteItem"], arns, grants.GrantOptions(justification=justification) if justification else None)
  
      def grant_read_write(self, target: "grants.GrantTarget", indexes: Optional[list] = None, justification: Optional[str] = None) -> None:
          """Grants readwrite access on this resource.

          Args:
              target: The compute resource to grant access to.
              indexes: Optional list of GSI names to scope access (e.g. ["by_status"]).
                       If omitted, grants table access only — no index access.
              justification: Optional audit trail note.
          """
          name = f"{self._name}-{target.grant_name()}-readwrite"
          index_paths = [f"index/{i}" for i in indexes] if indexes else None
          arns = grants.build_resource_arns(self.tableArn, index_paths)
          grants.create_grant(self, name, target, ["dynamodb:GetItem", "dynamodb:BatchGetItem", "dynamodb:Query", "dynamodb:Scan", "dynamodb:PutItem", "dynamodb:UpdateItem", "dynamodb:BatchWriteItem"], arns, grants.GrantOptions(justification=justification) if justification else None)
  
      def grant_delete(self, target: "grants.GrantTarget", indexes: Optional[list] = None, justification: Optional[str] = None) -> None:
          """Grants delete access on this resource.

          Args:
              target: The compute resource to grant access to.
              indexes: Optional list of GSI names to scope access (e.g. ["by_status"]).
                       If omitted, grants table access only — no index access.
              justification: Optional audit trail note.
          """
          name = f"{self._name}-{target.grant_name()}-delete"
          index_paths = [f"index/{i}" for i in indexes] if indexes else None
          arns = grants.build_resource_arns(self.tableArn, index_paths)
          grants.create_grant(self, name, target, ["dynamodb:DeleteItem"], arns, grants.GrantOptions(justification=justification) if justification else None)
  
