# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from ._inputs import *
import pulumi_aws

__all__ = ['LambdaArgs', 'Lambda']

@pulumi.input_type
class LambdaArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[_builtins.str],
                 transform: Optional[pulumi.Input['LambdaTransformArgsArgs']] = None,
                 vpc: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a Lambda resource.

        :param pulumi.Input[_builtins.str] name: The logical name of the Lambda function.
        :param pulumi.Input[_builtins.str] vpc: The ID of the AWS VPC to deploy this function into.
        """
        pulumi.set(__self__, "name", name)
        if transform is not None:
            pulumi.set(__self__, "transform", transform)
        if vpc is not None:
            pulumi.set(__self__, "vpc", vpc)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        The logical name of the Lambda function.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def transform(self) -> Optional[pulumi.Input['LambdaTransformArgsArgs']]:
        return pulumi.get(self, "transform")

    @transform.setter
    def transform(self, value: Optional[pulumi.Input['LambdaTransformArgsArgs']]):
        pulumi.set(self, "transform", value)

    @_builtins.property
    @pulumi.getter
    def vpc(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The ID of the AWS VPC to deploy this function into.
        """
        return pulumi.get(self, "vpc")

    @vpc.setter
    def vpc(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "vpc", value)


@pulumi.type_token("anvil:aws:Lambda")
class Lambda(pulumi.ComponentResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 transform: Optional[pulumi.Input[Union['LambdaTransformArgsArgs', 'LambdaTransformArgsArgsDict']]] = None,
                 vpc: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a Lambda resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] name: The logical name of the Lambda function.
        :param pulumi.Input[_builtins.str] vpc: The ID of the AWS VPC to deploy this function into.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: LambdaArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Lambda resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param LambdaArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(LambdaArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 transform: Optional[pulumi.Input[Union['LambdaTransformArgsArgs', 'LambdaTransformArgsArgsDict']]] = None,
                 vpc: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is not None:
            raise ValueError('ComponentResource classes do not support opts.id')
        else:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = LambdaArgs.__new__(LambdaArgs)

            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["transform"] = transform
            __props__.__dict__["vpc"] = vpc
        super(Lambda, __self__).__init__(
            'anvil:aws:Lambda',
            resource_name,
            __props__,
            opts,
            remote=True)

