# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from ._inputs import *

__all__ = ['QueueArgs', 'Queue']

@pulumi.input_type
class QueueArgs:
    def __init__(__self__, *,
                 consumer: Optional[pulumi.Input['QueueConsumerArgsArgs']] = None,
                 dlq: Optional[pulumi.Input['QueueDlqArgsArgs']] = None,
                 fifo: Optional[pulumi.Input[_builtins.bool]] = None,
                 transform: Optional[pulumi.Input['QueueTransformArgsArgs']] = None):
        """
        The set of arguments for constructing a Queue resource.

        :param pulumi.Input['QueueConsumerArgsArgs'] consumer: Wires a compute resource to consume messages from this queue. Creates the event source mapping (trigger) and grants the necessary IAM permissions automatically.
        :param pulumi.Input['QueueDlqArgsArgs'] dlq: Dead letter queue configuration. Always provisioned — messages that fail processing are moved here instead of being silently dropped. Omit to use defaults (managed DLQ, maxReceiveCount: 3). Set arn to reuse an existing queue.
        :param pulumi.Input[_builtins.bool] fifo: Creates a FIFO queue when true. FIFO queues guarantee message ordering and exactly-once processing but have lower throughput (~3,000 msg/s vs unlimited for standard). Use for financial transactions, inventory updates, or any workflow where ordering or deduplication matters. Default: false.
        """
        if consumer is not None:
            pulumi.set(__self__, "consumer", consumer)
        if dlq is not None:
            pulumi.set(__self__, "dlq", dlq)
        if fifo is not None:
            pulumi.set(__self__, "fifo", fifo)
        if transform is not None:
            pulumi.set(__self__, "transform", transform)

    @_builtins.property
    @pulumi.getter
    def consumer(self) -> Optional[pulumi.Input['QueueConsumerArgsArgs']]:
        """
        Wires a compute resource to consume messages from this queue. Creates the event source mapping (trigger) and grants the necessary IAM permissions automatically.
        """
        return pulumi.get(self, "consumer")

    @consumer.setter
    def consumer(self, value: Optional[pulumi.Input['QueueConsumerArgsArgs']]):
        pulumi.set(self, "consumer", value)

    @_builtins.property
    @pulumi.getter
    def dlq(self) -> Optional[pulumi.Input['QueueDlqArgsArgs']]:
        """
        Dead letter queue configuration. Always provisioned — messages that fail processing are moved here instead of being silently dropped. Omit to use defaults (managed DLQ, maxReceiveCount: 3). Set arn to reuse an existing queue.
        """
        return pulumi.get(self, "dlq")

    @dlq.setter
    def dlq(self, value: Optional[pulumi.Input['QueueDlqArgsArgs']]):
        pulumi.set(self, "dlq", value)

    @_builtins.property
    @pulumi.getter
    def fifo(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Creates a FIFO queue when true. FIFO queues guarantee message ordering and exactly-once processing but have lower throughput (~3,000 msg/s vs unlimited for standard). Use for financial transactions, inventory updates, or any workflow where ordering or deduplication matters. Default: false.
        """
        return pulumi.get(self, "fifo")

    @fifo.setter
    def fifo(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "fifo", value)

    @_builtins.property
    @pulumi.getter
    def transform(self) -> Optional[pulumi.Input['QueueTransformArgsArgs']]:
        return pulumi.get(self, "transform")

    @transform.setter
    def transform(self, value: Optional[pulumi.Input['QueueTransformArgsArgs']]):
        pulumi.set(self, "transform", value)


@pulumi.type_token("anvil:aws:Queue")
class Queue(pulumi.ComponentResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 consumer: Optional[pulumi.Input[Union['QueueConsumerArgsArgs', 'QueueConsumerArgsArgsDict']]] = None,
                 dlq: Optional[pulumi.Input[Union['QueueDlqArgsArgs', 'QueueDlqArgsArgsDict']]] = None,
                 fifo: Optional[pulumi.Input[_builtins.bool]] = None,
                 transform: Optional[pulumi.Input[Union['QueueTransformArgsArgs', 'QueueTransformArgsArgsDict']]] = None,
                 __props__=None):
        """
        An Anvil-managed SQS queue. A dead letter queue is always provisioned to prevent silent message loss. SSE-SQS encryption is enabled by default at no cost.


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Union['QueueConsumerArgsArgs', 'QueueConsumerArgsArgsDict']] consumer: Wires a compute resource to consume messages from this queue. Creates the event source mapping (trigger) and grants the necessary IAM permissions automatically.
        :param pulumi.Input[Union['QueueDlqArgsArgs', 'QueueDlqArgsArgsDict']] dlq: Dead letter queue configuration. Always provisioned — messages that fail processing are moved here instead of being silently dropped. Omit to use defaults (managed DLQ, maxReceiveCount: 3). Set arn to reuse an existing queue.
        :param pulumi.Input[_builtins.bool] fifo: Creates a FIFO queue when true. FIFO queues guarantee message ordering and exactly-once processing but have lower throughput (~3,000 msg/s vs unlimited for standard). Use for financial transactions, inventory updates, or any workflow where ordering or deduplication matters. Default: false.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[QueueArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        An Anvil-managed SQS queue. A dead letter queue is always provisioned to prevent silent message loss. SSE-SQS encryption is enabled by default at no cost.


        :param str resource_name: The name of the resource.
        :param QueueArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(QueueArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 consumer: Optional[pulumi.Input[Union['QueueConsumerArgsArgs', 'QueueConsumerArgsArgsDict']]] = None,
                 dlq: Optional[pulumi.Input[Union['QueueDlqArgsArgs', 'QueueDlqArgsArgsDict']]] = None,
                 fifo: Optional[pulumi.Input[_builtins.bool]] = None,
                 transform: Optional[pulumi.Input[Union['QueueTransformArgsArgs', 'QueueTransformArgsArgsDict']]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is not None:
            raise ValueError('ComponentResource classes do not support opts.id')
        else:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = QueueArgs.__new__(QueueArgs)

            __props__.__dict__["consumer"] = consumer
            __props__.__dict__["dlq"] = dlq
            __props__.__dict__["fifo"] = fifo
            __props__.__dict__["transform"] = transform
            __props__.__dict__["arn"] = None
            __props__.__dict__["dlq_arn"] = None
            __props__.__dict__["dlq_url"] = None
            __props__.__dict__["name"] = None
            __props__.__dict__["url"] = None
        super(Queue, __self__).__init__(
            'anvil:aws:Queue',
            resource_name,
            __props__,
            opts,
            remote=True)

    @_builtins.property
    @pulumi.getter
    def arn(self) -> pulumi.Output[_builtins.str]:
        """
        The ARN of the SQS queue.
        """
        return pulumi.get(self, "arn")

    @_builtins.property
    @pulumi.getter(name="dlqArn")
    def dlq_arn(self) -> pulumi.Output[_builtins.str]:
        """
        The ARN of the dead letter queue.
        """
        return pulumi.get(self, "dlq_arn")

    @_builtins.property
    @pulumi.getter(name="dlqUrl")
    def dlq_url(self) -> pulumi.Output[_builtins.str]:
        """
        The URL of the dead letter queue.
        """
        return pulumi.get(self, "dlq_url")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The physical name of the SQS queue.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def url(self) -> pulumi.Output[_builtins.str]:
        """
        The URL of the SQS queue. Use this to send and receive messages.
        """
        return pulumi.get(self, "url")

