# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = ['SvelteKitSiteArgs', 'SvelteKitSite']

@pulumi.input_type
class SvelteKitSiteArgs:
    def __init__(__self__, *,
                 path: pulumi.Input[_builtins.str],
                 domain: Optional[pulumi.Input[_builtins.str]] = None,
                 environment: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 transform: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a SvelteKitSite resource.

        :param pulumi.Input[_builtins.str] path: Path to the SvelteKit project directory, relative to the project root (where anvil.yaml lives). Not relative to the anvil.config file.
        :param pulumi.Input[_builtins.str] domain: Custom domain name for the site. When set, Anvil configures DNS and TLS certificates automatically.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] environment: Environment variables injected at both build time and runtime. Build time: available via $env/static and import.meta.env during static generation and prerendering. Runtime: set on the compute service (Lambda/Cloud Run) for SSR and API routes via $env/dynamic.
        :param pulumi.Input[_builtins.str] transform: Transform overrides for underlying AWS resources.
        """
        pulumi.set(__self__, "path", path)
        if domain is not None:
            pulumi.set(__self__, "domain", domain)
        if environment is not None:
            pulumi.set(__self__, "environment", environment)
        if transform is not None:
            pulumi.set(__self__, "transform", transform)

    @_builtins.property
    @pulumi.getter
    def path(self) -> pulumi.Input[_builtins.str]:
        """
        Path to the SvelteKit project directory, relative to the project root (where anvil.yaml lives). Not relative to the anvil.config file.
        """
        return pulumi.get(self, "path")

    @path.setter
    def path(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "path", value)

    @_builtins.property
    @pulumi.getter
    def domain(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Custom domain name for the site. When set, Anvil configures DNS and TLS certificates automatically.
        """
        return pulumi.get(self, "domain")

    @domain.setter
    def domain(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "domain", value)

    @_builtins.property
    @pulumi.getter
    def environment(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Environment variables injected at both build time and runtime. Build time: available via $env/static and import.meta.env during static generation and prerendering. Runtime: set on the compute service (Lambda/Cloud Run) for SSR and API routes via $env/dynamic.
        """
        return pulumi.get(self, "environment")

    @environment.setter
    def environment(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "environment", value)

    @_builtins.property
    @pulumi.getter
    def transform(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Transform overrides for underlying AWS resources.
        """
        return pulumi.get(self, "transform")

    @transform.setter
    def transform(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "transform", value)


@pulumi.type_token("anvil:aws:SvelteKitSite")
class SvelteKitSite(pulumi.ComponentResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 domain: Optional[pulumi.Input[_builtins.str]] = None,
                 environment: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 path: Optional[pulumi.Input[_builtins.str]] = None,
                 transform: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        SvelteKitSite is an Anvil-managed SvelteKit deployment on AWS. Static assets go to S3 behind CloudFront. Server code runs on Lambda.


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] domain: Custom domain name for the site. When set, Anvil configures DNS and TLS certificates automatically.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] environment: Environment variables injected at both build time and runtime. Build time: available via $env/static and import.meta.env during static generation and prerendering. Runtime: set on the compute service (Lambda/Cloud Run) for SSR and API routes via $env/dynamic.
        :param pulumi.Input[_builtins.str] path: Path to the SvelteKit project directory, relative to the project root (where anvil.yaml lives). Not relative to the anvil.config file.
        :param pulumi.Input[_builtins.str] transform: Transform overrides for underlying AWS resources.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: SvelteKitSiteArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        SvelteKitSite is an Anvil-managed SvelteKit deployment on AWS. Static assets go to S3 behind CloudFront. Server code runs on Lambda.


        :param str resource_name: The name of the resource.
        :param SvelteKitSiteArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(SvelteKitSiteArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 domain: Optional[pulumi.Input[_builtins.str]] = None,
                 environment: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 path: Optional[pulumi.Input[_builtins.str]] = None,
                 transform: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is not None:
            raise ValueError('ComponentResource classes do not support opts.id')
        else:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = SvelteKitSiteArgs.__new__(SvelteKitSiteArgs)

            __props__.__dict__["domain"] = domain
            __props__.__dict__["environment"] = environment
            if path is None and not opts.urn:
                raise TypeError("Missing required property 'path'")
            __props__.__dict__["path"] = path
            __props__.__dict__["transform"] = transform
            __props__.__dict__["bucket_name"] = None
            __props__.__dict__["cloud_front_distribution_id"] = None
            __props__.__dict__["dns_records"] = None
            __props__.__dict__["function_name"] = None
            __props__.__dict__["url"] = None
        super(SvelteKitSite, __self__).__init__(
            'anvil:aws:SvelteKitSite',
            resource_name,
            __props__,
            opts,
            remote=True)

    @_builtins.property
    @pulumi.getter(name="bucketName")
    def bucket_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The S3 bucket name storing static assets.
        """
        return pulumi.get(self, "bucket_name")

    @_builtins.property
    @pulumi.getter(name="cloudFrontDistributionId")
    def cloud_front_distribution_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The CloudFront distribution ID serving the site.
        """
        return pulumi.get(self, "cloud_front_distribution_id")

    @_builtins.property
    @pulumi.getter(name="dnsRecords")
    def dns_records(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        DNS records the user needs to create (if domain is set and not on Route53). Empty if no domain or if Route53 records were created automatically.
        """
        return pulumi.get(self, "dns_records")

    @_builtins.property
    @pulumi.getter(name="functionName")
    def function_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The Lambda function name running SSR.
        """
        return pulumi.get(self, "function_name")

    @_builtins.property
    @pulumi.getter
    def url(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The URL where the site is accessible.
        """
        return pulumi.get(self, "url")

