# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from ._enums import *
from ._inputs import *

__all__ = ['SvelteKitSiteArgs', 'SvelteKitSite']

@pulumi.input_type
class SvelteKitSiteArgs:
    def __init__(__self__, *,
                 domain: Optional[pulumi.Input[_builtins.str]] = None,
                 environment: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 origin_protection: Optional[pulumi.Input['SiteOriginProtectionArgs']] = None,
                 path: Optional[pulumi.Input[_builtins.str]] = None,
                 runtime_environment: Optional[pulumi.Input[_builtins.str]] = None,
                 transform: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a SvelteKitSite resource.

        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] environment: Environment vars available at BOTH build time and runtime. Values must be string literals since they're needed before the build runs.
        :param pulumi.Input['SiteOriginProtectionArgs'] origin_protection: OriginProtection enables WAF-based origin protection. When set, a WAF WebACL is created that blocks requests missing the x-origin-secret header. The secret value is output as originSecret. Requires domain to be set.
        :param pulumi.Input[_builtins.str] runtime_environment: Runtime-only environment vars set on the Lambda function. Supports Pulumi Output values (e.g. bucket.name, fn.arn). Only available at request time, NOT during build/prerendering.
        """
        if domain is not None:
            pulumi.set(__self__, "domain", domain)
        if environment is not None:
            pulumi.set(__self__, "environment", environment)
        if origin_protection is not None:
            pulumi.set(__self__, "origin_protection", origin_protection)
        if path is not None:
            pulumi.set(__self__, "path", path)
        if runtime_environment is not None:
            pulumi.set(__self__, "runtime_environment", runtime_environment)
        if transform is not None:
            pulumi.set(__self__, "transform", transform)

    @_builtins.property
    @pulumi.getter
    def domain(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "domain")

    @domain.setter
    def domain(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "domain", value)

    @_builtins.property
    @pulumi.getter
    def environment(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Environment vars available at BOTH build time and runtime. Values must be string literals since they're needed before the build runs.
        """
        return pulumi.get(self, "environment")

    @environment.setter
    def environment(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "environment", value)

    @_builtins.property
    @pulumi.getter(name="originProtection")
    def origin_protection(self) -> Optional[pulumi.Input['SiteOriginProtectionArgs']]:
        """
        OriginProtection enables WAF-based origin protection. When set, a WAF WebACL is created that blocks requests missing the x-origin-secret header. The secret value is output as originSecret. Requires domain to be set.
        """
        return pulumi.get(self, "origin_protection")

    @origin_protection.setter
    def origin_protection(self, value: Optional[pulumi.Input['SiteOriginProtectionArgs']]):
        pulumi.set(self, "origin_protection", value)

    @_builtins.property
    @pulumi.getter
    def path(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "path")

    @path.setter
    def path(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "path", value)

    @_builtins.property
    @pulumi.getter(name="runtimeEnvironment")
    def runtime_environment(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Runtime-only environment vars set on the Lambda function. Supports Pulumi Output values (e.g. bucket.name, fn.arn). Only available at request time, NOT during build/prerendering.
        """
        return pulumi.get(self, "runtime_environment")

    @runtime_environment.setter
    def runtime_environment(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "runtime_environment", value)

    @_builtins.property
    @pulumi.getter
    def transform(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "transform")

    @transform.setter
    def transform(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "transform", value)


@pulumi.type_token("anvil:aws:SvelteKitSite")
class SvelteKitSite(pulumi.ComponentResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 domain: Optional[pulumi.Input[_builtins.str]] = None,
                 environment: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 origin_protection: Optional[pulumi.Input[Union['SiteOriginProtectionArgs', 'SiteOriginProtectionArgsDict']]] = None,
                 path: Optional[pulumi.Input[_builtins.str]] = None,
                 runtime_environment: Optional[pulumi.Input[_builtins.str]] = None,
                 transform: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a SvelteKitSite resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] environment: Environment vars available at BOTH build time and runtime. Values must be string literals since they're needed before the build runs.
        :param pulumi.Input[Union['SiteOriginProtectionArgs', 'SiteOriginProtectionArgsDict']] origin_protection: OriginProtection enables WAF-based origin protection. When set, a WAF WebACL is created that blocks requests missing the x-origin-secret header. The secret value is output as originSecret. Requires domain to be set.
        :param pulumi.Input[_builtins.str] runtime_environment: Runtime-only environment vars set on the Lambda function. Supports Pulumi Output values (e.g. bucket.name, fn.arn). Only available at request time, NOT during build/prerendering.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[SvelteKitSiteArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a SvelteKitSite resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param SvelteKitSiteArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(SvelteKitSiteArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 domain: Optional[pulumi.Input[_builtins.str]] = None,
                 environment: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 origin_protection: Optional[pulumi.Input[Union['SiteOriginProtectionArgs', 'SiteOriginProtectionArgsDict']]] = None,
                 path: Optional[pulumi.Input[_builtins.str]] = None,
                 runtime_environment: Optional[pulumi.Input[_builtins.str]] = None,
                 transform: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is not None:
            raise ValueError('ComponentResource classes do not support opts.id')
        else:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = SvelteKitSiteArgs.__new__(SvelteKitSiteArgs)

            __props__.__dict__["domain"] = domain
            __props__.__dict__["environment"] = environment
            __props__.__dict__["origin_protection"] = origin_protection
            __props__.__dict__["path"] = path
            __props__.__dict__["runtime_environment"] = runtime_environment
            __props__.__dict__["transform"] = transform
            __props__.__dict__["bucket_name"] = None
            __props__.__dict__["cloud_front_distribution_id"] = None
            __props__.__dict__["dns_records"] = None
            __props__.__dict__["function_name"] = None
            __props__.__dict__["origin_secret"] = None
            __props__.__dict__["url"] = None
        super(SvelteKitSite, __self__).__init__(
            'anvil:aws:SvelteKitSite',
            resource_name,
            __props__,
            opts,
            remote=True)

    @_builtins.property
    @pulumi.getter(name="bucketName")
    def bucket_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "bucket_name")

    @_builtins.property
    @pulumi.getter(name="cloudFrontDistributionId")
    def cloud_front_distribution_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "cloud_front_distribution_id")

    @_builtins.property
    @pulumi.getter(name="dnsRecords")
    def dns_records(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "dns_records")

    @_builtins.property
    @pulumi.getter(name="functionName")
    def function_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "function_name")

    @_builtins.property
    @pulumi.getter(name="originSecret")
    def origin_secret(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        OriginSecret is the x-origin-secret header value to configure in Cloudflare Transform Rules. Only populated when originProtection is set.
        """
        return pulumi.get(self, "origin_secret")

    @_builtins.property
    @pulumi.getter
    def url(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "url")

