# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from ._enums import *
from ._inputs import *
from .. import _enums as enums

__all__ = ['VpcArgs', 'Vpc']

@pulumi.input_type
class VpcArgs:
    def __init__(__self__, *,
                 availability_zones: Optional[pulumi.Input[_builtins.int]] = None,
                 bastion: Optional[pulumi.Input['VpcBastionArgsArgs']] = None,
                 cidr: Optional[pulumi.Input[_builtins.str]] = None,
                 flow_logs: Optional[pulumi.Input['VpcFlowLogsArgsArgs']] = None,
                 nat: Optional[pulumi.Input['VpcNatArgsArgs']] = None):
        """
        The set of arguments for constructing a Vpc resource.

        :param pulumi.Input[_builtins.int] availability_zones: Number of Availability Zones to deploy subnets into. Valid values: 1, 2, 3. Defaults to 1. Inherits from App.defaults.availability — 'high' maps to 3, 'low' maps to 1.
        :param pulumi.Input['VpcBastionArgsArgs'] bastion: Optional SSM bastion host for private network access. No SSH, no port 22 — access via AWS SSM Session Manager only. Use to connect to RDS, ElastiCache, and other private resources locally.
        :param pulumi.Input[_builtins.str] cidr: The IPv4 CIDR block for the VPC. Default: '10.0.0.0/16'. Public subnets carved from offset 0 (/24 each), private subnets from offset 10 (/24 each).
        :param pulumi.Input['VpcFlowLogsArgsArgs'] flow_logs: Optional VPC Flow Log configuration. Opt-in only. Either or both destinations can be enabled simultaneously. CloudWatch for active debugging, S3 for long-term compliance retention.
        :param pulumi.Input['VpcNatArgsArgs'] nat: Optional NAT configuration for outbound internet access from private subnets. Omit for a fully private VPC.
        """
        if availability_zones is not None:
            pulumi.set(__self__, "availability_zones", availability_zones)
        if bastion is not None:
            pulumi.set(__self__, "bastion", bastion)
        if cidr is not None:
            pulumi.set(__self__, "cidr", cidr)
        if flow_logs is not None:
            pulumi.set(__self__, "flow_logs", flow_logs)
        if nat is not None:
            pulumi.set(__self__, "nat", nat)

    @_builtins.property
    @pulumi.getter(name="availabilityZones")
    def availability_zones(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Number of Availability Zones to deploy subnets into. Valid values: 1, 2, 3. Defaults to 1. Inherits from App.defaults.availability — 'high' maps to 3, 'low' maps to 1.
        """
        return pulumi.get(self, "availability_zones")

    @availability_zones.setter
    def availability_zones(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "availability_zones", value)

    @_builtins.property
    @pulumi.getter
    def bastion(self) -> Optional[pulumi.Input['VpcBastionArgsArgs']]:
        """
        Optional SSM bastion host for private network access. No SSH, no port 22 — access via AWS SSM Session Manager only. Use to connect to RDS, ElastiCache, and other private resources locally.
        """
        return pulumi.get(self, "bastion")

    @bastion.setter
    def bastion(self, value: Optional[pulumi.Input['VpcBastionArgsArgs']]):
        pulumi.set(self, "bastion", value)

    @_builtins.property
    @pulumi.getter
    def cidr(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The IPv4 CIDR block for the VPC. Default: '10.0.0.0/16'. Public subnets carved from offset 0 (/24 each), private subnets from offset 10 (/24 each).
        """
        return pulumi.get(self, "cidr")

    @cidr.setter
    def cidr(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "cidr", value)

    @_builtins.property
    @pulumi.getter(name="flowLogs")
    def flow_logs(self) -> Optional[pulumi.Input['VpcFlowLogsArgsArgs']]:
        """
        Optional VPC Flow Log configuration. Opt-in only. Either or both destinations can be enabled simultaneously. CloudWatch for active debugging, S3 for long-term compliance retention.
        """
        return pulumi.get(self, "flow_logs")

    @flow_logs.setter
    def flow_logs(self, value: Optional[pulumi.Input['VpcFlowLogsArgsArgs']]):
        pulumi.set(self, "flow_logs", value)

    @_builtins.property
    @pulumi.getter
    def nat(self) -> Optional[pulumi.Input['VpcNatArgsArgs']]:
        """
        Optional NAT configuration for outbound internet access from private subnets. Omit for a fully private VPC.
        """
        return pulumi.get(self, "nat")

    @nat.setter
    def nat(self, value: Optional[pulumi.Input['VpcNatArgsArgs']]):
        pulumi.set(self, "nat", value)


@pulumi.type_token("anvil:aws:Vpc")
class Vpc(pulumi.ComponentResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 availability_zones: Optional[pulumi.Input[_builtins.int]] = None,
                 bastion: Optional[pulumi.Input[Union['VpcBastionArgsArgs', 'VpcBastionArgsArgsDict']]] = None,
                 cidr: Optional[pulumi.Input[_builtins.str]] = None,
                 flow_logs: Optional[pulumi.Input[Union['VpcFlowLogsArgsArgs', 'VpcFlowLogsArgsArgsDict']]] = None,
                 nat: Optional[pulumi.Input[Union['VpcNatArgsArgs', 'VpcNatArgsArgsDict']]] = None,
                 __props__=None):
        """
        Create a Vpc resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.int] availability_zones: Number of Availability Zones to deploy subnets into. Valid values: 1, 2, 3. Defaults to 1. Inherits from App.defaults.availability — 'high' maps to 3, 'low' maps to 1.
        :param pulumi.Input[Union['VpcBastionArgsArgs', 'VpcBastionArgsArgsDict']] bastion: Optional SSM bastion host for private network access. No SSH, no port 22 — access via AWS SSM Session Manager only. Use to connect to RDS, ElastiCache, and other private resources locally.
        :param pulumi.Input[_builtins.str] cidr: The IPv4 CIDR block for the VPC. Default: '10.0.0.0/16'. Public subnets carved from offset 0 (/24 each), private subnets from offset 10 (/24 each).
        :param pulumi.Input[Union['VpcFlowLogsArgsArgs', 'VpcFlowLogsArgsArgsDict']] flow_logs: Optional VPC Flow Log configuration. Opt-in only. Either or both destinations can be enabled simultaneously. CloudWatch for active debugging, S3 for long-term compliance retention.
        :param pulumi.Input[Union['VpcNatArgsArgs', 'VpcNatArgsArgsDict']] nat: Optional NAT configuration for outbound internet access from private subnets. Omit for a fully private VPC.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[VpcArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Vpc resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param VpcArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(VpcArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 availability_zones: Optional[pulumi.Input[_builtins.int]] = None,
                 bastion: Optional[pulumi.Input[Union['VpcBastionArgsArgs', 'VpcBastionArgsArgsDict']]] = None,
                 cidr: Optional[pulumi.Input[_builtins.str]] = None,
                 flow_logs: Optional[pulumi.Input[Union['VpcFlowLogsArgsArgs', 'VpcFlowLogsArgsArgsDict']]] = None,
                 nat: Optional[pulumi.Input[Union['VpcNatArgsArgs', 'VpcNatArgsArgsDict']]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is not None:
            raise ValueError('ComponentResource classes do not support opts.id')
        else:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = VpcArgs.__new__(VpcArgs)

            __props__.__dict__["availability_zones"] = availability_zones
            __props__.__dict__["bastion"] = bastion
            __props__.__dict__["cidr"] = cidr
            __props__.__dict__["flow_logs"] = flow_logs
            __props__.__dict__["nat"] = nat
            __props__.__dict__["bastion_instance_id"] = None
            __props__.__dict__["bastion_security_group_id"] = None
            __props__.__dict__["default_security_group_id"] = None
            __props__.__dict__["private_subnet_ids"] = None
            __props__.__dict__["public_subnet_ids"] = None
            __props__.__dict__["vpc_id"] = None
        super(Vpc, __self__).__init__(
            'anvil:aws:Vpc',
            resource_name,
            __props__,
            opts,
            remote=True)

    @_builtins.property
    @pulumi.getter(name="availabilityZones")
    def availability_zones(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        The resolved Availability Zone names, e.g. ['ap-southeast-2a']. Consumed by RDS Multi-AZ, ECS spread, and other downstream components.
        """
        return pulumi.get(self, "availability_zones")

    @_builtins.property
    @pulumi.getter(name="bastionInstanceId")
    def bastion_instance_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The EC2 instance ID of the bastion host. Use with: aws ssm start-session --target <bastionInstanceId>. Only populated when bastion is enabled.
        """
        return pulumi.get(self, "bastion_instance_id")

    @_builtins.property
    @pulumi.getter(name="bastionSecurityGroupId")
    def bastion_security_group_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The security group ID of the bastion host. Use to grant the bastion access to private resources, e.g. db.grant(network.bastion, { access: 'readWrite' }). Only populated when bastion is enabled.
        """
        return pulumi.get(self, "bastion_security_group_id")

    @_builtins.property
    @pulumi.getter(name="defaultSecurityGroupId")
    def default_security_group_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the VPC default security group. All rules removed — not used by Anvil components.
        """
        return pulumi.get(self, "default_security_group_id")

    @_builtins.property
    @pulumi.getter(name="privateSubnetIds")
    def private_subnet_ids(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        The IDs of the private subnets, one per AZ. Used by Lambda, ECS tasks, EC2, and RDS.
        """
        return pulumi.get(self, "private_subnet_ids")

    @_builtins.property
    @pulumi.getter(name="publicSubnetIds")
    def public_subnet_ids(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        The IDs of the public subnets, one per AZ. Used by load balancers, NAT Gateways, and the bastion host.
        """
        return pulumi.get(self, "public_subnet_ids")

    @_builtins.property
    @pulumi.getter(name="vpcId")
    def vpc_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the VPC.
        """
        return pulumi.get(self, "vpc_id")

    @staticmethod
    def from_id(
        name: str,
        args: 'VpcLookupArgs',
        opts: Optional[pulumi.ResourceOptions] = None
    ) -> 'Vpc':
        """
        Imports an existing Vpc into Anvil without managing or modifying it.
        Returns an identical output shape to constructing a new Vpc.

        Flow logs, NAT, and bastion are not available on an imported VPC.

        If subnet IDs are omitted, Anvil auto-discovers them by inspecting
        route tables. Provide IDs explicitly if auto-discovery fails.
        """
        return Vpc(name, args, opts)  # type: ignore

