# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from ._enums import *
from ._inputs import *
import pulumi_aws

__all__ = ['WafArgs', 'Waf']

@pulumi.input_type
class WafArgs:
    def __init__(__self__, *,
                 block_countries: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 client_ip_header: Optional[pulumi.Input[_builtins.str]] = None,
                 ip_allow_list: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 ip_block_list: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 logging: Optional[pulumi.Input['WafLoggingArgsArgs']] = None,
                 managed_rules: Optional[pulumi.Input['WafManagedRulesArgsArgs']] = None,
                 mode: Optional[pulumi.Input['WafMode']] = None,
                 rate_limit: Optional[pulumi.Input['WafRateLimitArgsArgs']] = None,
                 rule_overrides: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 scope: Optional[pulumi.Input['WafScope']] = None,
                 transform: Optional[pulumi.Input['WafTransformArgsArgs']] = None):
        """
        The set of arguments for constructing a Waf resource.

        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] block_countries: Two-letter ISO 3166 country codes to block, e.g. ["KP"]. Follows mode.
        :param pulumi.Input[_builtins.str] client_ip_header: Header carrying the real visitor IP when the site sits behind a proxy, e.g. "CF-Connecting-IP" for Cloudflare. The rate limit, IP lists and country blocking then use the visitor's IP instead of the proxy's. AWS's ipReputation and anonymousIp rule groups can't read this header, so they default to off when it's set.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] ip_allow_list: IP addresses or CIDRs (IPv4 and IPv6) that are always allowed, skipping every other rule — e.g. office networks or uptime monitors.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] ip_block_list: IP addresses or CIDRs (IPv4 and IPv6) that are always blocked.
        :param pulumi.Input['WafLoggingArgsArgs'] logging: Logging to CloudWatch Logs. On by default: blocked and counted requests only, kept 30 days, with the authorization, cookie and x-origin-secret headers redacted.
        :param pulumi.Input['WafManagedRulesArgsArgs'] managed_rules: AWS managed rule groups. On by default: core, knownBadInputs, ipReputation, sqli. Off by default: anonymousIp, adminProtection.
        :param pulumi.Input['WafMode'] mode: What rules do when they match. "count" (default): log the match without blocking — use this to check for false positives on live traffic. "block": block matching requests. The IP allow and block lists always allow / block regardless of mode.
        :param pulumi.Input['WafRateLimitArgsArgs'] rate_limit: Per-client rate limit. On by default: 2000 requests per client per 5 minutes.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] rule_overrides: Override the action of individual AWS managed rules, keyed by exact AWS rule name: "count", "block" or "allow". Default: { SizeRestrictions_BODY: "count" } — that rule blocks any body over 8 KB, which breaks forms, JSON APIs and uploads. Set it to "block" to restore it.
        :param pulumi.Input['WafScope'] scope: What the WAF protects. "cloudfront" (default): sites and other CloudFront distributions; created in us-east-1 as AWS requires. "regional": regional resources such as Cognito user pools; created in the stack's region.
        """
        if block_countries is not None:
            pulumi.set(__self__, "block_countries", block_countries)
        if client_ip_header is not None:
            pulumi.set(__self__, "client_ip_header", client_ip_header)
        if ip_allow_list is not None:
            pulumi.set(__self__, "ip_allow_list", ip_allow_list)
        if ip_block_list is not None:
            pulumi.set(__self__, "ip_block_list", ip_block_list)
        if logging is not None:
            pulumi.set(__self__, "logging", logging)
        if managed_rules is not None:
            pulumi.set(__self__, "managed_rules", managed_rules)
        if mode is not None:
            pulumi.set(__self__, "mode", mode)
        if rate_limit is not None:
            pulumi.set(__self__, "rate_limit", rate_limit)
        if rule_overrides is not None:
            pulumi.set(__self__, "rule_overrides", rule_overrides)
        if scope is not None:
            pulumi.set(__self__, "scope", scope)
        if transform is not None:
            pulumi.set(__self__, "transform", transform)

    @_builtins.property
    @pulumi.getter(name="blockCountries")
    def block_countries(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Two-letter ISO 3166 country codes to block, e.g. ["KP"]. Follows mode.
        """
        return pulumi.get(self, "block_countries")

    @block_countries.setter
    def block_countries(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "block_countries", value)

    @_builtins.property
    @pulumi.getter(name="clientIpHeader")
    def client_ip_header(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Header carrying the real visitor IP when the site sits behind a proxy, e.g. "CF-Connecting-IP" for Cloudflare. The rate limit, IP lists and country blocking then use the visitor's IP instead of the proxy's. AWS's ipReputation and anonymousIp rule groups can't read this header, so they default to off when it's set.
        """
        return pulumi.get(self, "client_ip_header")

    @client_ip_header.setter
    def client_ip_header(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "client_ip_header", value)

    @_builtins.property
    @pulumi.getter(name="ipAllowList")
    def ip_allow_list(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        IP addresses or CIDRs (IPv4 and IPv6) that are always allowed, skipping every other rule — e.g. office networks or uptime monitors.
        """
        return pulumi.get(self, "ip_allow_list")

    @ip_allow_list.setter
    def ip_allow_list(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "ip_allow_list", value)

    @_builtins.property
    @pulumi.getter(name="ipBlockList")
    def ip_block_list(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        IP addresses or CIDRs (IPv4 and IPv6) that are always blocked.
        """
        return pulumi.get(self, "ip_block_list")

    @ip_block_list.setter
    def ip_block_list(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "ip_block_list", value)

    @_builtins.property
    @pulumi.getter
    def logging(self) -> Optional[pulumi.Input['WafLoggingArgsArgs']]:
        """
        Logging to CloudWatch Logs. On by default: blocked and counted requests only, kept 30 days, with the authorization, cookie and x-origin-secret headers redacted.
        """
        return pulumi.get(self, "logging")

    @logging.setter
    def logging(self, value: Optional[pulumi.Input['WafLoggingArgsArgs']]):
        pulumi.set(self, "logging", value)

    @_builtins.property
    @pulumi.getter(name="managedRules")
    def managed_rules(self) -> Optional[pulumi.Input['WafManagedRulesArgsArgs']]:
        """
        AWS managed rule groups. On by default: core, knownBadInputs, ipReputation, sqli. Off by default: anonymousIp, adminProtection.
        """
        return pulumi.get(self, "managed_rules")

    @managed_rules.setter
    def managed_rules(self, value: Optional[pulumi.Input['WafManagedRulesArgsArgs']]):
        pulumi.set(self, "managed_rules", value)

    @_builtins.property
    @pulumi.getter
    def mode(self) -> Optional[pulumi.Input['WafMode']]:
        """
        What rules do when they match. "count" (default): log the match without blocking — use this to check for false positives on live traffic. "block": block matching requests. The IP allow and block lists always allow / block regardless of mode.
        """
        return pulumi.get(self, "mode")

    @mode.setter
    def mode(self, value: Optional[pulumi.Input['WafMode']]):
        pulumi.set(self, "mode", value)

    @_builtins.property
    @pulumi.getter(name="rateLimit")
    def rate_limit(self) -> Optional[pulumi.Input['WafRateLimitArgsArgs']]:
        """
        Per-client rate limit. On by default: 2000 requests per client per 5 minutes.
        """
        return pulumi.get(self, "rate_limit")

    @rate_limit.setter
    def rate_limit(self, value: Optional[pulumi.Input['WafRateLimitArgsArgs']]):
        pulumi.set(self, "rate_limit", value)

    @_builtins.property
    @pulumi.getter(name="ruleOverrides")
    def rule_overrides(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Override the action of individual AWS managed rules, keyed by exact AWS rule name: "count", "block" or "allow". Default: { SizeRestrictions_BODY: "count" } — that rule blocks any body over 8 KB, which breaks forms, JSON APIs and uploads. Set it to "block" to restore it.
        """
        return pulumi.get(self, "rule_overrides")

    @rule_overrides.setter
    def rule_overrides(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "rule_overrides", value)

    @_builtins.property
    @pulumi.getter
    def scope(self) -> Optional[pulumi.Input['WafScope']]:
        """
        What the WAF protects. "cloudfront" (default): sites and other CloudFront distributions; created in us-east-1 as AWS requires. "regional": regional resources such as Cognito user pools; created in the stack's region.
        """
        return pulumi.get(self, "scope")

    @scope.setter
    def scope(self, value: Optional[pulumi.Input['WafScope']]):
        pulumi.set(self, "scope", value)

    @_builtins.property
    @pulumi.getter
    def transform(self) -> Optional[pulumi.Input['WafTransformArgsArgs']]:
        return pulumi.get(self, "transform")

    @transform.setter
    def transform(self, value: Optional[pulumi.Input['WafTransformArgsArgs']]):
        pulumi.set(self, "transform", value)


@pulumi.type_token("anvil:aws:Waf")
class Waf(pulumi.ComponentResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 block_countries: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 client_ip_header: Optional[pulumi.Input[_builtins.str]] = None,
                 ip_allow_list: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 ip_block_list: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 logging: Optional[pulumi.Input[Union['WafLoggingArgsArgs', 'WafLoggingArgsArgsDict']]] = None,
                 managed_rules: Optional[pulumi.Input[Union['WafManagedRulesArgsArgs', 'WafManagedRulesArgsArgsDict']]] = None,
                 mode: Optional[pulumi.Input['WafMode']] = None,
                 rate_limit: Optional[pulumi.Input[Union['WafRateLimitArgsArgs', 'WafRateLimitArgsArgsDict']]] = None,
                 rule_overrides: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 scope: Optional[pulumi.Input['WafScope']] = None,
                 transform: Optional[pulumi.Input[Union['WafTransformArgsArgs', 'WafTransformArgsArgsDict']]] = None,
                 __props__=None):
        """
        An Anvil-managed AWS WAF WebACL with researched defaults: a per-client rate limit (2000 requests / 5 min) and AWS managed rule groups for IP reputation, known bad inputs, the OWASP core rule set and SQL injection. Starts in count mode — matches are logged, not blocked — until mode is set to "block". Attach it to a site with waf: { arn } or to a Cognito user pool with waf: { arn }.


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] block_countries: Two-letter ISO 3166 country codes to block, e.g. ["KP"]. Follows mode.
        :param pulumi.Input[_builtins.str] client_ip_header: Header carrying the real visitor IP when the site sits behind a proxy, e.g. "CF-Connecting-IP" for Cloudflare. The rate limit, IP lists and country blocking then use the visitor's IP instead of the proxy's. AWS's ipReputation and anonymousIp rule groups can't read this header, so they default to off when it's set.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] ip_allow_list: IP addresses or CIDRs (IPv4 and IPv6) that are always allowed, skipping every other rule — e.g. office networks or uptime monitors.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] ip_block_list: IP addresses or CIDRs (IPv4 and IPv6) that are always blocked.
        :param pulumi.Input[Union['WafLoggingArgsArgs', 'WafLoggingArgsArgsDict']] logging: Logging to CloudWatch Logs. On by default: blocked and counted requests only, kept 30 days, with the authorization, cookie and x-origin-secret headers redacted.
        :param pulumi.Input[Union['WafManagedRulesArgsArgs', 'WafManagedRulesArgsArgsDict']] managed_rules: AWS managed rule groups. On by default: core, knownBadInputs, ipReputation, sqli. Off by default: anonymousIp, adminProtection.
        :param pulumi.Input['WafMode'] mode: What rules do when they match. "count" (default): log the match without blocking — use this to check for false positives on live traffic. "block": block matching requests. The IP allow and block lists always allow / block regardless of mode.
        :param pulumi.Input[Union['WafRateLimitArgsArgs', 'WafRateLimitArgsArgsDict']] rate_limit: Per-client rate limit. On by default: 2000 requests per client per 5 minutes.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] rule_overrides: Override the action of individual AWS managed rules, keyed by exact AWS rule name: "count", "block" or "allow". Default: { SizeRestrictions_BODY: "count" } — that rule blocks any body over 8 KB, which breaks forms, JSON APIs and uploads. Set it to "block" to restore it.
        :param pulumi.Input['WafScope'] scope: What the WAF protects. "cloudfront" (default): sites and other CloudFront distributions; created in us-east-1 as AWS requires. "regional": regional resources such as Cognito user pools; created in the stack's region.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[WafArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        An Anvil-managed AWS WAF WebACL with researched defaults: a per-client rate limit (2000 requests / 5 min) and AWS managed rule groups for IP reputation, known bad inputs, the OWASP core rule set and SQL injection. Starts in count mode — matches are logged, not blocked — until mode is set to "block". Attach it to a site with waf: { arn } or to a Cognito user pool with waf: { arn }.


        :param str resource_name: The name of the resource.
        :param WafArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(WafArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 block_countries: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 client_ip_header: Optional[pulumi.Input[_builtins.str]] = None,
                 ip_allow_list: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 ip_block_list: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 logging: Optional[pulumi.Input[Union['WafLoggingArgsArgs', 'WafLoggingArgsArgsDict']]] = None,
                 managed_rules: Optional[pulumi.Input[Union['WafManagedRulesArgsArgs', 'WafManagedRulesArgsArgsDict']]] = None,
                 mode: Optional[pulumi.Input['WafMode']] = None,
                 rate_limit: Optional[pulumi.Input[Union['WafRateLimitArgsArgs', 'WafRateLimitArgsArgsDict']]] = None,
                 rule_overrides: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 scope: Optional[pulumi.Input['WafScope']] = None,
                 transform: Optional[pulumi.Input[Union['WafTransformArgsArgs', 'WafTransformArgsArgsDict']]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is not None:
            raise ValueError('ComponentResource classes do not support opts.id')
        else:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = WafArgs.__new__(WafArgs)

            __props__.__dict__["block_countries"] = block_countries
            __props__.__dict__["client_ip_header"] = client_ip_header
            __props__.__dict__["ip_allow_list"] = ip_allow_list
            __props__.__dict__["ip_block_list"] = ip_block_list
            __props__.__dict__["logging"] = logging
            __props__.__dict__["managed_rules"] = managed_rules
            __props__.__dict__["mode"] = mode
            __props__.__dict__["rate_limit"] = rate_limit
            __props__.__dict__["rule_overrides"] = rule_overrides
            __props__.__dict__["scope"] = scope
            __props__.__dict__["transform"] = transform
            __props__.__dict__["arn"] = None
            __props__.__dict__["log_group_name"] = None
            __props__.__dict__["name"] = None
            __props__.__dict__["web_acl_id"] = None
        super(Waf, __self__).__init__(
            'anvil:aws:Waf',
            resource_name,
            __props__,
            opts,
            remote=True)

    @_builtins.property
    @pulumi.getter
    def arn(self) -> pulumi.Output[_builtins.str]:
        """
        The WebACL ARN. Pass it to a site's waf.arn (cloudfront scope) or a Cognito user pool's waf.arn (regional scope).
        """
        return pulumi.get(self, "arn")

    @_builtins.property
    @pulumi.getter(name="logGroupName")
    def log_group_name(self) -> pulumi.Output[_builtins.str]:
        """
        The CloudWatch log group receiving WAF logs. Empty when logging is off.
        """
        return pulumi.get(self, "log_group_name")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The physical WebACL name.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def scope(self) -> pulumi.Output[_builtins.str]:
        """
        "cloudfront" or "regional".
        """
        return pulumi.get(self, "scope")

    @_builtins.property
    @pulumi.getter(name="webAclId")
    def web_acl_id(self) -> pulumi.Output[_builtins.str]:
        """
        The WebACL ID.
        """
        return pulumi.get(self, "web_acl_id")

