package cmd

import (
	"context"
	"fmt"
	"os"
	"os/user"
	"path/filepath"

	"github.com/pulumi/pulumi/sdk/v3/go/auto"
)

// defaultBackendURL is the fallback when no anvil.yaml or env var is set.
const defaultBackendURL = "file://~/.anvil-state"

// defaultRegion is the AWS region used for all stacks.
const defaultRegion = "ap-southeast-2"

// resolveStage determines the effective stage.
// Priority: explicit flag → active stage from anvil.yaml → "dev"
func resolveStage(flagValue string) string {
	if flagValue != "" {
		return flagValue
	}

	config, err := loadAnvilConfig()
	if err == nil && config.Active != "" {
		return config.Active
	}

	u, err := user.Current()
	if err == nil && u.Username != "" {
		return u.Username
	}

	fmt.Printf("  %s No active stage set. Defaulting to \"dev\".\n", dim("hint:"))
	fmt.Printf("  %s Run `anvil stage set <n>` to set one.\n\n", dim("     "))

	return "dev"
}

// resolveBackendForStage determines the backend URL for a specific stage.
func resolveBackendForStage(stage string) string {
	if envURL := os.Getenv("ANVIL_BACKEND_URL"); envURL != "" {
		return envURL
	}

	config, err := loadAnvilConfig()
	if err != nil {
		return defaultBackendURL
	}

	sc, ok := config.Stages[stage]
	if !ok || sc.ID == "" {
		return defaultBackendURL
	}

	bucketName := resolveBucketName(stage, config.Project, sc.ID)
	return fmt.Sprintf("s3://%s", bucketName)
}

// resolveRegionForStage determines the AWS region for a specific stage.
func resolveRegionForStage(stage string) string {
	config, err := loadAnvilConfig()
	if err != nil {
		return defaultRegion
	}

	sc, ok := config.Stages[stage]
	if !ok || sc.Region == "" {
		return defaultRegion
	}

	return sc.Region
}

// resolveProjectName reads the project name from anvil.yaml.
// Falls back to the project root directory name if unavailable.
func resolveProjectName(projectRoot string) string {
	config, err := loadAnvilConfig()
	if err == nil && config.Project != "" {
		return config.Project
	}
	return filepath.Base(projectRoot)
}

// writeProjectFile writes a Pulumi.yaml to .anvil/ inside the project root.
// The user never creates or sees this file — Anvil manages it internally.
// The "main" field points back up to the entry point in the project root
// since Pulumi resolves it relative to the Pulumi.yaml location.
func writeProjectFile(projectRoot string, projectName string, rt *runtime) (string, error) {
	anvilDir := filepath.Join(projectRoot, ".anvil")
	if err := os.MkdirAll(anvilDir, 0755); err != nil {
		return "", fmt.Errorf("failed to create .anvil directory: %w", err)
	}

	// main is relative to .anvil/ — point back up to project root
	main := filepath.Join("..", rt.EntryFile)

	content := "# Auto-generated by Anvil — do not edit\n"
	content += fmt.Sprintf("name: %s\n", projectName)

	switch rt.Name {
	case "nodejs":
		content += "runtime:\n  name: nodejs\n  options:\n    typescript: true\n"
	case "python":
		content += "runtime: python\n"
	case "go":
		content += "runtime: go\n"
	default:
		return "", fmt.Errorf("unsupported runtime: %s", rt.Name)
	}

	content += fmt.Sprintf("main: %s\n", main)

	err := os.WriteFile(filepath.Join(anvilDir, "Pulumi.yaml"), []byte(content), 0644)
	if err != nil {
		return "", err
	}

	// Write .gitignore inside .anvil/ so the whole directory is ignored
	gitignore := filepath.Join(anvilDir, ".gitignore")
	if _, err := os.Stat(gitignore); os.IsNotExist(err) {
		os.WriteFile(gitignore, []byte("# Anvil internal files — do not commit\n*\n"), 0644)
	}

	return anvilDir, nil
}

// ensureBootstrapped checks if the given stage is bootstrapped. If not, runs bootstrap automatically.
func ensureBootstrapped(_ context.Context, stage string) error {
	config, err := loadAnvilConfig()
	if err == nil {
		if _, ok := config.Stages[stage]; ok {
			return nil
		}
	}

	fmt.Println("  No state backend found for stage \"" + stage + "\". Setting up...\n")

	bootstrapStage = stage
	bootstrapRegion = ""

	env, err := promptEnvironment()
	if err != nil {
		return fmt.Errorf("auto-bootstrap failed: %w", err)
	}
	bootstrapEnvironment = env

	err = runBootstrap(nil, nil)
	if err != nil {
		return fmt.Errorf("auto-bootstrap failed: %w", err)
	}

	return nil
}

// loadStack creates or selects a stack using the Automation API.
func loadStack(ctx context.Context, stage string) (auto.Stack, error) {
	// Detect project root and runtime
	projectRoot, err := findProjectRoot()
	if err != nil {
		return auto.Stack{}, err
	}

	rt, err := detectRuntime(projectRoot)
	if err != nil {
		return auto.Stack{}, err
	}

	projectName := resolveProjectName(projectRoot)

	// Write Pulumi.yaml to .anvil/ before anything else.
	workDir, err := writeProjectFile(projectRoot, projectName, rt)
	if err != nil {
		return auto.Stack{}, err
	}

	// Bootstrap after project file exists so the project name can be resolved.
	if err := ensureBootstrapped(ctx, stage); err != nil {
		return auto.Stack{}, err
	}

	backendURL := resolveBackendForStage(stage)
	region := resolveRegionForStage(stage)

	s, err := auto.UpsertStackLocalSource(ctx, stage, workDir,
		auto.EnvVars(map[string]string{
			"PULUMI_BACKEND_URL":       backendURL,
			"PULUMI_CONFIG_PASSPHRASE": "",
		}),
	)
	if err != nil {
		return auto.Stack{}, fmt.Errorf("%s", mapError(err.Error()))
	}

	if err := s.SetConfig(ctx, "aws:region", auto.ConfigValue{Value: region}); err != nil {
		return auto.Stack{}, fmt.Errorf("failed to set aws:region: %w", err)
	}
	if err := s.SetConfig(ctx, "anvil:stage", auto.ConfigValue{Value: stage}); err != nil {
		return auto.Stack{}, fmt.Errorf("failed to set anvil:stage: %w", err)
	}

	env := resolveEnvironmentForStage(stage)
	if err := s.SetConfig(ctx, "anvil:environment", auto.ConfigValue{Value: env}); err != nil {
		return auto.Stack{}, fmt.Errorf("failed to set anvil:environment: %w", err)
	}

	return s, nil
}

// loadStackNoBootstrap loads a stack without auto-bootstrapping.
// Used by destroy — it shouldn't create infrastructure to tear it down.
func loadStackNoBootstrap(ctx context.Context, stage string) (auto.Stack, error) {
	// Detect project root and runtime
	projectRoot, err := findProjectRoot()
	if err != nil {
		return auto.Stack{}, err
	}

	rt, err := detectRuntime(projectRoot)
	if err != nil {
		return auto.Stack{}, err
	}

	projectName := resolveProjectName(projectRoot)

	// Write Pulumi.yaml to .anvil/
	workDir, err := writeProjectFile(projectRoot, projectName, rt)
	if err != nil {
		return auto.Stack{}, err
	}

	backendURL := resolveBackendForStage(stage)
	if backendURL == defaultBackendURL {
		return auto.Stack{}, fmt.Errorf("Stage \"%s\" has not been bootstrapped.\n  Nothing to destroy.", stage)
	}

	region := resolveRegionForStage(stage)

	s, err := auto.UpsertStackLocalSource(ctx, stage, workDir,
		auto.EnvVars(map[string]string{
			"PULUMI_BACKEND_URL":       backendURL,
			"PULUMI_CONFIG_PASSPHRASE": "",
		}),
	)
	if err != nil {
		return auto.Stack{}, fmt.Errorf("%s", mapError(err.Error()))
	}

	if err := s.SetConfig(ctx, "aws:region", auto.ConfigValue{Value: region}); err != nil {
		return auto.Stack{}, fmt.Errorf("failed to set aws:region: %w", err)
	}
	if err := s.SetConfig(ctx, "anvil:stage", auto.ConfigValue{Value: stage}); err != nil {
		return auto.Stack{}, fmt.Errorf("failed to set anvil:stage: %w", err)
	}

	env := resolveEnvironmentForStage(stage)
	if err := s.SetConfig(ctx, "anvil:environment", auto.ConfigValue{Value: env}); err != nil {
		return auto.Stack{}, fmt.Errorf("failed to set anvil:environment: %w", err)
	}

	return s, nil
}

// resolveEnvironmentForStage reads the environment from anvil.yaml for the given stage.
func resolveEnvironmentForStage(stage string) string {
	config, err := loadAnvilConfig()
	if err != nil {
		return "nonprod"
	}

	sc, ok := config.Stages[stage]
	if !ok || sc.Environment == "" {
		return "nonprod"
	}

	return sc.Environment
}
