# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from ._enums import *
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import anvil_cloud.aws as __aws
    aws = __aws
    import anvil_cloud.gcp as __gcp
    gcp = __gcp
else:
    from .stack import wrap_namespace as _wrap_namespace
    # Wrap the component namespaces so constructing any component
    # auto-registers it into the active Stack under its logical name,
    # powering ctx.ref(...) forward references. See stack.py.
    aws = _wrap_namespace(_utilities.lazy_import('anvil_cloud.aws'))
    gcp = _wrap_namespace(_utilities.lazy_import('anvil_cloud.gcp'))

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "anvil",
  "mod": "aws",
  "fqn": "anvil_cloud.aws",
  "classes": {
   "anvil:aws:Bucket": "Bucket",
   "anvil:aws:CognitoAuth": "CognitoAuth",
   "anvil:aws:CognitoUserPool": "CognitoUserPool",
   "anvil:aws:DSQL": "DSQL",
   "anvil:aws:DSQLConnect": "DSQLConnect",
   "anvil:aws:DynamoDB": "DynamoDB",
   "anvil:aws:EventBus": "EventBus",
   "anvil:aws:HttpApi": "HttpApi",
   "anvil:aws:Lambda": "Lambda",
   "anvil:aws:OAuthAuthorizer": "OAuthAuthorizer",
   "anvil:aws:Queue": "Queue",
   "anvil:aws:SvelteKitSite": "SvelteKitSite",
   "anvil:aws:Vpc": "Vpc",
   "anvil:aws:VpcEndpoint": "VpcEndpoint"
  }
 },
 {
  "pkg": "anvil",
  "mod": "gcp",
  "fqn": "anvil_cloud.gcp",
  "classes": {
   "anvil:gcp:Function": "Function",
   "anvil:gcp:StorageBucket": "StorageBucket"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "anvil",
  "token": "pulumi:providers:anvil",
  "fqn": "anvil_cloud",
  "class": "Provider"
 }
]
"""
)

# Hand-written overlay exports (run, App, Block, types, grants, export)
from ._extras import *  # noqa: F401,F403
