# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from ._enums import *
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import anvil_cloud.aws as __aws
    aws = __aws
    import anvil_cloud.gcp as __gcp
    gcp = __gcp
else:
    aws = _utilities.lazy_import('anvil_cloud.aws')
    gcp = _utilities.lazy_import('anvil_cloud.gcp')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "anvil",
  "mod": "aws",
  "fqn": "anvil_cloud.aws",
  "classes": {
   "anvil:aws:Bucket": "Bucket",
   "anvil:aws:CognitoAuth": "CognitoAuth",
   "anvil:aws:EventBus": "EventBus",
   "anvil:aws:HttpApi": "HttpApi",
   "anvil:aws:Lambda": "Lambda",
   "anvil:aws:OAuthAuthorizer": "OAuthAuthorizer",
   "anvil:aws:Queue": "Queue",
   "anvil:aws:SvelteKitSite": "SvelteKitSite",
   "anvil:aws:Vpc": "Vpc",
   "anvil:aws:VpcEndpoint": "VpcEndpoint"
  }
 },
 {
  "pkg": "anvil",
  "mod": "gcp",
  "fqn": "anvil_cloud.gcp",
  "classes": {
   "anvil:gcp:Function": "Function",
   "anvil:gcp:StorageBucket": "StorageBucket"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "anvil",
  "token": "pulumi:providers:anvil",
  "fqn": "anvil_cloud",
  "class": "Provider"
 }
]
"""
)

# Typed entry point
from .app import run

# Hand-written App class
from .app import App, Context

# Hand-written Block class
from .block import Block

# Config classes
from .types import AppConfig, DefaultsConfig, AwsProviderConfig, GcpProviderConfig, AssumeRoleConfig

# Re-export core Pulumi functions so users never need to import pulumi directly.
from pulumi import export

# Grant helpers
from .grants import GrantTarget, GrantOptions, create_grant, build_resource_arns
