// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package gcp

import (
	"context"
	"reflect"

	"errors"
	"github.com/DamienPace15/anvil/sdk/go/anvil/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// SvelteKitSite is an Anvil-managed SvelteKit deployment on GCP. Static assets go to Cloud Storage behind Cloud CDN. Server code runs on Cloud Run.
type SvelteKitSite struct {
	pulumi.ResourceState

	// The Cloud Storage bucket name storing static assets.
	BucketName pulumi.StringPtrOutput `pulumi:"bucketName"`
	// The Cloud Run service URL.
	CloudRunUrl pulumi.StringPtrOutput `pulumi:"cloudRunUrl"`
	// The URL where the site is accessible.
	Url pulumi.StringPtrOutput `pulumi:"url"`
}

// NewSvelteKitSite registers a new resource with the given unique name, arguments, and options.
func NewSvelteKitSite(ctx *pulumi.Context,
	name string, args *SvelteKitSiteArgs, opts ...pulumi.ResourceOption) (*SvelteKitSite, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Path == nil {
		return nil, errors.New("invalid value for required argument 'Path'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource SvelteKitSite
	err := ctx.RegisterRemoteComponentResource("anvil:gcp:SvelteKitSite", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type svelteKitSiteArgs struct {
	// Custom domain name for the site. When set, Anvil configures DNS and TLS certificates automatically.
	Domain *string `pulumi:"domain"`
	// Environment variables injected at both build time and runtime. Build time: available via $env/static and import.meta.env during static generation and prerendering. Runtime: set on the compute service (Lambda/Cloud Run) for SSR and API routes via $env/dynamic.
	Environment map[string]string `pulumi:"environment"`
	// Minimum number of Cloud Run instances to keep warm. Set to 1 or higher to eliminate cold starts. Defaults to 0.
	MinInstances *int `pulumi:"minInstances"`
	// Path to the SvelteKit project directory, relative to the project root (where anvil.yaml lives). Not relative to the anvil.config file.
	Path string `pulumi:"path"`
}

// The set of arguments for constructing a SvelteKitSite resource.
type SvelteKitSiteArgs struct {
	// Custom domain name for the site. When set, Anvil configures DNS and TLS certificates automatically.
	Domain pulumi.StringPtrInput
	// Environment variables injected at both build time and runtime. Build time: available via $env/static and import.meta.env during static generation and prerendering. Runtime: set on the compute service (Lambda/Cloud Run) for SSR and API routes via $env/dynamic.
	Environment pulumi.StringMapInput
	// Minimum number of Cloud Run instances to keep warm. Set to 1 or higher to eliminate cold starts. Defaults to 0.
	MinInstances pulumi.IntPtrInput
	// Path to the SvelteKit project directory, relative to the project root (where anvil.yaml lives). Not relative to the anvil.config file.
	Path pulumi.StringInput
}

func (SvelteKitSiteArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*svelteKitSiteArgs)(nil)).Elem()
}

type SvelteKitSiteInput interface {
	pulumi.Input

	ToSvelteKitSiteOutput() SvelteKitSiteOutput
	ToSvelteKitSiteOutputWithContext(ctx context.Context) SvelteKitSiteOutput
}

func (*SvelteKitSite) ElementType() reflect.Type {
	return reflect.TypeOf((**SvelteKitSite)(nil)).Elem()
}

func (i *SvelteKitSite) ToSvelteKitSiteOutput() SvelteKitSiteOutput {
	return i.ToSvelteKitSiteOutputWithContext(context.Background())
}

func (i *SvelteKitSite) ToSvelteKitSiteOutputWithContext(ctx context.Context) SvelteKitSiteOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SvelteKitSiteOutput)
}

// SvelteKitSiteArrayInput is an input type that accepts SvelteKitSiteArray and SvelteKitSiteArrayOutput values.
// You can construct a concrete instance of `SvelteKitSiteArrayInput` via:
//
//	SvelteKitSiteArray{ SvelteKitSiteArgs{...} }
type SvelteKitSiteArrayInput interface {
	pulumi.Input

	ToSvelteKitSiteArrayOutput() SvelteKitSiteArrayOutput
	ToSvelteKitSiteArrayOutputWithContext(context.Context) SvelteKitSiteArrayOutput
}

type SvelteKitSiteArray []SvelteKitSiteInput

func (SvelteKitSiteArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SvelteKitSite)(nil)).Elem()
}

func (i SvelteKitSiteArray) ToSvelteKitSiteArrayOutput() SvelteKitSiteArrayOutput {
	return i.ToSvelteKitSiteArrayOutputWithContext(context.Background())
}

func (i SvelteKitSiteArray) ToSvelteKitSiteArrayOutputWithContext(ctx context.Context) SvelteKitSiteArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SvelteKitSiteArrayOutput)
}

// SvelteKitSiteMapInput is an input type that accepts SvelteKitSiteMap and SvelteKitSiteMapOutput values.
// You can construct a concrete instance of `SvelteKitSiteMapInput` via:
//
//	SvelteKitSiteMap{ "key": SvelteKitSiteArgs{...} }
type SvelteKitSiteMapInput interface {
	pulumi.Input

	ToSvelteKitSiteMapOutput() SvelteKitSiteMapOutput
	ToSvelteKitSiteMapOutputWithContext(context.Context) SvelteKitSiteMapOutput
}

type SvelteKitSiteMap map[string]SvelteKitSiteInput

func (SvelteKitSiteMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SvelteKitSite)(nil)).Elem()
}

func (i SvelteKitSiteMap) ToSvelteKitSiteMapOutput() SvelteKitSiteMapOutput {
	return i.ToSvelteKitSiteMapOutputWithContext(context.Background())
}

func (i SvelteKitSiteMap) ToSvelteKitSiteMapOutputWithContext(ctx context.Context) SvelteKitSiteMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SvelteKitSiteMapOutput)
}

type SvelteKitSiteOutput struct{ *pulumi.OutputState }

func (SvelteKitSiteOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SvelteKitSite)(nil)).Elem()
}

func (o SvelteKitSiteOutput) ToSvelteKitSiteOutput() SvelteKitSiteOutput {
	return o
}

func (o SvelteKitSiteOutput) ToSvelteKitSiteOutputWithContext(ctx context.Context) SvelteKitSiteOutput {
	return o
}

// The Cloud Storage bucket name storing static assets.
func (o SvelteKitSiteOutput) BucketName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SvelteKitSite) pulumi.StringPtrOutput { return v.BucketName }).(pulumi.StringPtrOutput)
}

// The Cloud Run service URL.
func (o SvelteKitSiteOutput) CloudRunUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SvelteKitSite) pulumi.StringPtrOutput { return v.CloudRunUrl }).(pulumi.StringPtrOutput)
}

// The URL where the site is accessible.
func (o SvelteKitSiteOutput) Url() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SvelteKitSite) pulumi.StringPtrOutput { return v.Url }).(pulumi.StringPtrOutput)
}

type SvelteKitSiteArrayOutput struct{ *pulumi.OutputState }

func (SvelteKitSiteArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SvelteKitSite)(nil)).Elem()
}

func (o SvelteKitSiteArrayOutput) ToSvelteKitSiteArrayOutput() SvelteKitSiteArrayOutput {
	return o
}

func (o SvelteKitSiteArrayOutput) ToSvelteKitSiteArrayOutputWithContext(ctx context.Context) SvelteKitSiteArrayOutput {
	return o
}

func (o SvelteKitSiteArrayOutput) Index(i pulumi.IntInput) SvelteKitSiteOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *SvelteKitSite {
		return vs[0].([]*SvelteKitSite)[vs[1].(int)]
	}).(SvelteKitSiteOutput)
}

type SvelteKitSiteMapOutput struct{ *pulumi.OutputState }

func (SvelteKitSiteMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SvelteKitSite)(nil)).Elem()
}

func (o SvelteKitSiteMapOutput) ToSvelteKitSiteMapOutput() SvelteKitSiteMapOutput {
	return o
}

func (o SvelteKitSiteMapOutput) ToSvelteKitSiteMapOutputWithContext(ctx context.Context) SvelteKitSiteMapOutput {
	return o
}

func (o SvelteKitSiteMapOutput) MapIndex(k pulumi.StringInput) SvelteKitSiteOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *SvelteKitSite {
		return vs[0].(map[string]*SvelteKitSite)[vs[1].(string)]
	}).(SvelteKitSiteOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SvelteKitSiteInput)(nil)).Elem(), &SvelteKitSite{})
	pulumi.RegisterInputType(reflect.TypeOf((*SvelteKitSiteArrayInput)(nil)).Elem(), SvelteKitSiteArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SvelteKitSiteMapInput)(nil)).Elem(), SvelteKitSiteMap{})
	pulumi.RegisterOutputType(SvelteKitSiteOutput{})
	pulumi.RegisterOutputType(SvelteKitSiteArrayOutput{})
	pulumi.RegisterOutputType(SvelteKitSiteMapOutput{})
}
