// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

import * as pulumiAws from "@pulumi/aws";

export class Bucket extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'anvil:aws:Bucket';

    /**
     * Returns true if the given object is an instance of Bucket.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Bucket {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Bucket.__pulumiType;
    }

    /**
     * The ARN of the S3 bucket.
     */
    declare public /*out*/ readonly arn: pulumi.Output<string>;
    /**
     * The name of the S3 bucket.
     */
    declare public /*out*/ readonly bucketName: pulumi.Output<string>;

    /**
     * Create a Bucket resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: BucketArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["encryption"] = args?.encryption;
            resourceInputs["logging"] = args?.logging;
            resourceInputs["retention"] = args?.retention;
            resourceInputs["storageTransition"] = args?.storageTransition;
            resourceInputs["transform"] = args?.transform;
            resourceInputs["versionRetention"] = args?.versionRetention;
            resourceInputs["versioning"] = args?.versioning;
            resourceInputs["arn"] = undefined /*out*/;
            resourceInputs["bucketName"] = undefined /*out*/;
        } else {
            resourceInputs["arn"] = undefined /*out*/;
            resourceInputs["bucketName"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Bucket.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a Bucket resource.
 */
export interface BucketArgs {
    /**
     * Upgrade at-rest encryption to SSE-KMS. Set to "kms" to enable. SSE-S3 (AES256) is always on by default at no cost. SSE-KMS incurs KMS API call cost and is required by HIPAA, PCI-DSS, FedRAMP, and IRAP.
     */
    encryption?: pulumi.Input<string>;
    /**
     * Enable S3 server access logging to the centralised logging bucket created during `anvil bootstrap`. Required by most compliance frameworks for audit trails. Incurs storage cost. Default: false.
     */
    logging?: pulumi.Input<boolean>;
    /**
     * Enable Object Lock with a retention period in days (COMPLIANCE mode). Objects cannot be deleted or overwritten until the period expires. Required by PCI-DSS (365), FedRAMP (1095), HIPAA (2190). Must be set at bucket creation — changing requires bucket replacement. Default: 0 (disabled).
     */
    retention?: pulumi.Input<number>;
    /**
     * When to move objects to cheaper storage classes. Omit to use Intelligent-Tiering (recommended default). Only applies when no custom lifecycle is provided via transform.
     */
    storageTransition?: pulumi.Input<string>;
    transform?: pulumi.Input<inputs.aws.BucketTransformArgsArgs>;
    /**
     * How long non-current object versions are kept before automatic expiry. Strongly recommended when versioning is enabled to prevent unbounded storage growth. Default: keep forever.
     */
    versionRetention?: pulumi.Input<string>;
    /**
     * Enable versioning in non-production stages. Versioning is always enabled in production. Incurs additional storage cost per version. Default: false.
     */
    versioning?: pulumi.Input<boolean>;
}
