// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * An Anvil-managed JWT authorizer backed by a Cognito user pool. Derives the issuer URL automatically from the user pool ID — no manual Cognito endpoint construction required. Creates a native API Gateway JWT authorizer; verification is handled entirely by API Gateway with no Lambda or custom code. Pass authorizerId to HttpApi defaultAuthorizerId to protect your API routes.
 */
export class CognitoAuth extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'anvil:aws:CognitoAuth';

    /**
     * Returns true if the given object is an instance of CognitoAuth.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CognitoAuth {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CognitoAuth.__pulumiType;
    }

    /**
     * The API Gateway authorizer ID. Pass this to HttpApi defaultAuthorizerId to protect your API routes.
     */
    declare public /*out*/ readonly authorizerId: pulumi.Output<string>;

    /**
     * Create a CognitoAuth resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CognitoAuthArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.audience === undefined && !opts.urn) {
                throw new Error("Missing required property 'audience'");
            }
            if (args?.userPoolId === undefined && !opts.urn) {
                throw new Error("Missing required property 'userPoolId'");
            }
            resourceInputs["audience"] = args?.audience;
            resourceInputs["userPoolId"] = args?.userPoolId;
            resourceInputs["authorizerId"] = undefined /*out*/;
        } else {
            resourceInputs["authorizerId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CognitoAuth.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a CognitoAuth resource.
 */
export interface CognitoAuthArgs {
    /**
     * The Cognito app client IDs allowed to access this API. API Gateway rejects tokens whose 'aud' claim does not match one of these values. Pass your Cognito app client ID(s) here.
     */
    audience: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The Cognito user pool ID. Pass pool.userPoolId directly. Accepts Output<string>. Anvil derives the issuer URL automatically: https://cognito-idp.{region}.amazonaws.com/{userPoolId}.
     */
    userPoolId: any;
}
