// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Internal: created by App when `compliance` is set. Schedules this app's Prowler compliance scans on the shared Anvil scanner. Do not construct directly — set `compliance` on your App instead.
 */
export class ComplianceScanner extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'anvil:aws:ComplianceScanner';

    /**
     * Returns true if the given object is an instance of ComplianceScanner.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ComplianceScanner {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ComplianceScanner.__pulumiType;
    }

    /**
     * The EventBridge Scheduler expression. Empty when schedule is none.
     */
    declare public /*out*/ readonly scheduleExpression: pulumi.Output<string>;
    /**
     * The schedule's name in the anvil-compliance schedule group. Empty when schedule is none.
     */
    declare public /*out*/ readonly scheduleName: pulumi.Output<string>;

    /**
     * Create a ComplianceScanner resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ComplianceScannerArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.frameworks === undefined && !opts.urn) {
                throw new Error("Missing required property 'frameworks'");
            }
            resourceInputs["cron"] = args?.cron;
            resourceInputs["frameworks"] = args?.frameworks;
            resourceInputs["regions"] = args?.regions;
            resourceInputs["retention"] = args?.retention;
            resourceInputs["scanOnDeploy"] = args?.scanOnDeploy;
            resourceInputs["schedule"] = args?.schedule;
            resourceInputs["timezone"] = args?.timezone;
            resourceInputs["scheduleExpression"] = undefined /*out*/;
            resourceInputs["scheduleName"] = undefined /*out*/;
        } else {
            resourceInputs["scheduleExpression"] = undefined /*out*/;
            resourceInputs["scheduleName"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ComplianceScanner.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a ComplianceScanner resource.
 */
export interface ComplianceScannerArgs {
    /**
     * Six AWS cron fields (minutes hours day-of-month month day-of-week year), used when schedule is cron. At most once an hour.
     */
    cron?: pulumi.Input<string>;
    /**
     * Frameworks to scan against: friendly names (soc2, iso27001, cis, nist-800-53, nist-800-171, nist-csf, pci, hipaa, fsbp, gdpr, nis2, dora, fedramp-low, fedramp-moderate, cmmc, essential-eight, well-architected, c5, csa-ccm) or any raw Prowler AWS compliance ID.
     */
    frameworks: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Regions the app deploys to, in addition to the provider's region. us-east-1 is always scanned for global services.
     */
    regions?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * How long scan results are kept: 30d, 90d, 180d, 1y (default), 2y, 7y.
     */
    retention?: pulumi.Input<string>;
    /**
     * Start a scan after each successful deploy. Default: false.
     */
    scanOnDeploy?: pulumi.Input<boolean>;
    /**
     * When to scan: daily (default), weekly, none, or cron (with `cron`). Presets run at a fixed time derived from the project and stage, so apps in one account don't all scan at once.
     */
    schedule?: pulumi.Input<string>;
    /**
     * IANA time zone for the schedule, e.g. Australia/Sydney. Default: UTC.
     */
    timezone?: pulumi.Input<string>;
}
