// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

import * as pulumiAws from "@pulumi/aws";
import * as grants from "../grants";
import * as aws from "@pulumi/aws";
import { DSQLConnect } from "./dsqlconnect";

/**
 * Serverless distributed PostgreSQL-compatible database. Secure-by-default Aurora DSQL cluster with optional multi-region active-active replication, IAM authentication, deploy-time role bootstrapping, and AWS Backup integration. No VPC required — connect directly via IAM auth tokens.
 */
export class DSQL extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'anvil:aws:DSQL';

    /** @internal Logical resource name for grant policy naming. */
    private __name: string;

    /**
     * Returns true if the given object is an instance of DSQL.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DSQL {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DSQL.__pulumiType;
    }

    /**
     * Map of region to cluster ARN. Single-region: one entry. Multi-region: one entry per region. e.g. { "us-east-1": "arn:aws:dsql:us-east-1:..." }.
     */
    declare public /*out*/ readonly clusterArns: pulumi.Output<{[key: string]: string}>;
    /**
     * Map of region to cluster endpoint. Single-region: one entry keyed by the provider region. Multi-region: one entry per region. e.g. { "us-east-1": "abc123.dsql.us-east-1.on.aws" }. Pass the relevant endpoint to your Lambda via environment variables.
     */
    declare public /*out*/ readonly endpoints: pulumi.Output<{[key: string]: string}>;
    /**
     * Map of region to VPC endpoint ID. Only populated when vpc is set and hasNat is false. Pass to LambdaVpcEndpointArgs.endpointId.
     */
    declare public /*out*/ readonly vpcEndpointIds: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * Map of region to VPC endpoint security group ID. Only populated when vpc is set and hasNat is false. Pass to LambdaVpcEndpointArgs.securityGroupId so Anvil can wire the egress rule from the Lambda SG to the endpoint SG on port 5432.
     */
    declare public /*out*/ readonly vpcEndpointSecurityGroupIds: pulumi.Output<{[key: string]: string} | undefined>;
    declare public /*out*/ readonly rolesTableName: pulumi.Output<string | undefined>;

    /**
     * Create a DSQL resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: DSQLArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["backup"] = args?.backup;
            resourceInputs["multiRegion"] = args?.multiRegion;
            resourceInputs["roles"] = args?.roles;
            resourceInputs["transform"] = args?.transform;
            resourceInputs["vpc"] = args?.vpc;
            resourceInputs["clusterArns"] = undefined /*out*/;
            resourceInputs["endpoints"] = undefined /*out*/;
            resourceInputs["vpcEndpointIds"] = undefined /*out*/;
            resourceInputs["vpcEndpointSecurityGroupIds"] = undefined /*out*/;
            resourceInputs["rolesTableName"] = undefined /*out*/;
        } else {
            resourceInputs["clusterArns"] = undefined /*out*/;
            resourceInputs["endpoints"] = undefined /*out*/;
            resourceInputs["vpcEndpointIds"] = undefined /*out*/;
            resourceInputs["vpcEndpointSecurityGroupIds"] = undefined /*out*/;
            resourceInputs["rolesTableName"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DSQL.__pulumiType, name, resourceInputs, opts, true /*remote*/);
        this.__name = name;
    }



    /**
     * Grants connect access (dsql:DbConnect) on this DSQL cluster
     * to the target compute resource's execution role.
     *
     * Creates an anvil:aws:DSQLConnect component that handles:
     * 1. IAM policy (dsql:DbConnect) on all cluster ARNs
     * 2. DynamoDB IAM mapping item (when roles are configured) that triggers
     *    the bootstrap Lambda to run: AWS IAM GRANT "dbRole" TO 'arn:...'
     *
     * @param target - The compute resource to grant access to (Lambda, ECS, etc.).
     * @param dbRole - The database role name to map this target to (e.g. "app_role").
     */
    public grantConnect(target: grants.GrantTarget, dbRole?: string): void {
        const args: any = {
            clusterArns: this.clusterArns,
            targetRoleArn: target.grantRoleArn(),
            targetName: target.grantName(),
            dbRole: dbRole,
        };
        if (this.rolesTableName) {
            args.rolesTableName = this.rolesTableName;
        }
        new DSQLConnect(`${this.__name}-${target.grantName()}-connect`, args, { parent: this });
    }

}

/**
 * The set of arguments for constructing a DSQL resource.
 */
export interface DSQLArgs {
    /**
     * AWS Backup configuration. Omit to disable. When set, Anvil opts in the DSQL resource type per region, creates a backup plan with retention and schedule, and for multi-region clusters automatically adds cross-region copy rules.
     */
    backup?: pulumi.Input<inputs.aws.DSQLBackupArgsArgs>;
    /**
     * Opt-in multi-region configuration. When set, Anvil creates two clusters in the specified regions and links them via ClusterPeering. When omitted, a single-region cluster is created in the provider's default region.
     */
    multiRegion?: pulumi.Input<inputs.aws.DSQLMultiRegionArgsArgs>;
    /**
     * Database roles to bootstrap at deploy time. Anvil connects as admin using the deployer's credentials and runs the SQL to create schemas, roles, IAM grants, and table-level permissions. Only re-runs when role definitions change. Omit entirely to skip bootstrapping — useful when managing schema separately.
     */
    roles?: pulumi.Input<pulumi.Input<inputs.aws.DSQLRoleArgs>[]>;
    transform?: pulumi.Input<inputs.aws.DsqlTransformArgsArgs>;
    /**
     * Optional VPC configuration. When set without hasNat, Anvil creates interface VPC endpoints (PrivateLink) per region so traffic stays on the AWS backbone. When omitted, the Lambda connects to the public DSQL endpoint over the internet using IAM auth tokens over TLS.
     */
    vpc?: pulumi.Input<inputs.aws.DSQLVpcArgsArgs>;
}
