// AUTO-GENERATED by scripts/grants/generate-grants.ts — do not edit.
// Adds grant methods to the generated DSQL class via declaration merging.
import * as pulumi from "@pulumi/pulumi";
import * as grants from "../grants";
import { DSQL } from "./dsql";
import { DSQLConnect } from "./dsqlconnect";

declare module "./dsql" {
    interface DSQL {
        grantConnect(target: grants.GrantTarget, opts: any): void;
    }
}


    /**
     * Grants a compute resource connect access to this DSQL cluster.
     *
     * Pass one or more { schema, roleName } pairs. The compute may be mapped to
     * multiple roles and connects as whichever one it chooses at runtime.
     *
     * Creates an anvil:aws:DSQLConnect component that handles:
     * 1. IAM policy (dsql:DbConnect) on all cluster ARNs
     * 2. One DynamoDB IAM mapping item per role — the bootstrap Lambda runs
     *    AWS IAM GRANT "<roleName>" TO 'arn:...' for each.
     *
     * @param target - The compute resource to grant access to (Lambda, ECS, etc.).
     * @param opts.schemas - The { schema, roleName } pairs this compute may connect as.
     *
     * @example
     *   dsql.grantConnect(lambda, { schemas: [{ schema: 'my_app', roleName: 'app_role' }] });
     */
    DSQL.prototype.grantConnect = function (
        target: grants.GrantTarget,
        opts: { schemas: { schema: string; roleName: string }[] },
    ): void {
        const dbRoles = opts.schemas.map((s) => s.roleName);
        const args: any = {
            clusterArns: this.clusterArns,
            targetRoleArn: target.grantRoleArn(),
            targetName: target.grantName(),
            dbRoles: dbRoles,
        };
        if (this.rolesTableName) {
            args.rolesTableName = this.rolesTableName;
        }
        // NOT parented to this DSQL component: DSQLConnect depends on this
        // component's outputs (clusterArns, rolesTableName). Parenting would
        // create a cycle — the parent's outputs only finalize after its
        // children complete, but this child needs those outputs to construct.
        new DSQLConnect(`${grants.grantResourceName(this)}-${target.grantName()}-connect`, args);
    };
