// AUTO-GENERATED by scripts/grants/generate-grants.ts — do not edit.
// Adds grant methods to the generated DynamoDB class via declaration merging.
import * as pulumi from "@pulumi/pulumi";
import * as grants from "../grants";
import { DynamoDB } from "./dynamoDB";


declare module "./dynamoDB" {
    interface DynamoDB {
        grantRead(target: grants.GrantTarget, opts?: { indexes?: string[]; justification?: string }): void;
        grantWrite(target: grants.GrantTarget, opts?: { indexes?: string[]; justification?: string }): void;
        grantReadWrite(target: grants.GrantTarget, opts?: { indexes?: string[]; justification?: string }): void;
        grantDelete(target: grants.GrantTarget, opts?: { indexes?: string[]; justification?: string }): void;
    }
}

DynamoDB.prototype.grantRead = function (this: DynamoDB, target: grants.GrantTarget, opts?: { indexes?: string[]; justification?: string }): void {
    const name = `${grants.grantResourceName(this)}-${target.grantName()}-read`;
    const indexPaths = opts?.indexes?.map((i) => `index/${i}`) ?? null;
    const arns = grants.buildResourceArns(this.tableArn, indexPaths);
    grants.createGrant(this, name, target, ["dynamodb:GetItem", "dynamodb:BatchGetItem", "dynamodb:Query", "dynamodb:Scan"], arns, { justification: opts?.justification });
};

DynamoDB.prototype.grantWrite = function (this: DynamoDB, target: grants.GrantTarget, opts?: { indexes?: string[]; justification?: string }): void {
    const name = `${grants.grantResourceName(this)}-${target.grantName()}-write`;
    const indexPaths = opts?.indexes?.map((i) => `index/${i}`) ?? null;
    const arns = grants.buildResourceArns(this.tableArn, indexPaths);
    grants.createGrant(this, name, target, ["dynamodb:PutItem", "dynamodb:UpdateItem", "dynamodb:BatchWriteItem"], arns, { justification: opts?.justification });
};

DynamoDB.prototype.grantReadWrite = function (this: DynamoDB, target: grants.GrantTarget, opts?: { indexes?: string[]; justification?: string }): void {
    const name = `${grants.grantResourceName(this)}-${target.grantName()}-readwrite`;
    const indexPaths = opts?.indexes?.map((i) => `index/${i}`) ?? null;
    const arns = grants.buildResourceArns(this.tableArn, indexPaths);
    grants.createGrant(this, name, target, ["dynamodb:GetItem", "dynamodb:BatchGetItem", "dynamodb:Query", "dynamodb:Scan", "dynamodb:PutItem", "dynamodb:UpdateItem", "dynamodb:BatchWriteItem"], arns, { justification: opts?.justification });
};

DynamoDB.prototype.grantDelete = function (this: DynamoDB, target: grants.GrantTarget, opts?: { indexes?: string[]; justification?: string }): void {
    const name = `${grants.grantResourceName(this)}-${target.grantName()}-delete`;
    const indexPaths = opts?.indexes?.map((i) => `index/${i}`) ?? null;
    const arns = grants.buildResourceArns(this.tableArn, indexPaths);
    grants.createGrant(this, name, target, ["dynamodb:DeleteItem"], arns, { justification: opts?.justification });
};
