// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

import * as pulumiAws from "@pulumi/aws";

/**
 * Serverless key-value and document store. Secure-by-default DynamoDB table with GSI support, optional streams, and Lambda/EventBridge consumers. First data layer component — pairs naturally with anvil.aws.Lambda.
 */
export class DynamoDB extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'anvil:aws:DynamoDB';

    /**
     * Returns true if the given object is an instance of DynamoDB.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DynamoDB {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DynamoDB.__pulumiType;
    }

    /**
     * The ARN of the DynamoDB stream. Only present when stream is enabled.
     */
    declare public /*out*/ readonly streamArn: pulumi.Output<string | undefined>;
    /**
     * The ARN of the DynamoDB table.
     */
    declare public /*out*/ readonly tableArn: pulumi.Output<string>;
    /**
     * The physical DynamoDB table name. Scoped as {name}-{stage}.
     */
    declare public /*out*/ readonly tableName: pulumi.Output<string>;

    /**
     * Create a DynamoDB resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DynamoDBArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.hashKey === undefined && !opts.urn) {
                throw new Error("Missing required property 'hashKey'");
            }
            resourceInputs["globalSecondaryIndexes"] = args?.globalSecondaryIndexes;
            resourceInputs["hashKey"] = args?.hashKey;
            resourceInputs["kmsKeyArn"] = args?.kmsKeyArn;
            resourceInputs["rangeKey"] = args?.rangeKey;
            resourceInputs["stream"] = args?.stream;
            resourceInputs["transform"] = args?.transform;
            resourceInputs["ttlAttribute"] = args?.ttlAttribute;
            resourceInputs["streamArn"] = undefined /*out*/;
            resourceInputs["tableArn"] = undefined /*out*/;
            resourceInputs["tableName"] = undefined /*out*/;
        } else {
            resourceInputs["streamArn"] = undefined /*out*/;
            resourceInputs["tableArn"] = undefined /*out*/;
            resourceInputs["tableName"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DynamoDB.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a DynamoDB resource.
 */
export interface DynamoDBArgs {
    /**
     * Global Secondary Indexes. All GSI key types must be explicitly declared — Anvil derives attributeDefinitions automatically from all declared keys.
     */
    globalSecondaryIndexes?: pulumi.Input<pulumi.Input<inputs.aws.DynamoDBGlobalSecondaryIndexArgs>[]>;
    /**
     * Primary hash (partition) key. Required.
     */
    hashKey: pulumi.Input<inputs.aws.DynamoDBKeyAttributeArgs>;
    /**
     * Tier 2 opt-in. ARN of a KMS CMK for encryption at rest. If omitted, AWS_OWNED_KMS is used (Tier 1 default — always on, zero cost). Use this for compliance workloads requiring key rotation control, audit trail, or the ability to revoke access by disabling the key.
     */
    kmsKeyArn?: pulumi.Input<string>;
    /**
     * Primary range (sort) key. Optional.
     */
    rangeKey?: pulumi.Input<inputs.aws.DynamoDBKeyAttributeArgs>;
    /**
     * DynamoDB Streams configuration. Opt-in. Enables change data capture on the table.
     */
    stream?: pulumi.Input<inputs.aws.DynamoDBStreamArgs>;
    transform?: pulumi.Input<inputs.aws.DynamoTransformArgsArgs>;
    /**
     * Name of the attribute used for TTL (time-to-live). Items with this attribute set to a past Unix timestamp are automatically deleted by DynamoDB.
     */
    ttlAttribute?: pulumi.Input<string>;
}
