// AUTO-GENERATED by scripts/grants/generate-grants.ts — do not edit.
// Adds grant methods to the generated EventBus class via declaration merging.
import * as pulumi from "@pulumi/pulumi";
import * as grants from "../grants";
import { EventBus } from "./eventBus";


declare module "./eventBus" {
    interface EventBus {
        grantPutEvents(target: grants.GrantTarget, opts?: grants.GrantOptions): void;
    }
}

EventBus.prototype.grantPutEvents = function (this: EventBus, target: grants.GrantTarget, opts?: grants.GrantOptions): void {
    const name = `${grants.grantResourceName(this)}-${target.grantName()}-putevents`;
    const arns = grants.buildResourceArns(this.arn, undefined);
    grants.createGrant(this, name, target, ["events:PutEvents"], arns, opts);
};
