// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { BucketArgs } from "./bucket";
export type Bucket = import("./bucket").Bucket;
export const Bucket: typeof import("./bucket").Bucket = null as any;
utilities.lazyLoad(exports, ["Bucket"], () => require("./bucket"));

export { LambdaArgs } from "./lambda";
export type Lambda = import("./lambda").Lambda;
export const Lambda: typeof import("./lambda").Lambda = null as any;
utilities.lazyLoad(exports, ["Lambda"], () => require("./lambda"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "anvil:aws:Bucket":
                return new Bucket(name, <any>undefined, { urn })
            case "anvil:aws:Lambda":
                return new Lambda(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("anvil", "aws", _module)
