// AUTO-GENERATED by scripts/grants/generate-grants.ts — do not edit.
// Adds grant methods to the generated Lambda class via declaration merging.
import * as pulumi from "@pulumi/pulumi";
import * as grants from "../grants";
import { Lambda } from "./lambda";


declare module "./lambda" {
    interface Lambda {
        grantInvoke(target: grants.GrantTarget, opts?: grants.GrantOptions): void;
        grantName(): string;
        grantRoleArn(): pulumi.Output<string>;
    }
}

Lambda.prototype.grantInvoke = function (this: Lambda, target: grants.GrantTarget, opts?: grants.GrantOptions): void {
    const name = `${grants.grantResourceName(this)}-${target.grantName()}-invoke`;
    const arns = grants.buildResourceArns(this.arn, undefined);
    grants.createGrant(this, name, target, ["lambda:InvokeFunction"], arns, opts);
};

Lambda.prototype.grantName = function (this: Lambda): string {
    return grants.grantResourceName(this);
};

Lambda.prototype.grantRoleArn = function (this: Lambda): pulumi.Output<string> {
    return this.roleArn;
};
