// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

import * as pulumiAws from "@pulumi/aws";
import * as grants from "../grants";

export class Lambda extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'anvil:aws:Lambda';

    /** @internal Logical resource name for grant policy naming. */
    private __name: string;

    /**
     * Returns true if the given object is an instance of Lambda.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Lambda {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Lambda.__pulumiType;
    }

    /**
     * The ARN of the Lambda function.
     */
    declare public /*out*/ readonly arn: pulumi.Output<string>;
    /**
     * The name of the Lambda function.
     */
    declare public /*out*/ readonly functionName: pulumi.Output<string>;
    /**
     * The ARN of the Lambda's IAM execution role.
     */
    declare public /*out*/ readonly roleArn: pulumi.Output<string>;

    /**
     * Create a Lambda resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: LambdaArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["name"] = args?.name;
            resourceInputs["transform"] = args?.transform;
            resourceInputs["vpc"] = args?.vpc;
            resourceInputs["arn"] = undefined /*out*/;
            resourceInputs["functionName"] = undefined /*out*/;
            resourceInputs["roleArn"] = undefined /*out*/;
        } else {
            resourceInputs["arn"] = undefined /*out*/;
            resourceInputs["functionName"] = undefined /*out*/;
            resourceInputs["roleArn"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Lambda.__pulumiType, name, resourceInputs, opts, true /*remote*/);
        this.__name = name;
    }

    /**
     * Grants invoke access (lambda:InvokeFunction) on this lambda
     * to the target compute resource's execution role.
     *
     * @param target - The compute resource to grant access to.
     * @param opts - Optional grant options (justification for audit trail).
     */
    public grantInvoke(target: grants.GrantTarget, opts?: grants.GrantOptions): void {
        const name = `${this.__name}-${target.grantName()}-invoke`;
        const arns = grants.buildResourceArns(this.arn, undefined);
        grants.createGrant(this, name, target, ["lambda:InvokeFunction"], arns, opts);
    }
    /** Implements GrantTarget — returns the logical resource name. */
    public grantName(): string {
        return this.__name;
    }

    /** Implements GrantTarget — returns the IAM execution role ARN. */
    public grantRoleArn(): pulumi.Output<string> {
        return this.roleArn;
    }

}

/**
 * The set of arguments for constructing a Lambda resource.
 */
export interface LambdaArgs {
    /**
     * The logical name of the Lambda function.
     */
    name: pulumi.Input<string>;
    transform?: pulumi.Input<inputs.aws.LambdaTransformArgsArgs>;
    /**
     * The ID of the AWS VPC to deploy this function into.
     */
    vpc?: pulumi.Input<string>;
}
