// AUTO-GENERATED by scripts/grants/generate-grants.ts — do not edit.
// Adds grant methods to the generated Queue class via declaration merging.
import * as pulumi from "@pulumi/pulumi";
import * as grants from "../grants";
import { Queue } from "./queue";


declare module "./queue" {
    interface Queue {
        grantSendMessage(target: grants.GrantTarget, opts?: grants.GrantOptions): void;
        grantConsumeMessages(target: grants.GrantTarget, opts?: grants.GrantOptions): void;
        grantFullAccess(target: grants.GrantTarget, opts?: grants.GrantOptions): void;
    }
}

Queue.prototype.grantSendMessage = function (this: Queue, target: grants.GrantTarget, opts?: grants.GrantOptions): void {
    const name = `${grants.grantResourceName(this)}-${target.grantName()}-sendmessage`;
    const arns = grants.buildResourceArns(this.arn, undefined);
    grants.createGrant(this, name, target, ["sqs:SendMessage"], arns, opts);
};

Queue.prototype.grantConsumeMessages = function (this: Queue, target: grants.GrantTarget, opts?: grants.GrantOptions): void {
    const name = `${grants.grantResourceName(this)}-${target.grantName()}-consumemessages`;
    const arns = grants.buildResourceArns(this.arn, undefined);
    grants.createGrant(this, name, target, ["sqs:ReceiveMessage", "sqs:DeleteMessage", "sqs:GetQueueAttributes"], arns, opts);
};

Queue.prototype.grantFullAccess = function (this: Queue, target: grants.GrantTarget, opts?: grants.GrantOptions): void {
    if (!opts?.justification) {
        pulumi.log.warn(
            `⚠ ${grants.grantResourceName(this)} → ${target.grantName()}: full access granted with no justification. ` +
            `Consider a scoped grant or add a justification.`,
            this,
        );
    } else {
        pulumi.log.info(
            `ℹ ${grants.grantResourceName(this)} → ${target.grantName()}: full access granted. Justification: "${opts.justification}"`,
            this,
        );
    }
    const name = `${grants.grantResourceName(this)}-${target.grantName()}-fullaccess`;
    const arns = grants.buildResourceArns(this.arn, undefined);
    grants.createGrant(this, name, target, ["sqs:SendMessage", "sqs:ReceiveMessage", "sqs:DeleteMessage", "sqs:GetQueueAttributes", "sqs:ChangeMessageVisibility", "sqs:PurgeQueue"], arns, opts);
};
