// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * SvelteKitSite is an Anvil-managed SvelteKit deployment on AWS. Static assets go to S3 behind CloudFront. Server code runs on Lambda.
 */
export class SvelteKitSite extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'anvil:aws:SvelteKitSite';

    /**
     * Returns true if the given object is an instance of SvelteKitSite.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SvelteKitSite {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SvelteKitSite.__pulumiType;
    }

    /**
     * The S3 bucket name storing static assets.
     */
    declare public /*out*/ readonly bucketName: pulumi.Output<string | undefined>;
    /**
     * The CloudFront distribution ID serving the site.
     */
    declare public /*out*/ readonly cloudFrontDistributionId: pulumi.Output<string | undefined>;
    /**
     * DNS records the user needs to create (if domain is set and not on Route53). Empty if no domain or if Route53 records were created automatically.
     */
    declare public /*out*/ readonly dnsRecords: pulumi.Output<string | undefined>;
    /**
     * The Lambda function name running SSR.
     */
    declare public /*out*/ readonly functionName: pulumi.Output<string | undefined>;
    /**
     * The URL where the site is accessible.
     */
    declare public /*out*/ readonly url: pulumi.Output<string | undefined>;

    /**
     * Create a SvelteKitSite resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SvelteKitSiteArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.path === undefined && !opts.urn) {
                throw new Error("Missing required property 'path'");
            }
            resourceInputs["domain"] = args?.domain;
            resourceInputs["environment"] = args?.environment;
            resourceInputs["path"] = args?.path;
            resourceInputs["transform"] = args?.transform;
            resourceInputs["bucketName"] = undefined /*out*/;
            resourceInputs["cloudFrontDistributionId"] = undefined /*out*/;
            resourceInputs["dnsRecords"] = undefined /*out*/;
            resourceInputs["functionName"] = undefined /*out*/;
            resourceInputs["url"] = undefined /*out*/;
        } else {
            resourceInputs["bucketName"] = undefined /*out*/;
            resourceInputs["cloudFrontDistributionId"] = undefined /*out*/;
            resourceInputs["dnsRecords"] = undefined /*out*/;
            resourceInputs["functionName"] = undefined /*out*/;
            resourceInputs["url"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SvelteKitSite.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a SvelteKitSite resource.
 */
export interface SvelteKitSiteArgs {
    /**
     * Custom domain name for the site. When set, Anvil configures DNS and TLS certificates automatically.
     */
    domain?: pulumi.Input<string>;
    /**
     * Environment variables injected at both build time and runtime. Build time: available via $env/static and import.meta.env during static generation and prerendering. Runtime: set on the compute service (Lambda/Cloud Run) for SSR and API routes via $env/dynamic.
     */
    environment?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Path to the SvelteKit project directory, relative to the project root (where anvil.yaml lives). Not relative to the anvil.config file.
     */
    path: pulumi.Input<string>;
    /**
     * Transform overrides for underlying AWS resources.
     */
    transform?: pulumi.Input<string>;
}
