// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

import * as pulumiAws from "@pulumi/aws";

/**
 * An Anvil-managed AWS WAF WebACL with researched defaults: a per-client rate limit (2000 requests / 5 min) and AWS managed rule groups for IP reputation, known bad inputs, the OWASP core rule set and SQL injection. Starts in count mode — matches are logged, not blocked — until mode is set to "block". Attach it to a site with waf: { arn } or to a Cognito user pool with waf: { arn }.
 */
export class Waf extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'anvil:aws:Waf';

    /**
     * Returns true if the given object is an instance of Waf.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Waf {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Waf.__pulumiType;
    }

    /**
     * The WebACL ARN. Pass it to a site's waf.arn (cloudfront scope) or a Cognito user pool's waf.arn (regional scope).
     */
    declare public /*out*/ readonly arn: pulumi.Output<string>;
    /**
     * The CloudWatch log group receiving WAF logs. Empty when logging is off.
     */
    declare public /*out*/ readonly logGroupName: pulumi.Output<string>;
    /**
     * The physical WebACL name.
     */
    declare public /*out*/ readonly name: pulumi.Output<string>;
    /**
     * "cloudfront" or "regional".
     */
    declare public readonly scope: pulumi.Output<string>;
    /**
     * The WebACL ID.
     */
    declare public /*out*/ readonly webAclId: pulumi.Output<string>;

    /**
     * Create a Waf resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: WafArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["blockCountries"] = args?.blockCountries;
            resourceInputs["clientIpHeader"] = args?.clientIpHeader;
            resourceInputs["ipAllowList"] = args?.ipAllowList;
            resourceInputs["ipBlockList"] = args?.ipBlockList;
            resourceInputs["logging"] = args?.logging;
            resourceInputs["managedRules"] = args?.managedRules;
            resourceInputs["mode"] = args?.mode;
            resourceInputs["rateLimit"] = args?.rateLimit;
            resourceInputs["ruleOverrides"] = args?.ruleOverrides;
            resourceInputs["scope"] = args?.scope;
            resourceInputs["transform"] = args?.transform;
            resourceInputs["arn"] = undefined /*out*/;
            resourceInputs["logGroupName"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["webAclId"] = undefined /*out*/;
        } else {
            resourceInputs["arn"] = undefined /*out*/;
            resourceInputs["logGroupName"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["scope"] = undefined /*out*/;
            resourceInputs["webAclId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Waf.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a Waf resource.
 */
export interface WafArgs {
    /**
     * Two-letter ISO 3166 country codes to block, e.g. ["KP"]. Follows mode.
     */
    blockCountries?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Header carrying the real visitor IP when the site sits behind a proxy, e.g. "CF-Connecting-IP" for Cloudflare. The rate limit, IP lists and country blocking then use the visitor's IP instead of the proxy's. AWS's ipReputation and anonymousIp rule groups can't read this header, so they default to off when it's set.
     */
    clientIpHeader?: pulumi.Input<string>;
    /**
     * IP addresses or CIDRs (IPv4 and IPv6) that are always allowed, skipping every other rule — e.g. office networks or uptime monitors.
     */
    ipAllowList?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * IP addresses or CIDRs (IPv4 and IPv6) that are always blocked.
     */
    ipBlockList?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Logging to CloudWatch Logs. On by default: blocked and counted requests only, kept 30 days, with the authorization, cookie and x-origin-secret headers redacted.
     */
    logging?: pulumi.Input<inputs.aws.WafLoggingArgsArgs>;
    /**
     * AWS managed rule groups. On by default: core, knownBadInputs, ipReputation, sqli. Off by default: anonymousIp, adminProtection.
     */
    managedRules?: pulumi.Input<inputs.aws.WafManagedRulesArgsArgs>;
    /**
     * What rules do when they match. "count" (default): log the match without blocking — use this to check for false positives on live traffic. "block": block matching requests. The IP allow and block lists always allow / block regardless of mode.
     */
    mode?: pulumi.Input<enums.aws.WafMode>;
    /**
     * Per-client rate limit. On by default: 2000 requests per client per 5 minutes.
     */
    rateLimit?: pulumi.Input<inputs.aws.WafRateLimitArgsArgs>;
    /**
     * Override the action of individual AWS managed rules, keyed by exact AWS rule name: "count", "block" or "allow". Default: { SizeRestrictions_BODY: "count" } — that rule blocks any body over 8 KB, which breaks forms, JSON APIs and uploads. Set it to "block" to restore it.
     */
    ruleOverrides?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * What the WAF protects. "cloudfront" (default): sites and other CloudFront distributions; created in us-east-1 as AWS requires. "regional": regional resources such as Cognito user pools; created in the stack's region.
     */
    scope?: pulumi.Input<enums.aws.WafScope>;
    transform?: pulumi.Input<inputs.aws.WafTransformArgsArgs>;
}
