[project]
  name = "anvil_cloud"
  description = "Anvil — secure-by-default cloud infrastructure components"
  dependencies = ["parver>=0.2.1", "pulumi>=3.0.0,<4.0.0", "pulumi-aws>=7.21.0,<8.0.0", "pulumi-gcp>=9.0.0,<10.0.0", "semver>=2.8.1", "typing-extensions>=4.11,<5; python_version < \"3.11\""]
  readme = "README.md"
  requires-python = ">=3.9"
  version = "0.0.16"
  [project.license]
    text = "Apache-2.0"
  [project.urls]
    Homepage = "https://github.com/anvil-cloud/anvil"
    Repository = "https://github.com/DamienPace15/anvil"

[build-system]
  requires = ["setuptools>=61.0"]
  build-backend = "setuptools.build_meta"

[tool]
  [tool.setuptools]
    [tool.setuptools.package-data]
      anvil_cloud = ["py.typed", "pulumi-plugin.json"]
