package codegen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type GoGenerator struct{}

func (g *GoGenerator) Name() string { return "go" }

func (g *GoGenerator) Generate(schemas map[string]DSQLComponent, outDir string) error {
	for _, comp := range schemas {
		for _, s := range comp.Schemas {
			code := generateGo(s)
			path := filepath.Join(outDir, ToSnakeCase(s.Name)+".go")
			if err := os.WriteFile(path, []byte(code), 0o644); err != nil {
				return fmt.Errorf("writing %s: %w", path, err)
			}
		}
	}
	return nil
}

func generateGo(s Schema) string {
	var b strings.Builder
	b.WriteString("// generated by anvil generate — do not edit\n")
	b.WriteString("package db\n\n")

	imports := goImports(s)
	if imports != "" {
		fmt.Fprintf(&b, "import (\n%s)\n\n", imports)
	}

	for _, t := range s.Tables {
		writeGoTypes(&b, t)
		b.WriteString("\n")
	}

	writeGoQueries(&b, s)
	return b.String()
}

func writeGoTypes(b *strings.Builder, t Table) {
	row := ToPascalCase(t.Name) + "Row"
	ins := ToPascalCase(t.Name) + "Insert"
	upd := ToPascalCase(t.Name) + "Update"

	pkSet := map[string]bool{}
	for _, pk := range t.PrimaryKey {
		pkSet[pk] = true
	}
	hasDefaultSet := map[string]bool{}
	for _, c := range t.Columns {
		if c.Default != "" {
			hasDefaultSet[c.Name] = true
		}
	}

	// Row
	fmt.Fprintf(b, "type %s struct {\n", row)
	for _, c := range t.Columns {
		goT := goType(c)
		fieldName := ToPascalCase(c.Name)
		fmt.Fprintf(b, "\t%s %s `json:\"%s\" db:\"%s\"`\n", fieldName, goT, c.Name, c.Name)
	}
	b.WriteString("}\n\n")

	// Insert
	fmt.Fprintf(b, "type %s struct {\n", ins)
	for _, c := range t.Columns {
		fieldName := ToPascalCase(c.Name)
		required := pkSet[c.Name] || (c.NotNull && !hasDefaultSet[c.Name])
		var goT string
		if required {
			c2 := c
			c2.NotNull = true
			goT = goType(c2)
			fmt.Fprintf(b, "\t%s %s `json:\"%s\" db:\"%s\"`\n", fieldName, goT, c.Name, c.Name)
		} else {
			goT = goTypePtr(c)
			fmt.Fprintf(b, "\t%s %s `json:\"%s,omitempty\" db:\"%s\"`\n", fieldName, goT, c.Name, c.Name)
		}
	}
	b.WriteString("}\n\n")

	// Update — all pointers
	fmt.Fprintf(b, "type %s struct {\n", upd)
	for _, c := range t.Columns {
		goT := goTypePtr(c)
		fieldName := ToPascalCase(c.Name)
		fmt.Fprintf(b, "\t%s %s `json:\"%s,omitempty\" db:\"%s\"`\n", fieldName, goT, c.Name, c.Name)
	}
	b.WriteString("}\n")
}

func writeGoQueries(b *strings.Builder, s Schema) {
	for _, t := range s.Tables {
		writeGoTableQueries(b, s.Name, t)
	}
}

func writeGoTableQueries(b *strings.Builder, schemaName string, t Table) {
	row := ToPascalCase(t.Name) + "Row"
	ins := ToPascalCase(t.Name) + "Insert"
	upd := ToPascalCase(t.Name) + "Update"
	structName := ToPascalCase(t.Name) + "Queries"
	qualifiedTable := schemaName + "." + t.Name

	colNames := make([]string, len(t.Columns))
	for i, c := range t.Columns {
		colNames[i] = c.Name
	}
	selectCols := strings.Join(colNames, ", ")

	scanFields := make([]string, len(t.Columns))
	for i, c := range t.Columns {
		scanFields[i] = "&row." + ToPascalCase(c.Name)
	}
	scanArgs := strings.Join(scanFields, ", ")

	fmt.Fprintf(b, "\ntype %s struct {\n\tdb interface {\n\t\tQueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error)\n\t\tQueryRowContext(ctx context.Context, query string, args ...any) *sql.Row\n\t\tExecContext(ctx context.Context, query string, args ...any) (sql.Result, error)\n\t}\n}\n\n", structName)

	fmt.Fprintf(b, "func New%s(db interface {\n\tQueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error)\n\tQueryRowContext(ctx context.Context, query string, args ...any) *sql.Row\n\tExecContext(ctx context.Context, query string, args ...any) (sql.Result, error)\n}) *%s {\n", structName, structName)
	fmt.Fprintf(b, "\treturn &%s{db: db}\n}\n\n", structName)

	// FindByID
	goPKParams := makeGoPKParams(t)
	goPKArgs := makeGoPKArgs(t)
	pkWhere := makeGoPKWhere(t, 1)

	fmt.Fprintf(b, "func (q *%s) FindByID(ctx context.Context, %s) (*%s, error) {\n", structName, goPKParams, row)
	fmt.Fprintf(b, "\tvar row %s\n", row)
	fmt.Fprintf(b, "\terr := q.db.QueryRowContext(ctx,\n\t\t\"SELECT %s FROM %s WHERE %s\",\n\t\t%s,\n\t).Scan(%s)\n", selectCols, qualifiedTable, pkWhere, goPKArgs, scanArgs)
	b.WriteString("\tif err != nil {\n\t\tif err == sql.ErrNoRows {\n\t\t\treturn nil, nil\n\t\t}\n\t\treturn nil, err\n\t}\n")
	b.WriteString("\treturn &row, nil\n}\n\n")

	// FindMany
	fmt.Fprintf(b, "func (q *%s) FindMany(ctx context.Context) ([]%s, error) {\n", structName, row)
	fmt.Fprintf(b, "\trows, err := q.db.QueryContext(ctx, \"SELECT %s FROM %s\")\n", selectCols, qualifiedTable)
	b.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n\tdefer rows.Close()\n\n")
	fmt.Fprintf(b, "\tvar result []%s\n\tfor rows.Next() {\n\t\tvar row %s\n", row, row)
	fmt.Fprintf(b, "\t\tif err := rows.Scan(%s); err != nil {\n\t\t\treturn nil, err\n\t\t}\n", scanArgs)
	b.WriteString("\t\tresult = append(result, row)\n\t}\n\treturn result, rows.Err()\n}\n\n")

	// Insert
	fmt.Fprintf(b, "func (q *%s) Insert(ctx context.Context, row %s) (*%s, error) {\n", structName, ins, row)
	fmt.Fprintf(b, "\tvar result %s\n", row)
	b.WriteString("\t// Build column list and values dynamically based on non-nil fields\n")

	insertCols := make([]string, 0, len(t.Columns))
	insertPlaceholders := make([]string, 0, len(t.Columns))
	insertArgs := make([]string, 0, len(t.Columns))
	for i, c := range t.Columns {
		insertCols = append(insertCols, c.Name)
		insertPlaceholders = append(insertPlaceholders, fmt.Sprintf("$%d", i+1))
		insertArgs = append(insertArgs, "row."+ToPascalCase(c.Name))
	}

	fmt.Fprintf(b, "\terr := q.db.QueryRowContext(ctx,\n\t\t\"INSERT INTO %s (%s) VALUES (%s) RETURNING %s\",\n\t\t%s,\n\t).Scan(%s)\n",
		qualifiedTable,
		strings.Join(insertCols, ", "),
		strings.Join(insertPlaceholders, ", "),
		selectCols,
		strings.Join(insertArgs, ", "),
		scanArgs,
	)
	b.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n\treturn &result, nil\n}\n\n")

	// Delete
	fmt.Fprintf(b, "func (q *%s) Delete(ctx context.Context, %s) (bool, error) {\n", structName, goPKParams)
	fmt.Fprintf(b, "\tresult, err := q.db.ExecContext(ctx,\n\t\t\"DELETE FROM %s WHERE %s\",\n\t\t%s,\n\t)\n", qualifiedTable, pkWhere, goPKArgs)
	b.WriteString("\tif err != nil {\n\t\treturn false, err\n\t}\n")
	b.WriteString("\tn, err := result.RowsAffected()\n\tif err != nil {\n\t\treturn false, err\n\t}\n\treturn n > 0, nil\n}\n")

	_ = upd // update is more complex with dynamic fields; keeping the type available
}

// Helpers

func goType(c Column) string {
	m, ok := typeMappings[c.Type]
	if !ok {
		return "any"
	}
	base := m.Go
	if !c.NotNull {
		if strings.HasPrefix(base, "[]") {
			return base
		}
		return "*" + base
	}
	return base
}

func goTypePtr(c Column) string {
	m, ok := typeMappings[c.Type]
	if !ok {
		return "any"
	}
	base := m.Go
	if strings.HasPrefix(base, "[]") {
		return base
	}
	return "*" + base
}

func goImports(s Schema) string {
	needsTime := false
	needsJSON := false
	for _, t := range s.Tables {
		for _, c := range t.Columns {
			switch c.Type {
			case "date", "timestamp", "timestamptz":
				needsTime = true
			case "json", "jsonb":
				needsJSON = true
			}
		}
	}

	var imports []string
	imports = append(imports, "\t\"context\"")
	imports = append(imports, "\t\"database/sql\"")
	if needsJSON {
		imports = append(imports, "\t\"encoding/json\"")
	}
	if needsTime {
		imports = append(imports, "\t\"time\"")
	}

	// Suppress unused import warnings
	_ = needsJSON

	return strings.Join(imports, "\n") + "\n"
}

func makeGoPKParams(t Table) string {
	colMap := map[string]Column{}
	for _, c := range t.Columns {
		colMap[c.Name] = c
	}
	parts := make([]string, len(t.PrimaryKey))
	for i, pk := range t.PrimaryKey {
		c := colMap[pk]
		c.NotNull = true
		parts[i] = fmt.Sprintf("%s %s", ToCamelCase(pk), goType(c))
	}
	return strings.Join(parts, ", ")
}

func makeGoPKWhere(t Table, startIdx int) string {
	parts := make([]string, len(t.PrimaryKey))
	for i, pk := range t.PrimaryKey {
		parts[i] = fmt.Sprintf("%s = $%d", pk, startIdx+i)
	}
	return strings.Join(parts, " AND ")
}

func makeGoPKArgs(t Table) string {
	parts := make([]string, len(t.PrimaryKey))
	for i, pk := range t.PrimaryKey {
		parts[i] = ToCamelCase(pk)
	}
	return strings.Join(parts, ", ")
}
