package codegen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type RustGenerator struct{}

func (g *RustGenerator) Name() string { return "rust" }

func (g *RustGenerator) Generate(schemas map[string]DSQLComponent, outDir string) error {
	for _, comp := range schemas {
		for _, s := range comp.Schemas {
			code := generateRust(s)
			path := filepath.Join(outDir, ToSnakeCase(s.Name)+".rs")
			if err := os.WriteFile(path, []byte(code), 0o644); err != nil {
				return fmt.Errorf("writing %s: %w", path, err)
			}
		}
	}

	mod := generateRustMod(schemas)
	path := filepath.Join(outDir, "mod.rs")
	return os.WriteFile(path, []byte(mod), 0o644)
}

func generateRust(s Schema) string {
	var b strings.Builder
	b.WriteString("// generated by anvil generate — do not edit\n\n")

	imports := rustImports(s)
	if imports != "" {
		b.WriteString(imports)
		b.WriteString("\n")
	}

	for _, t := range s.Tables {
		writeRustTypes(&b, t)
		b.WriteString("\n")
	}

	writeRustQueries(&b, s)
	return b.String()
}

func writeRustTypes(b *strings.Builder, t Table) {
	row := ToPascalCase(t.Name) + "Row"
	ins := ToPascalCase(t.Name) + "Insert"
	upd := ToPascalCase(t.Name) + "Update"

	pkSet := map[string]bool{}
	for _, pk := range t.PrimaryKey {
		pkSet[pk] = true
	}
	hasDefaultSet := map[string]bool{}
	for _, c := range t.Columns {
		if c.Default != "" {
			hasDefaultSet[c.Name] = true
		}
	}

	// Row
	fmt.Fprintf(b, "#[derive(Debug, Clone, Serialize, Deserialize)]\n")
	fmt.Fprintf(b, "pub struct %s {\n", row)
	for _, c := range t.Columns {
		rustT := rustType(c)
		fmt.Fprintf(b, "    pub %s: %s,\n", ToSnakeCase(c.Name), rustT)
	}
	b.WriteString("}\n\n")

	// Insert
	fmt.Fprintf(b, "#[derive(Debug, Clone, Serialize, Deserialize)]\n")
	fmt.Fprintf(b, "pub struct %s {\n", ins)
	for _, c := range t.Columns {
		required := pkSet[c.Name] || (c.NotNull && !hasDefaultSet[c.Name])
		if required {
			c2 := c
			c2.NotNull = true
			rustT := rustType(c2)
			fmt.Fprintf(b, "    pub %s: %s,\n", ToSnakeCase(c.Name), rustT)
		} else {
			rustT := rustTypeOption(c)
			fmt.Fprintf(b, "    pub %s: %s,\n", ToSnakeCase(c.Name), rustT)
		}
	}
	b.WriteString("}\n\n")

	// Update — all Option
	fmt.Fprintf(b, "#[derive(Debug, Clone, Default, Serialize, Deserialize)]\n")
	fmt.Fprintf(b, "pub struct %s {\n", upd)
	for _, c := range t.Columns {
		rustT := rustTypeOption(c)
		fmt.Fprintf(b, "    pub %s: %s,\n", ToSnakeCase(c.Name), rustT)
	}
	b.WriteString("}\n")
}

func writeRustQueries(b *strings.Builder, s Schema) {
	for _, t := range s.Tables {
		writeRustTableQueries(b, s.Name, t)
	}
}

func writeRustTableQueries(b *strings.Builder, schemaName string, t Table) {
	row := ToPascalCase(t.Name) + "Row"
	ins := ToPascalCase(t.Name) + "Insert"
	structName := ToPascalCase(t.Name) + "Queries"
	qualifiedTable := schemaName + "." + t.Name

	colNames := make([]string, len(t.Columns))
	for i, c := range t.Columns {
		colNames[i] = c.Name
	}
	selectCols := strings.Join(colNames, ", ")

	fmt.Fprintf(b, "\npub struct %s<'a> {\n    client: &'a Client,\n}\n\n", structName)

	fmt.Fprintf(b, "impl<'a> %s<'a> {\n", structName)
	fmt.Fprintf(b, "    pub fn new(client: &'a Client) -> Self {\n        Self { client }\n    }\n\n")

	// find_by_id
	pkParams := makeRustPKParams(t)
	pkWhere := makeRustPKWhere(t, 1)
	pkArgs := makeRustPKArgs(t)

	fmt.Fprintf(b, "    pub async fn find_by_id(&self, %s) -> Result<Option<%s>, Error> {\n", pkParams, row)
	fmt.Fprintf(b, "        let row = self.client\n")
	fmt.Fprintf(b, "            .query_opt(\n")
	fmt.Fprintf(b, "                \"SELECT %s FROM %s WHERE %s\",\n", selectCols, qualifiedTable, pkWhere)
	fmt.Fprintf(b, "                &[%s],\n", pkArgs)
	b.WriteString("            )\n            .await?;\n")
	b.WriteString("        Ok(row.map(|r| ")
	fmt.Fprintf(b, "%s {\n", row)
	for _, c := range t.Columns {
		fmt.Fprintf(b, "            %s: r.get(\"%s\"),\n", ToSnakeCase(c.Name), c.Name)
	}
	b.WriteString("        }))\n    }\n\n")

	// find_many
	fmt.Fprintf(b, "    pub async fn find_many(&self) -> Result<Vec<%s>, Error> {\n", row)
	fmt.Fprintf(b, "        let rows = self.client\n")
	fmt.Fprintf(b, "            .query(\"SELECT %s FROM %s\", &[])\n", selectCols, qualifiedTable)
	b.WriteString("            .await?;\n")
	b.WriteString("        Ok(rows.into_iter().map(|r| ")
	fmt.Fprintf(b, "%s {\n", row)
	for _, c := range t.Columns {
		fmt.Fprintf(b, "            %s: r.get(\"%s\"),\n", ToSnakeCase(c.Name), c.Name)
	}
	b.WriteString("        }).collect())\n    }\n\n")

	// insert
	fmt.Fprintf(b, "    pub async fn insert(&self, row: &%s) -> Result<%s, Error> {\n", ins, row)
	insertPlaceholders := make([]string, len(t.Columns))
	insertArgs := make([]string, len(t.Columns))
	for i, c := range t.Columns {
		insertPlaceholders[i] = fmt.Sprintf("$%d", i+1)
		insertArgs[i] = fmt.Sprintf("&row.%s", ToSnakeCase(c.Name))
	}
	fmt.Fprintf(b, "        let result = self.client\n")
	fmt.Fprintf(b, "            .query_one(\n")
	fmt.Fprintf(b, "                \"INSERT INTO %s (%s) VALUES (%s) RETURNING %s\",\n",
		qualifiedTable, strings.Join(colNames, ", "),
		strings.Join(insertPlaceholders, ", "), selectCols)
	fmt.Fprintf(b, "                &[%s],\n", strings.Join(insertArgs, ", "))
	b.WriteString("            )\n            .await?;\n")
	fmt.Fprintf(b, "        Ok(%s {\n", row)
	for _, c := range t.Columns {
		fmt.Fprintf(b, "            %s: result.get(\"%s\"),\n", ToSnakeCase(c.Name), c.Name)
	}
	b.WriteString("        })\n    }\n\n")

	// delete
	fmt.Fprintf(b, "    pub async fn delete(&self, %s) -> Result<bool, Error> {\n", pkParams)
	fmt.Fprintf(b, "        let n = self.client\n")
	fmt.Fprintf(b, "            .execute(\n")
	fmt.Fprintf(b, "                \"DELETE FROM %s WHERE %s\",\n", qualifiedTable, pkWhere)
	fmt.Fprintf(b, "                &[%s],\n", pkArgs)
	b.WriteString("            )\n            .await?;\n")
	b.WriteString("        Ok(n > 0)\n    }\n")

	b.WriteString("}\n")

	_ = ins // used above
}

func generateRustMod(schemas map[string]DSQLComponent) string {
	var b strings.Builder
	b.WriteString("// generated by anvil generate — do not edit\n\n")
	for _, comp := range schemas {
		for _, s := range comp.Schemas {
			file := ToSnakeCase(s.Name)
			fmt.Fprintf(&b, "pub mod %s;\n", file)
		}
	}
	return b.String()
}

// Helpers

func rustType(c Column) string {
	m, ok := typeMappings[c.Type]
	if !ok {
		return "serde_json::Value"
	}
	base := m.Rust
	if !c.NotNull {
		return "Option<" + base + ">"
	}
	return base
}

func rustTypeOption(c Column) string {
	m, ok := typeMappings[c.Type]
	if !ok {
		return "Option<serde_json::Value>"
	}
	return "Option<" + m.Rust + ">"
}

func rustImports(s Schema) string {
	needsUuid := false
	needsChrono := false
	needsDecimal := false
	needsSerde := false
	needsSerdeJSON := false

	for _, t := range s.Tables {
		needsSerde = true
		for _, c := range t.Columns {
			switch c.Type {
			case "uuid":
				needsUuid = true
			case "date", "time", "timestamp", "timestamptz":
				needsChrono = true
			case "numeric":
				needsDecimal = true
			case "json", "jsonb":
				needsSerdeJSON = true
			}
		}
	}

	var lines []string
	if needsChrono {
		lines = append(lines, "use chrono::{DateTime, NaiveDate, NaiveDateTime, NaiveTime, Utc};")
	}
	if needsDecimal {
		lines = append(lines, "use rust_decimal::Decimal;")
	}
	if needsSerde {
		lines = append(lines, "use serde::{Deserialize, Serialize};")
	}
	if needsSerdeJSON {
		_ = needsSerdeJSON // serde_json::Value is used inline
	}
	if needsUuid {
		lines = append(lines, "use uuid::Uuid;")
	}
	lines = append(lines, "use tokio_postgres::{Client, Error};")

	return strings.Join(lines, "\n") + "\n"
}

func makeRustPKParams(t Table) string {
	colMap := map[string]Column{}
	for _, c := range t.Columns {
		colMap[c.Name] = c
	}
	parts := make([]string, len(t.PrimaryKey))
	for i, pk := range t.PrimaryKey {
		c := colMap[pk]
		c.NotNull = true
		rustT := rustType(c)
		if rustT == "String" {
			rustT = "&str"
		}
		parts[i] = fmt.Sprintf("%s: %s", ToSnakeCase(pk), rustT)
	}
	return strings.Join(parts, ", ")
}

func makeRustPKWhere(t Table, startIdx int) string {
	parts := make([]string, len(t.PrimaryKey))
	for i, pk := range t.PrimaryKey {
		parts[i] = fmt.Sprintf("%s = $%d", pk, startIdx+i)
	}
	return strings.Join(parts, " AND ")
}

func makeRustPKArgs(t Table) string {
	parts := make([]string, len(t.PrimaryKey))
	for i, pk := range t.PrimaryKey {
		parts[i] = "&" + ToSnakeCase(pk)
	}
	return strings.Join(parts, ", ")
}
