package codegen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type TypeScriptGenerator struct{}

func (g *TypeScriptGenerator) Name() string { return "typescript" }

func (g *TypeScriptGenerator) Generate(schemas map[string]DSQLComponent, outDir string) error {
	for _, comp := range schemas {
		for _, s := range comp.Schemas {
			code := generateTypeScript(s)
			path := filepath.Join(outDir, ToSnakeCase(s.Name)+".ts")
			if err := os.WriteFile(path, []byte(code), 0o644); err != nil {
				return fmt.Errorf("writing %s: %w", path, err)
			}
		}
	}

	idx := generateTypeScriptIndex(schemas)
	path := filepath.Join(outDir, "index.ts")
	return os.WriteFile(path, []byte(idx), 0o644)
}

func generateTypeScript(s Schema) string {
	var b strings.Builder
	b.WriteString("// generated by anvil generate — do not edit\n")
	b.WriteString("import { Client } from 'pg';\n\n")

	for _, t := range s.Tables {
		writeTypeScriptTypes(&b, s.Name, t)
		b.WriteString("\n")
	}

	writeTypeScriptMetadata(&b, s)
	b.WriteString("\n")
	writeTypeScriptQueries(&b, s)

	return b.String()
}

func writeTypeScriptTypes(b *strings.Builder, schemaName string, t Table) {
	row := ToPascalCase(t.Name) + "Row"
	ins := ToPascalCase(t.Name) + "Insert"
	upd := ToPascalCase(t.Name) + "Update"

	pkSet := map[string]bool{}
	for _, pk := range t.PrimaryKey {
		pkSet[pk] = true
	}

	hasDefaultSet := map[string]bool{}
	for _, c := range t.Columns {
		if c.Default != "" {
			hasDefaultSet[c.Name] = true
		}
	}

	// Row type
	fmt.Fprintf(b, "export interface %s {\n", row)
	for _, c := range t.Columns {
		tsType := tsType(c)
		fmt.Fprintf(b, "  %s: %s;\n", c.Name, tsType)
	}
	b.WriteString("}\n\n")

	// Insert type — PK columns required, columns with defaults optional
	fmt.Fprintf(b, "export interface %s {\n", ins)
	for _, c := range t.Columns {
		tsType := tsType(c)
		optional := ""
		if !pkSet[c.Name] && (hasDefaultSet[c.Name] || !c.NotNull) {
			optional = "?"
		}
		fmt.Fprintf(b, "  %s%s: %s;\n", c.Name, optional, tsType)
	}
	b.WriteString("}\n\n")

	// Update type — all optional
	fmt.Fprintf(b, "export interface %s {\n", upd)
	for _, c := range t.Columns {
		tsType := tsType(c)
		fmt.Fprintf(b, "  %s?: %s;\n", c.Name, tsType)
	}
	b.WriteString("}\n")
}

func writeTypeScriptMetadata(b *strings.Builder, s Schema) {
	b.WriteString("export const tables = {\n")
	for i, t := range s.Tables {
		fmt.Fprintf(b, "  %s: {\n", t.Name)
		fmt.Fprintf(b, "    schema: %q,\n", s.Name)
		fmt.Fprintf(b, "    name: %q,\n", t.Name)

		pks := make([]string, len(t.PrimaryKey))
		for j, pk := range t.PrimaryKey {
			pks[j] = fmt.Sprintf("%q", pk)
		}
		fmt.Fprintf(b, "    primaryKey: [%s] as const,\n", strings.Join(pks, ", "))

		b.WriteString("    columns: {\n")
		for _, c := range t.Columns {
			fmt.Fprintf(b, "      %s: %q,\n", c.Name, c.Type)
		}
		b.WriteString("    } as const,\n")
		b.WriteString("  }")
		if i < len(s.Tables)-1 {
			b.WriteString(",")
		}
		b.WriteString("\n")
	}
	b.WriteString("} as const;\n")
}

func writeTypeScriptQueries(b *strings.Builder, s Schema) {
	funcName := "create" + ToPascalCase(s.Name) + "Queries"
	fmt.Fprintf(b, "export function %s(client: Client) {\n", funcName)
	b.WriteString("  return {\n")

	for ti, t := range s.Tables {
		row := ToPascalCase(t.Name) + "Row"
		ins := ToPascalCase(t.Name) + "Insert"
		upd := ToPascalCase(t.Name) + "Update"
		qualifiedTable := s.Name + "." + t.Name

		colNames := make([]string, len(t.Columns))
		for i, c := range t.Columns {
			colNames[i] = c.Name
		}
		selectCols := strings.Join(colNames, ", ")

		fmt.Fprintf(b, "    %s: {\n", t.Name)

		// findById — uses the primary key
		writeTSFindById(b, t, row, qualifiedTable, selectCols)

		// findMany
		writeTSFindMany(b, row, qualifiedTable, selectCols)

		// insert
		writeTSInsert(b, ins, row, qualifiedTable)

		// update
		writeTSUpdate(b, t, upd, row, qualifiedTable)

		// delete
		writeTSDelete(b, t, qualifiedTable)

		b.WriteString("    }")
		if ti < len(s.Tables)-1 {
			b.WriteString(",")
		}
		b.WriteString("\n")
	}

	b.WriteString("  };\n")
	b.WriteString("}\n")
}

func writeTSFindById(b *strings.Builder, t Table, row, qualifiedTable, selectCols string) {
	pkParams := makeTSPKParams(t)
	pkWhere := makeTSPKWhere(t, 1)
	pkArgs := makeTSPKArgs(t)

	fmt.Fprintf(b, "      findById: async (%s): Promise<%s | null> => {\n", pkParams, row)
	fmt.Fprintf(b, "        const r = await client.query<%s>(\n", row)
	fmt.Fprintf(b, "          'SELECT %s FROM %s WHERE %s',\n", selectCols, qualifiedTable, pkWhere)
	fmt.Fprintf(b, "          [%s],\n", pkArgs)
	b.WriteString("        );\n")
	b.WriteString("        return r.rows[0] ?? null;\n")
	b.WriteString("      },\n\n")
}

func writeTSFindMany(b *strings.Builder, row, qualifiedTable, selectCols string) {
	fmt.Fprintf(b, "      findMany: async (): Promise<%s[]> => {\n", row)
	fmt.Fprintf(b, "        const r = await client.query<%s>(\n", row)
	fmt.Fprintf(b, "          'SELECT %s FROM %s',\n", selectCols, qualifiedTable)
	b.WriteString("        );\n")
	b.WriteString("        return r.rows;\n")
	b.WriteString("      },\n\n")
}

func writeTSInsert(b *strings.Builder, ins, row, qualifiedTable string) {
	fmt.Fprintf(b, "      insert: async (row: %s): Promise<%s> => {\n", ins, row)
	b.WriteString("        const data = row as unknown as Record<string, unknown>;\n")
	b.WriteString("        const cols = Object.keys(data).filter(k => data[k] !== undefined);\n")
	b.WriteString("        const vals = cols.map(k => data[k]);\n")
	b.WriteString("        const placeholders = cols.map((_, i) => `$${i + 1}`).join(', ');\n")
	fmt.Fprintf(b, "        const r = await client.query<%s>(\n", row)
	fmt.Fprintf(b, "          `INSERT INTO %s (${cols.join(', ')}) VALUES (${placeholders}) RETURNING *`,\n", qualifiedTable)
	b.WriteString("          vals,\n")
	b.WriteString("        );\n")
	b.WriteString("        return r.rows[0];\n")
	b.WriteString("      },\n\n")
}

func writeTSUpdate(b *strings.Builder, t Table, upd, row, qualifiedTable string) {
	pkParams := makeTSPKParams(t)
	pkArgs := makeTSPKArgs(t)
	pkOffset := len(t.PrimaryKey)

	fmt.Fprintf(b, "      update: async (%s, set: %s): Promise<%s | null> => {\n", pkParams, upd, row)
	b.WriteString("        const entries = Object.entries(set).filter(([, v]) => v !== undefined);\n")
	b.WriteString("        if (entries.length === 0) return null;\n")
	fmt.Fprintf(b, "        const setClauses = entries.map(([k], i) => `${k} = $${i + %d}`).join(', ');\n", pkOffset+1)

	whereParts := make([]string, len(t.PrimaryKey))
	for i, pk := range t.PrimaryKey {
		whereParts[i] = fmt.Sprintf("%s = $%d", pk, i+1)
	}
	where := strings.Join(whereParts, " AND ")

	fmt.Fprintf(b, "        const r = await client.query<%s>(\n", row)
	fmt.Fprintf(b, "          `UPDATE %s SET ${setClauses} WHERE %s RETURNING *`,\n", qualifiedTable, where)
	fmt.Fprintf(b, "          [%s, ...entries.map(([, v]) => v)],\n", pkArgs)
	b.WriteString("        );\n")
	b.WriteString("        return r.rows[0] ?? null;\n")
	b.WriteString("      },\n\n")
}

func writeTSDelete(b *strings.Builder, t Table, qualifiedTable string) {
	pkParams := makeTSPKParams(t)
	pkWhere := makeTSPKWhere(t, 1)
	pkArgs := makeTSPKArgs(t)

	fmt.Fprintf(b, "      delete: async (%s): Promise<boolean> => {\n", pkParams)
	fmt.Fprintf(b, "        const r = await client.query(\n")
	fmt.Fprintf(b, "          'DELETE FROM %s WHERE %s',\n", qualifiedTable, pkWhere)
	fmt.Fprintf(b, "          [%s],\n", pkArgs)
	b.WriteString("        );\n")
	b.WriteString("        return (r.rowCount ?? 0) > 0;\n")
	b.WriteString("      },\n")
}

func generateTypeScriptIndex(schemas map[string]DSQLComponent) string {
	var b strings.Builder
	b.WriteString("// generated by anvil generate — do not edit\n\n")

	for _, comp := range schemas {
		for _, s := range comp.Schemas {
			file := ToSnakeCase(s.Name)
			b.WriteString(fmt.Sprintf("export * from './%s';\n", file))
		}
	}
	return b.String()
}

// Helpers

func tsType(c Column) string {
	m, ok := typeMappings[c.Type]
	if !ok {
		return "unknown"
	}
	base := m.TypeScript
	if !c.NotNull {
		return base + " | null"
	}
	return base
}

func makeTSPKParams(t Table) string {
	colMap := map[string]Column{}
	for _, c := range t.Columns {
		colMap[c.Name] = c
	}
	parts := make([]string, len(t.PrimaryKey))
	for i, pk := range t.PrimaryKey {
		c := colMap[pk]
		c.NotNull = true
		parts[i] = fmt.Sprintf("%s: %s", pk, tsType(c))
	}
	return strings.Join(parts, ", ")
}

func makeTSPKWhere(t Table, startIdx int) string {
	parts := make([]string, len(t.PrimaryKey))
	for i, pk := range t.PrimaryKey {
		parts[i] = fmt.Sprintf("%s = $%d", pk, startIdx+i)
	}
	return strings.Join(parts, " AND ")
}

func makeTSPKArgs(t Table) string {
	return strings.Join(t.PrimaryKey, ", ")
}
