package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"
	"time"
)

// Runs from provider/ directory (cd provider && go run ../scripts/registry/generate_registry.go)

const moduleName = "github.com/DamienPace15/anvil/provider"

type Component struct {
	ImportPath  string
	PackageName string
	StructName  string
	Constructor string
	Alias       string
}

var mainTemplate = template.Must(template.New("main.go").Parse(`// Code generated by scripts/registry/generate_registry.go — DO NOT EDIT.
package main

import (
	"context"
	"fmt"
	"os"

	"github.com/pulumi/pulumi-go-provider/infer"
{{- range .Components }}
	{{ .Alias }} "{{ .ImportPath }}"
{{- end }}
)

func main() {
	p, err := infer.NewProviderBuilder().
		WithComponents(
{{- range .Components }}
			infer.ComponentF({{ .Alias }}.{{ .Constructor }}),
{{- end }}
		).
		Build()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	p.Run(context.Background(), "anvil", "0.0.1")
}
`))

func main() {
	fmt.Println("🔧 Starting Registry Generator...")
	start := time.Now()

	outputPath := filepath.Join("cmd", "anvil", "main.go")

	var components []Component

	// Read current directory (provider/) for cloud provider folders
	entries, err := os.ReadDir(".")
	if err != nil {
		log.Fatalf("❌ Could not read current directory: %v", err)
	}

	skip := map[string]bool{"cmd": true, "scripts": true, "sdk": true, "internal": true}

	for _, entry := range entries {
		if !entry.IsDir() || skip[entry.Name()] {
			continue
		}

		providerName := entry.Name()
		resources, err := os.ReadDir(providerName)
		if err != nil {
			continue
		}

		for _, res := range resources {
			if !res.IsDir() {
				continue
			}

			resourceName := res.Name()

			// Verify a .go file exists in this folder
			goFiles, _ := filepath.Glob(filepath.Join(providerName, resourceName, "*.go"))
			if len(goFiles) == 0 {
				continue
			}

			constructor, err := findConstructor(filepath.Join(providerName, resourceName))
			if err != nil {
				fmt.Printf("   ⚠️  Skipping %s/%s: %v\n", providerName, resourceName, err)
				continue
			}

			comp := Component{
				ImportPath:  fmt.Sprintf("%s/%s/%s", moduleName, providerName, resourceName),
				PackageName: resourceName,
				StructName:  strings.TrimPrefix(constructor, "New"),
				Constructor: constructor,
				Alias:       providerName + resourceName,
			}

			components = append(components, comp)
			fmt.Printf("   📦 %s/%s -> %s.%s\n", providerName, resourceName, comp.Alias, comp.Constructor)
		}
	}

	if len(components) == 0 {
		log.Fatal("❌ No components found. Check that <cloud>/<resource>/*.go files exist.")
	}

	if err := os.MkdirAll(filepath.Dir(outputPath), 0755); err != nil {
		log.Fatalf("❌ Could not create output directory: %v", err)
	}

	f, err := os.Create(outputPath)
	if err != nil {
		log.Fatalf("❌ Could not create %s: %v", outputPath, err)
	}
	defer f.Close()

	if err := mainTemplate.Execute(f, map[string]interface{}{
		"Components": components,
	}); err != nil {
		log.Fatalf("❌ Template error: %v", err)
	}

	fmt.Printf("✅ Generated %s with %d components in %v\n", outputPath, len(components), time.Since(start))
}

func toPascalCase(s string) string {
	parts := regexp.MustCompile(`[-_]`).Split(s, -1)
	var result string
	for _, p := range parts {
		if len(p) > 0 {
			result += strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return result
}

// findConstructor scans Go files in a directory for a function
// matching the pattern NewXxx(...) that returns a pointer and error.
// This is the Pulumi component constructor convention.
func findConstructor(dir string) (string, error) {
	goFiles, _ := filepath.Glob(filepath.Join(dir, "*.go"))

	re := regexp.MustCompile(`func (New[A-Z]\w*)\(`)

	for _, f := range goFiles {
		// Skip test files.
		if strings.HasSuffix(f, "_test.go") {
			continue
		}

		data, err := os.ReadFile(f)
		if err != nil {
			continue
		}

		matches := re.FindSubmatch(data)
		if len(matches) >= 2 {
			return string(matches[1]), nil
		}
	}

	// Fallback to the old behaviour.
	base := filepath.Base(dir)
	return "New" + toPascalCase(base), nil
}
