// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// Export sub-modules:
import * as aws from "./aws";

export {
    aws,
};

export const ComplianceFramework = {
    /**
     * SOC 2 Type II
     */
    Soc2: "soc2",
    /**
     * ISO/IEC 27001
     */
    Iso27001: "iso27001",
    /**
     * CIS AWS Foundations Benchmark
     */
    Cis: "cis",
    /**
     * PCI DSS
     */
    Pci_dss: "pci-dss",
    /**
     * HIPAA
     */
    Hipaa: "hipaa",
    /**
     * FedRAMP
     */
    Fedramp: "fedramp",
    /**
     * HITRUST CSF
     */
    Hitrust: "hitrust",
    /**
     * GDPR
     */
    Gdpr: "gdpr",
    /**
     * SOC 1 Type II
     */
    Soc1: "soc1",
    /**
     * IRAP (Australian Government)
     */
    Irap: "irap",
    /**
     * NIST Cybersecurity Framework
     */
    Nist_csf: "nist-csf",
    /**
     * CSA STAR
     */
    Csa_star: "csa-star",
} as const;

export type ComplianceFramework = (typeof ComplianceFramework)[keyof typeof ComplianceFramework];
