// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

import * as pulumiGcp from "@pulumi/gcp";

export class Function extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'anvil:gcp:Function';

    /**
     * Returns true if the given object is an instance of Function.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Function {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Function.__pulumiType;
    }


    /**
     * Create a Function resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: FunctionArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.entryPoint === undefined && !opts.urn) {
                throw new Error("Missing required property 'entryPoint'");
            }
            if (args?.location === undefined && !opts.urn) {
                throw new Error("Missing required property 'location'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.runtime === undefined && !opts.urn) {
                throw new Error("Missing required property 'runtime'");
            }
            resourceInputs["entryPoint"] = args?.entryPoint;
            resourceInputs["location"] = args?.location;
            resourceInputs["name"] = args?.name;
            resourceInputs["runtime"] = args?.runtime;
            resourceInputs["transform"] = args?.transform;
        } else {
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Function.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a Function resource.
 */
export interface FunctionArgs {
    /**
     * The name of the function to execute.
     */
    entryPoint: pulumi.Input<string>;
    /**
     * The GCP region to deploy to (e.g. us-central1).
     */
    location: pulumi.Input<string>;
    /**
     * The name of the Cloud Function.
     */
    name: pulumi.Input<string>;
    /**
     * The runtime to use (e.g. nodejs20, python312, go122).
     */
    runtime: pulumi.Input<string>;
    transform?: pulumi.Input<inputs.gcp.FunctionTransformArgsArgs>;
}
