// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * SvelteKitSite is an Anvil-managed SvelteKit deployment on GCP. Static assets go to Cloud Storage behind Cloud CDN. Server code runs on Cloud Run.
 */
export class SvelteKitSite extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'anvil:gcp:SvelteKitSite';

    /**
     * Returns true if the given object is an instance of SvelteKitSite.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SvelteKitSite {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SvelteKitSite.__pulumiType;
    }

    /**
     * The Cloud Storage bucket name storing static assets.
     */
    declare public /*out*/ readonly bucketName: pulumi.Output<string | undefined>;
    /**
     * The Cloud Run service URL.
     */
    declare public /*out*/ readonly cloudRunUrl: pulumi.Output<string | undefined>;
    /**
     * The URL where the site is accessible.
     */
    declare public /*out*/ readonly url: pulumi.Output<string | undefined>;

    /**
     * Create a SvelteKitSite resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SvelteKitSiteArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.path === undefined && !opts.urn) {
                throw new Error("Missing required property 'path'");
            }
            resourceInputs["domain"] = args?.domain;
            resourceInputs["environment"] = args?.environment;
            resourceInputs["minInstances"] = args?.minInstances;
            resourceInputs["path"] = args?.path;
            resourceInputs["bucketName"] = undefined /*out*/;
            resourceInputs["cloudRunUrl"] = undefined /*out*/;
            resourceInputs["url"] = undefined /*out*/;
        } else {
            resourceInputs["bucketName"] = undefined /*out*/;
            resourceInputs["cloudRunUrl"] = undefined /*out*/;
            resourceInputs["url"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SvelteKitSite.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a SvelteKitSite resource.
 */
export interface SvelteKitSiteArgs {
    /**
     * Custom domain name for the site. When set, Anvil configures DNS and TLS certificates automatically.
     */
    domain?: pulumi.Input<string>;
    /**
     * Environment variables injected at both build time and runtime. Build time: available via $env/static and import.meta.env during static generation and prerendering. Runtime: set on the compute service (Lambda/Cloud Run) for SSR and API routes via $env/dynamic.
     */
    environment?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Minimum number of Cloud Run instances to keep warm. Set to 1 or higher to eliminate cold starts. Defaults to 0.
     */
    minInstances?: pulumi.Input<number>;
    /**
     * Path to the SvelteKit project directory, relative to the project root (where anvil.yaml lives). Not relative to the anvil.config file.
     */
    path: pulumi.Input<string>;
}
