// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const LambdaArchitecture = {
    /**
     * Graviton — 20% cheaper, better performance. Default.
     */
    Arm64: "arm64",
    /**
     * Intel/AMD — use for x86-specific native dependencies.
     */
    X86_64: "x86_64",
} as const;

export type LambdaArchitecture = (typeof LambdaArchitecture)[keyof typeof LambdaArchitecture];

export const LambdaLogRetention = {
    /**
     * 7 days
     */
    LambdaLogRetention_7d: "7d",
    /**
     * 30 days (1 month)
     */
    LambdaLogRetention_30d: "30d",
    /**
     * 90 days (3 months)
     */
    LambdaLogRetention_90d: "90d",
    /**
     * 1 year (365 days) — SOC 2 / ISO 27001 / PCI-DSS baseline. Default.
     */
    LambdaLogRetention_1y: "1y",
    /**
     * 3 years (1095 days) — FedRAMP minimum
     */
    LambdaLogRetention_3y: "3y",
    /**
     * 6 years (2190 days) — HIPAA minimum
     */
    LambdaLogRetention_6y: "6y",
    /**
     * 7 years (2555 days) — IRAP minimum
     */
    LambdaLogRetention_7y: "7y",
} as const;

export type LambdaLogRetention = (typeof LambdaLogRetention)[keyof typeof LambdaLogRetention];

export const LambdaRuntime = {
    /**
     * Node.js 24 (LTS) — recommended
     */
    Nodejs24_x: "nodejs24.x",
    /**
     * Node.js 22 (LTS)
     */
    Nodejs22_x: "nodejs22.x",
} as const;

export type LambdaRuntime = (typeof LambdaRuntime)[keyof typeof LambdaRuntime];

export const VpcNatType = {
    /**
     * AWS managed NAT Gateway. One per AZ for true HA. ~$32/month per AZ plus $0.045/GB data processed.
     */
    Gateway: "gateway",
    /**
     * fck-nat EC2 instance. Single instance regardless of AZ count. ~$4-6/month for t4g.small. Accepted single point of failure tradeoff for cost savings.
     */
    Fck_nat: "fck-nat",
} as const;

export type VpcNatType = (typeof VpcNatType)[keyof typeof VpcNatType];
