// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package aws

import (
	"context"
	"reflect"

	"github.com/DamienPace15/anvil/sdk/go/anvil/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// An Anvil-managed Cognito user pool. Tier 1 controls (deletion protection, enforced password policy, account recovery via email) are always on. Pair with CognitoAuth to protect API Gateway routes.
type CognitoUserPool struct {
	pulumi.ResourceState

	// The ID of the default app client. Pass to CognitoAuth audience.
	AppClientId pulumi.StringOutput `pulumi:"appClientId"`
	// The client secret of the default app client. Only populated when appClient.generateSecret is true. Treat as sensitive.
	AppClientSecret pulumi.StringPtrOutput `pulumi:"appClientSecret"`
	// The CloudFront distribution domain for the custom hosted UI. Only populated when hostedUi.customDomain is true. Create a Route53 alias record pointing hostedUi.domain to this value to complete DNS setup. Empty string for Cognito-managed domains.
	CloudFrontDomain pulumi.StringOutput `pulumi:"cloudFrontDomain"`
	// The Cognito OIDC issuer URL. Format: https://cognito-idp.{region}.amazonaws.com/{userPoolId}. Pass directly to CognitoAuth if building the authorizer manually.
	Endpoint pulumi.StringOutput `pulumi:"endpoint"`
	// The full hosted UI domain (e.g. https://auth.myapp.com or https://myprefix.auth.us-east-1.amazoncognito.com). Empty string if hostedUi is not configured.
	HostedUiDomain pulumi.StringOutput `pulumi:"hostedUiDomain"`
	// The ARN of the Cognito user pool.
	UserPoolArn pulumi.StringOutput `pulumi:"userPoolArn"`
	// The Cognito user pool ID. Pass to CognitoAuth.userPoolId.
	UserPoolId pulumi.StringOutput `pulumi:"userPoolId"`
}

// NewCognitoUserPool registers a new resource with the given unique name, arguments, and options.
func NewCognitoUserPool(ctx *pulumi.Context,
	name string, args *CognitoUserPoolArgs, opts ...pulumi.ResourceOption) (*CognitoUserPool, error) {
	if args == nil {
		args = &CognitoUserPoolArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource CognitoUserPool
	err := ctx.RegisterRemoteComponentResource("anvil:aws:CognitoUserPool", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type cognitoUserPoolArgs struct {
	// Default app client created with the user pool. Covers the 80% case of one application per pool. Use transform for additional clients.
	AppClient *CognitoUserPoolAppClient `pulumi:"appClient"`
	// User attribute configuration. Controls sign-in identifiers and required attributes on sign-up.
	Attributes *CognitoUserPoolAttributes `pulumi:"attributes"`
	// Email delivery configuration. Default: Cognito-managed email (5 emails/day limit). Set sesFromAddress for SES delivery in production.
	EmailConfiguration *CognitoUserPoolEmailConfiguration `pulumi:"emailConfiguration"`
	// Hosted UI / Managed Login configuration. Omit to use the Cognito user pools API directly without a hosted sign-in page.
	HostedUi *CognitoUserPoolHostedUi `pulumi:"hostedUi"`
	// External identity providers to federate with this user pool. Supports Google, Facebook, LoginWithAmazon, SignInWithApple, OIDC, and SAML. Schema never changes per provider — add new providers by extending this array.
	IdentityProviders []CognitoUserPoolIdentityProvider `pulumi:"identityProviders"`
	// MFA configuration. TOTP requires no additional AWS resources. SMS requires an SNS caller ARN.
	Mfa *CognitoUserPoolMfa `pulumi:"mfa"`
	// Password policy for the user pool. Anvil enforces a secure baseline by default — override only to strengthen.
	PasswordPolicy *CognitoUserPoolPasswordPolicy `pulumi:"passwordPolicy"`
	Transform      *CognitoUserPoolTransformArgs  `pulumi:"transform"`
}

// The set of arguments for constructing a CognitoUserPool resource.
type CognitoUserPoolArgs struct {
	// Default app client created with the user pool. Covers the 80% case of one application per pool. Use transform for additional clients.
	AppClient CognitoUserPoolAppClientPtrInput
	// User attribute configuration. Controls sign-in identifiers and required attributes on sign-up.
	Attributes CognitoUserPoolAttributesPtrInput
	// Email delivery configuration. Default: Cognito-managed email (5 emails/day limit). Set sesFromAddress for SES delivery in production.
	EmailConfiguration CognitoUserPoolEmailConfigurationPtrInput
	// Hosted UI / Managed Login configuration. Omit to use the Cognito user pools API directly without a hosted sign-in page.
	HostedUi CognitoUserPoolHostedUiPtrInput
	// External identity providers to federate with this user pool. Supports Google, Facebook, LoginWithAmazon, SignInWithApple, OIDC, and SAML. Schema never changes per provider — add new providers by extending this array.
	IdentityProviders CognitoUserPoolIdentityProviderArrayInput
	// MFA configuration. TOTP requires no additional AWS resources. SMS requires an SNS caller ARN.
	Mfa CognitoUserPoolMfaPtrInput
	// Password policy for the user pool. Anvil enforces a secure baseline by default — override only to strengthen.
	PasswordPolicy CognitoUserPoolPasswordPolicyPtrInput
	Transform      CognitoUserPoolTransformArgsPtrInput
}

func (CognitoUserPoolArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*cognitoUserPoolArgs)(nil)).Elem()
}

type CognitoUserPoolInput interface {
	pulumi.Input

	ToCognitoUserPoolOutput() CognitoUserPoolOutput
	ToCognitoUserPoolOutputWithContext(ctx context.Context) CognitoUserPoolOutput
}

func (*CognitoUserPool) ElementType() reflect.Type {
	return reflect.TypeOf((**CognitoUserPool)(nil)).Elem()
}

func (i *CognitoUserPool) ToCognitoUserPoolOutput() CognitoUserPoolOutput {
	return i.ToCognitoUserPoolOutputWithContext(context.Background())
}

func (i *CognitoUserPool) ToCognitoUserPoolOutputWithContext(ctx context.Context) CognitoUserPoolOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CognitoUserPoolOutput)
}

// CognitoUserPoolArrayInput is an input type that accepts CognitoUserPoolArray and CognitoUserPoolArrayOutput values.
// You can construct a concrete instance of `CognitoUserPoolArrayInput` via:
//
//	CognitoUserPoolArray{ CognitoUserPoolArgs{...} }
type CognitoUserPoolArrayInput interface {
	pulumi.Input

	ToCognitoUserPoolArrayOutput() CognitoUserPoolArrayOutput
	ToCognitoUserPoolArrayOutputWithContext(context.Context) CognitoUserPoolArrayOutput
}

type CognitoUserPoolArray []CognitoUserPoolInput

func (CognitoUserPoolArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CognitoUserPool)(nil)).Elem()
}

func (i CognitoUserPoolArray) ToCognitoUserPoolArrayOutput() CognitoUserPoolArrayOutput {
	return i.ToCognitoUserPoolArrayOutputWithContext(context.Background())
}

func (i CognitoUserPoolArray) ToCognitoUserPoolArrayOutputWithContext(ctx context.Context) CognitoUserPoolArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CognitoUserPoolArrayOutput)
}

// CognitoUserPoolMapInput is an input type that accepts CognitoUserPoolMap and CognitoUserPoolMapOutput values.
// You can construct a concrete instance of `CognitoUserPoolMapInput` via:
//
//	CognitoUserPoolMap{ "key": CognitoUserPoolArgs{...} }
type CognitoUserPoolMapInput interface {
	pulumi.Input

	ToCognitoUserPoolMapOutput() CognitoUserPoolMapOutput
	ToCognitoUserPoolMapOutputWithContext(context.Context) CognitoUserPoolMapOutput
}

type CognitoUserPoolMap map[string]CognitoUserPoolInput

func (CognitoUserPoolMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CognitoUserPool)(nil)).Elem()
}

func (i CognitoUserPoolMap) ToCognitoUserPoolMapOutput() CognitoUserPoolMapOutput {
	return i.ToCognitoUserPoolMapOutputWithContext(context.Background())
}

func (i CognitoUserPoolMap) ToCognitoUserPoolMapOutputWithContext(ctx context.Context) CognitoUserPoolMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CognitoUserPoolMapOutput)
}

type CognitoUserPoolOutput struct{ *pulumi.OutputState }

func (CognitoUserPoolOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CognitoUserPool)(nil)).Elem()
}

func (o CognitoUserPoolOutput) ToCognitoUserPoolOutput() CognitoUserPoolOutput {
	return o
}

func (o CognitoUserPoolOutput) ToCognitoUserPoolOutputWithContext(ctx context.Context) CognitoUserPoolOutput {
	return o
}

// The ID of the default app client. Pass to CognitoAuth audience.
func (o CognitoUserPoolOutput) AppClientId() pulumi.StringOutput {
	return o.ApplyT(func(v *CognitoUserPool) pulumi.StringOutput { return v.AppClientId }).(pulumi.StringOutput)
}

// The client secret of the default app client. Only populated when appClient.generateSecret is true. Treat as sensitive.
func (o CognitoUserPoolOutput) AppClientSecret() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CognitoUserPool) pulumi.StringPtrOutput { return v.AppClientSecret }).(pulumi.StringPtrOutput)
}

// The CloudFront distribution domain for the custom hosted UI. Only populated when hostedUi.customDomain is true. Create a Route53 alias record pointing hostedUi.domain to this value to complete DNS setup. Empty string for Cognito-managed domains.
func (o CognitoUserPoolOutput) CloudFrontDomain() pulumi.StringOutput {
	return o.ApplyT(func(v *CognitoUserPool) pulumi.StringOutput { return v.CloudFrontDomain }).(pulumi.StringOutput)
}

// The Cognito OIDC issuer URL. Format: https://cognito-idp.{region}.amazonaws.com/{userPoolId}. Pass directly to CognitoAuth if building the authorizer manually.
func (o CognitoUserPoolOutput) Endpoint() pulumi.StringOutput {
	return o.ApplyT(func(v *CognitoUserPool) pulumi.StringOutput { return v.Endpoint }).(pulumi.StringOutput)
}

// The full hosted UI domain (e.g. https://auth.myapp.com or https://myprefix.auth.us-east-1.amazoncognito.com). Empty string if hostedUi is not configured.
func (o CognitoUserPoolOutput) HostedUiDomain() pulumi.StringOutput {
	return o.ApplyT(func(v *CognitoUserPool) pulumi.StringOutput { return v.HostedUiDomain }).(pulumi.StringOutput)
}

// The ARN of the Cognito user pool.
func (o CognitoUserPoolOutput) UserPoolArn() pulumi.StringOutput {
	return o.ApplyT(func(v *CognitoUserPool) pulumi.StringOutput { return v.UserPoolArn }).(pulumi.StringOutput)
}

// The Cognito user pool ID. Pass to CognitoAuth.userPoolId.
func (o CognitoUserPoolOutput) UserPoolId() pulumi.StringOutput {
	return o.ApplyT(func(v *CognitoUserPool) pulumi.StringOutput { return v.UserPoolId }).(pulumi.StringOutput)
}

type CognitoUserPoolArrayOutput struct{ *pulumi.OutputState }

func (CognitoUserPoolArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CognitoUserPool)(nil)).Elem()
}

func (o CognitoUserPoolArrayOutput) ToCognitoUserPoolArrayOutput() CognitoUserPoolArrayOutput {
	return o
}

func (o CognitoUserPoolArrayOutput) ToCognitoUserPoolArrayOutputWithContext(ctx context.Context) CognitoUserPoolArrayOutput {
	return o
}

func (o CognitoUserPoolArrayOutput) Index(i pulumi.IntInput) CognitoUserPoolOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *CognitoUserPool {
		return vs[0].([]*CognitoUserPool)[vs[1].(int)]
	}).(CognitoUserPoolOutput)
}

type CognitoUserPoolMapOutput struct{ *pulumi.OutputState }

func (CognitoUserPoolMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CognitoUserPool)(nil)).Elem()
}

func (o CognitoUserPoolMapOutput) ToCognitoUserPoolMapOutput() CognitoUserPoolMapOutput {
	return o
}

func (o CognitoUserPoolMapOutput) ToCognitoUserPoolMapOutputWithContext(ctx context.Context) CognitoUserPoolMapOutput {
	return o
}

func (o CognitoUserPoolMapOutput) MapIndex(k pulumi.StringInput) CognitoUserPoolOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *CognitoUserPool {
		return vs[0].(map[string]*CognitoUserPool)[vs[1].(string)]
	}).(CognitoUserPoolOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CognitoUserPoolInput)(nil)).Elem(), &CognitoUserPool{})
	pulumi.RegisterInputType(reflect.TypeOf((*CognitoUserPoolArrayInput)(nil)).Elem(), CognitoUserPoolArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*CognitoUserPoolMapInput)(nil)).Elem(), CognitoUserPoolMap{})
	pulumi.RegisterOutputType(CognitoUserPoolOutput{})
	pulumi.RegisterOutputType(CognitoUserPoolArrayOutput{})
	pulumi.RegisterOutputType(CognitoUserPoolMapOutput{})
}
