// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package aws

import (
	"context"
	"reflect"

	"errors"
	"github.com/DamienPace15/anvil/sdk/go/anvil/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// An Anvil-managed JWT authorizer backed by a Cognito user pool. Derives the issuer URL automatically from the user pool ID — no manual Cognito endpoint construction required. Creates a native API Gateway JWT authorizer; verification is handled entirely by API Gateway with no Lambda or custom code. Pass authorizerId to HttpApi defaultAuthorizerId to protect your API routes.
type CognitoAuth struct {
	pulumi.ResourceState

	// The API Gateway authorizer ID. Pass this to HttpApi defaultAuthorizerId to protect your API routes.
	AuthorizerId pulumi.StringOutput `pulumi:"authorizerId"`
}

// NewCognitoAuth registers a new resource with the given unique name, arguments, and options.
func NewCognitoAuth(ctx *pulumi.Context,
	name string, args *CognitoAuthArgs, opts ...pulumi.ResourceOption) (*CognitoAuth, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Audience == nil {
		return nil, errors.New("invalid value for required argument 'Audience'")
	}
	if args.UserPoolId == nil {
		return nil, errors.New("invalid value for required argument 'UserPoolId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource CognitoAuth
	err := ctx.RegisterRemoteComponentResource("anvil:aws:CognitoAuth", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type cognitoAuthArgs struct {
	// The Cognito app client IDs allowed to access this API. API Gateway rejects tokens whose 'aud' claim does not match one of these values. Pass your Cognito app client ID(s) here.
	Audience []string `pulumi:"audience"`
	// The Cognito user pool ID. Pass pool.userPoolId directly. Accepts Output<string>. Anvil derives the issuer URL automatically: https://cognito-idp.{region}.amazonaws.com/{userPoolId}.
	UserPoolId interface{} `pulumi:"userPoolId"`
}

// The set of arguments for constructing a CognitoAuth resource.
type CognitoAuthArgs struct {
	// The Cognito app client IDs allowed to access this API. API Gateway rejects tokens whose 'aud' claim does not match one of these values. Pass your Cognito app client ID(s) here.
	Audience pulumi.StringArrayInput
	// The Cognito user pool ID. Pass pool.userPoolId directly. Accepts Output<string>. Anvil derives the issuer URL automatically: https://cognito-idp.{region}.amazonaws.com/{userPoolId}.
	UserPoolId pulumi.Input
}

func (CognitoAuthArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*cognitoAuthArgs)(nil)).Elem()
}

type CognitoAuthInput interface {
	pulumi.Input

	ToCognitoAuthOutput() CognitoAuthOutput
	ToCognitoAuthOutputWithContext(ctx context.Context) CognitoAuthOutput
}

func (*CognitoAuth) ElementType() reflect.Type {
	return reflect.TypeOf((**CognitoAuth)(nil)).Elem()
}

func (i *CognitoAuth) ToCognitoAuthOutput() CognitoAuthOutput {
	return i.ToCognitoAuthOutputWithContext(context.Background())
}

func (i *CognitoAuth) ToCognitoAuthOutputWithContext(ctx context.Context) CognitoAuthOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CognitoAuthOutput)
}

// CognitoAuthArrayInput is an input type that accepts CognitoAuthArray and CognitoAuthArrayOutput values.
// You can construct a concrete instance of `CognitoAuthArrayInput` via:
//
//	CognitoAuthArray{ CognitoAuthArgs{...} }
type CognitoAuthArrayInput interface {
	pulumi.Input

	ToCognitoAuthArrayOutput() CognitoAuthArrayOutput
	ToCognitoAuthArrayOutputWithContext(context.Context) CognitoAuthArrayOutput
}

type CognitoAuthArray []CognitoAuthInput

func (CognitoAuthArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CognitoAuth)(nil)).Elem()
}

func (i CognitoAuthArray) ToCognitoAuthArrayOutput() CognitoAuthArrayOutput {
	return i.ToCognitoAuthArrayOutputWithContext(context.Background())
}

func (i CognitoAuthArray) ToCognitoAuthArrayOutputWithContext(ctx context.Context) CognitoAuthArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CognitoAuthArrayOutput)
}

// CognitoAuthMapInput is an input type that accepts CognitoAuthMap and CognitoAuthMapOutput values.
// You can construct a concrete instance of `CognitoAuthMapInput` via:
//
//	CognitoAuthMap{ "key": CognitoAuthArgs{...} }
type CognitoAuthMapInput interface {
	pulumi.Input

	ToCognitoAuthMapOutput() CognitoAuthMapOutput
	ToCognitoAuthMapOutputWithContext(context.Context) CognitoAuthMapOutput
}

type CognitoAuthMap map[string]CognitoAuthInput

func (CognitoAuthMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CognitoAuth)(nil)).Elem()
}

func (i CognitoAuthMap) ToCognitoAuthMapOutput() CognitoAuthMapOutput {
	return i.ToCognitoAuthMapOutputWithContext(context.Background())
}

func (i CognitoAuthMap) ToCognitoAuthMapOutputWithContext(ctx context.Context) CognitoAuthMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CognitoAuthMapOutput)
}

type CognitoAuthOutput struct{ *pulumi.OutputState }

func (CognitoAuthOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CognitoAuth)(nil)).Elem()
}

func (o CognitoAuthOutput) ToCognitoAuthOutput() CognitoAuthOutput {
	return o
}

func (o CognitoAuthOutput) ToCognitoAuthOutputWithContext(ctx context.Context) CognitoAuthOutput {
	return o
}

// The API Gateway authorizer ID. Pass this to HttpApi defaultAuthorizerId to protect your API routes.
func (o CognitoAuthOutput) AuthorizerId() pulumi.StringOutput {
	return o.ApplyT(func(v *CognitoAuth) pulumi.StringOutput { return v.AuthorizerId }).(pulumi.StringOutput)
}

type CognitoAuthArrayOutput struct{ *pulumi.OutputState }

func (CognitoAuthArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CognitoAuth)(nil)).Elem()
}

func (o CognitoAuthArrayOutput) ToCognitoAuthArrayOutput() CognitoAuthArrayOutput {
	return o
}

func (o CognitoAuthArrayOutput) ToCognitoAuthArrayOutputWithContext(ctx context.Context) CognitoAuthArrayOutput {
	return o
}

func (o CognitoAuthArrayOutput) Index(i pulumi.IntInput) CognitoAuthOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *CognitoAuth {
		return vs[0].([]*CognitoAuth)[vs[1].(int)]
	}).(CognitoAuthOutput)
}

type CognitoAuthMapOutput struct{ *pulumi.OutputState }

func (CognitoAuthMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CognitoAuth)(nil)).Elem()
}

func (o CognitoAuthMapOutput) ToCognitoAuthMapOutput() CognitoAuthMapOutput {
	return o
}

func (o CognitoAuthMapOutput) ToCognitoAuthMapOutputWithContext(ctx context.Context) CognitoAuthMapOutput {
	return o
}

func (o CognitoAuthMapOutput) MapIndex(k pulumi.StringInput) CognitoAuthOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *CognitoAuth {
		return vs[0].(map[string]*CognitoAuth)[vs[1].(string)]
	}).(CognitoAuthOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CognitoAuthInput)(nil)).Elem(), &CognitoAuth{})
	pulumi.RegisterInputType(reflect.TypeOf((*CognitoAuthArrayInput)(nil)).Elem(), CognitoAuthArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*CognitoAuthMapInput)(nil)).Elem(), CognitoAuthMap{})
	pulumi.RegisterOutputType(CognitoAuthOutput{})
	pulumi.RegisterOutputType(CognitoAuthArrayOutput{})
	pulumi.RegisterOutputType(CognitoAuthMapOutput{})
}
