// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package aws

import (
	"context"
	"reflect"

	"github.com/DamienPace15/anvil/sdk/go/anvil/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Serverless distributed PostgreSQL-compatible database. Secure-by-default Aurora DSQL cluster with optional multi-region active-active replication, IAM authentication, deploy-time role bootstrapping, and AWS Backup integration. No VPC required — connect directly via IAM auth tokens.
type DSQL struct {
	pulumi.ResourceState

	// Map of region to cluster ARN. Single-region: one entry. Multi-region: one entry per region. e.g. { "us-east-1": "arn:aws:dsql:us-east-1:..." }.
	ClusterArns pulumi.StringMapOutput `pulumi:"clusterArns"`
	// The single cluster endpoint for the provider's default region. Convenience for the common single-region case — pass straight to a Lambda env var: { DSQL_ENDPOINT: dsql.endpoint }. For multi-region this is the local-region endpoint; use endpoints[region] for another.
	Endpoint pulumi.StringOutput `pulumi:"endpoint"`
	// Map of region to cluster endpoint. Single-region: one entry keyed by the provider region. Multi-region: one entry per region. e.g. { "us-east-1": "abc123.dsql.us-east-1.on.aws" }. Pass the relevant endpoint to your Lambda via environment variables.
	Endpoints pulumi.StringMapOutput `pulumi:"endpoints"`
	// Map of region to VPC endpoint ID. Only populated when vpc is set and hasNat is false. Pass to LambdaVpcEndpointArgs.endpointId.
	VpcEndpointIds pulumi.StringMapOutput `pulumi:"vpcEndpointIds"`
	// Map of region to VPC endpoint security group ID. Only populated when vpc is set and hasNat is false. Pass to LambdaVpcEndpointArgs.securityGroupId so Anvil can wire the egress rule from the Lambda SG to the endpoint SG on port 5432.
	VpcEndpointSecurityGroupIds pulumi.StringMapOutput `pulumi:"vpcEndpointSecurityGroupIds"`
}

// NewDSQL registers a new resource with the given unique name, arguments, and options.
func NewDSQL(ctx *pulumi.Context,
	name string, args *DSQLArgs, opts ...pulumi.ResourceOption) (*DSQL, error) {
	if args == nil {
		args = &DSQLArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DSQL
	err := ctx.RegisterRemoteComponentResource("anvil:aws:DSQL", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type dsqlArgs struct {
	// AWS Backup configuration. Omit to disable. When set, Anvil opts in the DSQL resource type per region, creates a backup plan with retention and schedule, and for multi-region clusters automatically adds cross-region copy rules.
	Backup *DSQLBackupArgs `pulumi:"backup"`
	// Opt-in multi-region configuration. When set, Anvil creates two clusters in the specified regions and links them via ClusterPeering. When omitted, a single-region cluster is created in the provider's default region.
	MultiRegion *DSQLMultiRegionArgs `pulumi:"multiRegion"`
	// Schemas and the tables within them. Anvil creates each schema and table (additive-only — new tables/columns/indexes are applied; removals are left to humans). Omit to skip table management.
	Schemas   []DSQLSchema       `pulumi:"schemas"`
	Transform *DsqlTransformArgs `pulumi:"transform"`
	// Optional VPC configuration. When set without hasNat, Anvil creates interface VPC endpoints (PrivateLink) per region so traffic stays on the AWS backbone. When omitted, the Lambda connects to the public DSQL endpoint over the internet using IAM auth tokens over TLS.
	Vpc *DSQLVpcArgs `pulumi:"vpc"`
}

// The set of arguments for constructing a DSQL resource.
type DSQLArgs struct {
	// AWS Backup configuration. Omit to disable. When set, Anvil opts in the DSQL resource type per region, creates a backup plan with retention and schedule, and for multi-region clusters automatically adds cross-region copy rules.
	Backup DSQLBackupArgsPtrInput
	// Opt-in multi-region configuration. When set, Anvil creates two clusters in the specified regions and links them via ClusterPeering. When omitted, a single-region cluster is created in the provider's default region.
	MultiRegion DSQLMultiRegionArgsPtrInput
	// Schemas and the tables within them. Anvil creates each schema and table (additive-only — new tables/columns/indexes are applied; removals are left to humans). Omit to skip table management.
	Schemas   DSQLSchemaArrayInput
	Transform DsqlTransformArgsPtrInput
	// Optional VPC configuration. When set without hasNat, Anvil creates interface VPC endpoints (PrivateLink) per region so traffic stays on the AWS backbone. When omitted, the Lambda connects to the public DSQL endpoint over the internet using IAM auth tokens over TLS.
	Vpc DSQLVpcArgsPtrInput
}

func (DSQLArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*dsqlArgs)(nil)).Elem()
}

type DSQLInput interface {
	pulumi.Input

	ToDSQLOutput() DSQLOutput
	ToDSQLOutputWithContext(ctx context.Context) DSQLOutput
}

func (*DSQL) ElementType() reflect.Type {
	return reflect.TypeOf((**DSQL)(nil)).Elem()
}

func (i *DSQL) ToDSQLOutput() DSQLOutput {
	return i.ToDSQLOutputWithContext(context.Background())
}

func (i *DSQL) ToDSQLOutputWithContext(ctx context.Context) DSQLOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DSQLOutput)
}

// DSQLArrayInput is an input type that accepts DSQLArray and DSQLArrayOutput values.
// You can construct a concrete instance of `DSQLArrayInput` via:
//
//	DSQLArray{ DSQLArgs{...} }
type DSQLArrayInput interface {
	pulumi.Input

	ToDSQLArrayOutput() DSQLArrayOutput
	ToDSQLArrayOutputWithContext(context.Context) DSQLArrayOutput
}

type DSQLArray []DSQLInput

func (DSQLArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DSQL)(nil)).Elem()
}

func (i DSQLArray) ToDSQLArrayOutput() DSQLArrayOutput {
	return i.ToDSQLArrayOutputWithContext(context.Background())
}

func (i DSQLArray) ToDSQLArrayOutputWithContext(ctx context.Context) DSQLArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DSQLArrayOutput)
}

// DSQLMapInput is an input type that accepts DSQLMap and DSQLMapOutput values.
// You can construct a concrete instance of `DSQLMapInput` via:
//
//	DSQLMap{ "key": DSQLArgs{...} }
type DSQLMapInput interface {
	pulumi.Input

	ToDSQLMapOutput() DSQLMapOutput
	ToDSQLMapOutputWithContext(context.Context) DSQLMapOutput
}

type DSQLMap map[string]DSQLInput

func (DSQLMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DSQL)(nil)).Elem()
}

func (i DSQLMap) ToDSQLMapOutput() DSQLMapOutput {
	return i.ToDSQLMapOutputWithContext(context.Background())
}

func (i DSQLMap) ToDSQLMapOutputWithContext(ctx context.Context) DSQLMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DSQLMapOutput)
}

type DSQLOutput struct{ *pulumi.OutputState }

func (DSQLOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DSQL)(nil)).Elem()
}

func (o DSQLOutput) ToDSQLOutput() DSQLOutput {
	return o
}

func (o DSQLOutput) ToDSQLOutputWithContext(ctx context.Context) DSQLOutput {
	return o
}

// Map of region to cluster ARN. Single-region: one entry. Multi-region: one entry per region. e.g. { "us-east-1": "arn:aws:dsql:us-east-1:..." }.
func (o DSQLOutput) ClusterArns() pulumi.StringMapOutput {
	return o.ApplyT(func(v *DSQL) pulumi.StringMapOutput { return v.ClusterArns }).(pulumi.StringMapOutput)
}

// The single cluster endpoint for the provider's default region. Convenience for the common single-region case — pass straight to a Lambda env var: { DSQL_ENDPOINT: dsql.endpoint }. For multi-region this is the local-region endpoint; use endpoints[region] for another.
func (o DSQLOutput) Endpoint() pulumi.StringOutput {
	return o.ApplyT(func(v *DSQL) pulumi.StringOutput { return v.Endpoint }).(pulumi.StringOutput)
}

// Map of region to cluster endpoint. Single-region: one entry keyed by the provider region. Multi-region: one entry per region. e.g. { "us-east-1": "abc123.dsql.us-east-1.on.aws" }. Pass the relevant endpoint to your Lambda via environment variables.
func (o DSQLOutput) Endpoints() pulumi.StringMapOutput {
	return o.ApplyT(func(v *DSQL) pulumi.StringMapOutput { return v.Endpoints }).(pulumi.StringMapOutput)
}

// Map of region to VPC endpoint ID. Only populated when vpc is set and hasNat is false. Pass to LambdaVpcEndpointArgs.endpointId.
func (o DSQLOutput) VpcEndpointIds() pulumi.StringMapOutput {
	return o.ApplyT(func(v *DSQL) pulumi.StringMapOutput { return v.VpcEndpointIds }).(pulumi.StringMapOutput)
}

// Map of region to VPC endpoint security group ID. Only populated when vpc is set and hasNat is false. Pass to LambdaVpcEndpointArgs.securityGroupId so Anvil can wire the egress rule from the Lambda SG to the endpoint SG on port 5432.
func (o DSQLOutput) VpcEndpointSecurityGroupIds() pulumi.StringMapOutput {
	return o.ApplyT(func(v *DSQL) pulumi.StringMapOutput { return v.VpcEndpointSecurityGroupIds }).(pulumi.StringMapOutput)
}

type DSQLArrayOutput struct{ *pulumi.OutputState }

func (DSQLArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DSQL)(nil)).Elem()
}

func (o DSQLArrayOutput) ToDSQLArrayOutput() DSQLArrayOutput {
	return o
}

func (o DSQLArrayOutput) ToDSQLArrayOutputWithContext(ctx context.Context) DSQLArrayOutput {
	return o
}

func (o DSQLArrayOutput) Index(i pulumi.IntInput) DSQLOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *DSQL {
		return vs[0].([]*DSQL)[vs[1].(int)]
	}).(DSQLOutput)
}

type DSQLMapOutput struct{ *pulumi.OutputState }

func (DSQLMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DSQL)(nil)).Elem()
}

func (o DSQLMapOutput) ToDSQLMapOutput() DSQLMapOutput {
	return o
}

func (o DSQLMapOutput) ToDSQLMapOutputWithContext(ctx context.Context) DSQLMapOutput {
	return o
}

func (o DSQLMapOutput) MapIndex(k pulumi.StringInput) DSQLOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *DSQL {
		return vs[0].(map[string]*DSQL)[vs[1].(string)]
	}).(DSQLOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DSQLInput)(nil)).Elem(), &DSQL{})
	pulumi.RegisterInputType(reflect.TypeOf((*DSQLArrayInput)(nil)).Elem(), DSQLArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DSQLMapInput)(nil)).Elem(), DSQLMap{})
	pulumi.RegisterOutputType(DSQLOutput{})
	pulumi.RegisterOutputType(DSQLArrayOutput{})
	pulumi.RegisterOutputType(DSQLMapOutput{})
}
