// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package aws

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type LambdaArchitecture string

const (
	// Graviton — 20% cheaper, better performance. Default.
	LambdaArchitectureArm64 = LambdaArchitecture("arm64")
	// Intel/AMD — use for x86-specific native dependencies.
	LambdaArchitecture_X86_64 = LambdaArchitecture("x86_64")
)

func (LambdaArchitecture) ElementType() reflect.Type {
	return reflect.TypeOf((*LambdaArchitecture)(nil)).Elem()
}

func (e LambdaArchitecture) ToLambdaArchitectureOutput() LambdaArchitectureOutput {
	return pulumi.ToOutput(e).(LambdaArchitectureOutput)
}

func (e LambdaArchitecture) ToLambdaArchitectureOutputWithContext(ctx context.Context) LambdaArchitectureOutput {
	return pulumi.ToOutputWithContext(ctx, e).(LambdaArchitectureOutput)
}

func (e LambdaArchitecture) ToLambdaArchitecturePtrOutput() LambdaArchitecturePtrOutput {
	return e.ToLambdaArchitecturePtrOutputWithContext(context.Background())
}

func (e LambdaArchitecture) ToLambdaArchitecturePtrOutputWithContext(ctx context.Context) LambdaArchitecturePtrOutput {
	return LambdaArchitecture(e).ToLambdaArchitectureOutputWithContext(ctx).ToLambdaArchitecturePtrOutputWithContext(ctx)
}

func (e LambdaArchitecture) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e LambdaArchitecture) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e LambdaArchitecture) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e LambdaArchitecture) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type LambdaArchitectureOutput struct{ *pulumi.OutputState }

func (LambdaArchitectureOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LambdaArchitecture)(nil)).Elem()
}

func (o LambdaArchitectureOutput) ToLambdaArchitectureOutput() LambdaArchitectureOutput {
	return o
}

func (o LambdaArchitectureOutput) ToLambdaArchitectureOutputWithContext(ctx context.Context) LambdaArchitectureOutput {
	return o
}

func (o LambdaArchitectureOutput) ToLambdaArchitecturePtrOutput() LambdaArchitecturePtrOutput {
	return o.ToLambdaArchitecturePtrOutputWithContext(context.Background())
}

func (o LambdaArchitectureOutput) ToLambdaArchitecturePtrOutputWithContext(ctx context.Context) LambdaArchitecturePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v LambdaArchitecture) *LambdaArchitecture {
		return &v
	}).(LambdaArchitecturePtrOutput)
}

func (o LambdaArchitectureOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o LambdaArchitectureOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e LambdaArchitecture) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o LambdaArchitectureOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o LambdaArchitectureOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e LambdaArchitecture) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type LambdaArchitecturePtrOutput struct{ *pulumi.OutputState }

func (LambdaArchitecturePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**LambdaArchitecture)(nil)).Elem()
}

func (o LambdaArchitecturePtrOutput) ToLambdaArchitecturePtrOutput() LambdaArchitecturePtrOutput {
	return o
}

func (o LambdaArchitecturePtrOutput) ToLambdaArchitecturePtrOutputWithContext(ctx context.Context) LambdaArchitecturePtrOutput {
	return o
}

func (o LambdaArchitecturePtrOutput) Elem() LambdaArchitectureOutput {
	return o.ApplyT(func(v *LambdaArchitecture) LambdaArchitecture {
		if v != nil {
			return *v
		}
		var ret LambdaArchitecture
		return ret
	}).(LambdaArchitectureOutput)
}

func (o LambdaArchitecturePtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o LambdaArchitecturePtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *LambdaArchitecture) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// LambdaArchitectureInput is an input type that accepts values of the LambdaArchitecture enum
// A concrete instance of `LambdaArchitectureInput` can be one of the following:
//
//	LambdaArchitectureArm64
//	LambdaArchitecture_X86_64
type LambdaArchitectureInput interface {
	pulumi.Input

	ToLambdaArchitectureOutput() LambdaArchitectureOutput
	ToLambdaArchitectureOutputWithContext(context.Context) LambdaArchitectureOutput
}

var lambdaArchitecturePtrType = reflect.TypeOf((**LambdaArchitecture)(nil)).Elem()

type LambdaArchitecturePtrInput interface {
	pulumi.Input

	ToLambdaArchitecturePtrOutput() LambdaArchitecturePtrOutput
	ToLambdaArchitecturePtrOutputWithContext(context.Context) LambdaArchitecturePtrOutput
}

type lambdaArchitecturePtr string

func LambdaArchitecturePtr(v string) LambdaArchitecturePtrInput {
	return (*lambdaArchitecturePtr)(&v)
}

func (*lambdaArchitecturePtr) ElementType() reflect.Type {
	return lambdaArchitecturePtrType
}

func (in *lambdaArchitecturePtr) ToLambdaArchitecturePtrOutput() LambdaArchitecturePtrOutput {
	return pulumi.ToOutput(in).(LambdaArchitecturePtrOutput)
}

func (in *lambdaArchitecturePtr) ToLambdaArchitecturePtrOutputWithContext(ctx context.Context) LambdaArchitecturePtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(LambdaArchitecturePtrOutput)
}

type LambdaLogRetention string

const (
	// 7 days
	LambdaLogRetention_7d = LambdaLogRetention("7d")
	// 30 days (1 month)
	LambdaLogRetention_30d = LambdaLogRetention("30d")
	// 90 days (3 months)
	LambdaLogRetention_90d = LambdaLogRetention("90d")
	// 1 year (365 days) — SOC 2 / ISO 27001 / PCI-DSS baseline. Default.
	LambdaLogRetention_1y = LambdaLogRetention("1y")
	// 3 years (1095 days) — FedRAMP minimum
	LambdaLogRetention_3y = LambdaLogRetention("3y")
	// 6 years (2190 days) — HIPAA minimum
	LambdaLogRetention_6y = LambdaLogRetention("6y")
	// 7 years (2555 days) — IRAP minimum
	LambdaLogRetention_7y = LambdaLogRetention("7y")
)

func (LambdaLogRetention) ElementType() reflect.Type {
	return reflect.TypeOf((*LambdaLogRetention)(nil)).Elem()
}

func (e LambdaLogRetention) ToLambdaLogRetentionOutput() LambdaLogRetentionOutput {
	return pulumi.ToOutput(e).(LambdaLogRetentionOutput)
}

func (e LambdaLogRetention) ToLambdaLogRetentionOutputWithContext(ctx context.Context) LambdaLogRetentionOutput {
	return pulumi.ToOutputWithContext(ctx, e).(LambdaLogRetentionOutput)
}

func (e LambdaLogRetention) ToLambdaLogRetentionPtrOutput() LambdaLogRetentionPtrOutput {
	return e.ToLambdaLogRetentionPtrOutputWithContext(context.Background())
}

func (e LambdaLogRetention) ToLambdaLogRetentionPtrOutputWithContext(ctx context.Context) LambdaLogRetentionPtrOutput {
	return LambdaLogRetention(e).ToLambdaLogRetentionOutputWithContext(ctx).ToLambdaLogRetentionPtrOutputWithContext(ctx)
}

func (e LambdaLogRetention) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e LambdaLogRetention) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e LambdaLogRetention) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e LambdaLogRetention) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type LambdaLogRetentionOutput struct{ *pulumi.OutputState }

func (LambdaLogRetentionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LambdaLogRetention)(nil)).Elem()
}

func (o LambdaLogRetentionOutput) ToLambdaLogRetentionOutput() LambdaLogRetentionOutput {
	return o
}

func (o LambdaLogRetentionOutput) ToLambdaLogRetentionOutputWithContext(ctx context.Context) LambdaLogRetentionOutput {
	return o
}

func (o LambdaLogRetentionOutput) ToLambdaLogRetentionPtrOutput() LambdaLogRetentionPtrOutput {
	return o.ToLambdaLogRetentionPtrOutputWithContext(context.Background())
}

func (o LambdaLogRetentionOutput) ToLambdaLogRetentionPtrOutputWithContext(ctx context.Context) LambdaLogRetentionPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v LambdaLogRetention) *LambdaLogRetention {
		return &v
	}).(LambdaLogRetentionPtrOutput)
}

func (o LambdaLogRetentionOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o LambdaLogRetentionOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e LambdaLogRetention) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o LambdaLogRetentionOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o LambdaLogRetentionOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e LambdaLogRetention) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type LambdaLogRetentionPtrOutput struct{ *pulumi.OutputState }

func (LambdaLogRetentionPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**LambdaLogRetention)(nil)).Elem()
}

func (o LambdaLogRetentionPtrOutput) ToLambdaLogRetentionPtrOutput() LambdaLogRetentionPtrOutput {
	return o
}

func (o LambdaLogRetentionPtrOutput) ToLambdaLogRetentionPtrOutputWithContext(ctx context.Context) LambdaLogRetentionPtrOutput {
	return o
}

func (o LambdaLogRetentionPtrOutput) Elem() LambdaLogRetentionOutput {
	return o.ApplyT(func(v *LambdaLogRetention) LambdaLogRetention {
		if v != nil {
			return *v
		}
		var ret LambdaLogRetention
		return ret
	}).(LambdaLogRetentionOutput)
}

func (o LambdaLogRetentionPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o LambdaLogRetentionPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *LambdaLogRetention) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// LambdaLogRetentionInput is an input type that accepts values of the LambdaLogRetention enum
// A concrete instance of `LambdaLogRetentionInput` can be one of the following:
//
//	LambdaLogRetention_7d
//	LambdaLogRetention_30d
//	LambdaLogRetention_90d
//	LambdaLogRetention_1y
//	LambdaLogRetention_3y
//	LambdaLogRetention_6y
//	LambdaLogRetention_7y
type LambdaLogRetentionInput interface {
	pulumi.Input

	ToLambdaLogRetentionOutput() LambdaLogRetentionOutput
	ToLambdaLogRetentionOutputWithContext(context.Context) LambdaLogRetentionOutput
}

var lambdaLogRetentionPtrType = reflect.TypeOf((**LambdaLogRetention)(nil)).Elem()

type LambdaLogRetentionPtrInput interface {
	pulumi.Input

	ToLambdaLogRetentionPtrOutput() LambdaLogRetentionPtrOutput
	ToLambdaLogRetentionPtrOutputWithContext(context.Context) LambdaLogRetentionPtrOutput
}

type lambdaLogRetentionPtr string

func LambdaLogRetentionPtr(v string) LambdaLogRetentionPtrInput {
	return (*lambdaLogRetentionPtr)(&v)
}

func (*lambdaLogRetentionPtr) ElementType() reflect.Type {
	return lambdaLogRetentionPtrType
}

func (in *lambdaLogRetentionPtr) ToLambdaLogRetentionPtrOutput() LambdaLogRetentionPtrOutput {
	return pulumi.ToOutput(in).(LambdaLogRetentionPtrOutput)
}

func (in *lambdaLogRetentionPtr) ToLambdaLogRetentionPtrOutputWithContext(ctx context.Context) LambdaLogRetentionPtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(LambdaLogRetentionPtrOutput)
}

type LambdaRuntime string

const (
	// Node.js 24 (LTS) — recommended
	LambdaRuntime_Nodejs24_x = LambdaRuntime("nodejs24.x")
	// Node.js 22 (LTS)
	LambdaRuntime_Nodejs22_x = LambdaRuntime("nodejs22.x")
)

func (LambdaRuntime) ElementType() reflect.Type {
	return reflect.TypeOf((*LambdaRuntime)(nil)).Elem()
}

func (e LambdaRuntime) ToLambdaRuntimeOutput() LambdaRuntimeOutput {
	return pulumi.ToOutput(e).(LambdaRuntimeOutput)
}

func (e LambdaRuntime) ToLambdaRuntimeOutputWithContext(ctx context.Context) LambdaRuntimeOutput {
	return pulumi.ToOutputWithContext(ctx, e).(LambdaRuntimeOutput)
}

func (e LambdaRuntime) ToLambdaRuntimePtrOutput() LambdaRuntimePtrOutput {
	return e.ToLambdaRuntimePtrOutputWithContext(context.Background())
}

func (e LambdaRuntime) ToLambdaRuntimePtrOutputWithContext(ctx context.Context) LambdaRuntimePtrOutput {
	return LambdaRuntime(e).ToLambdaRuntimeOutputWithContext(ctx).ToLambdaRuntimePtrOutputWithContext(ctx)
}

func (e LambdaRuntime) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e LambdaRuntime) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e LambdaRuntime) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e LambdaRuntime) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type LambdaRuntimeOutput struct{ *pulumi.OutputState }

func (LambdaRuntimeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LambdaRuntime)(nil)).Elem()
}

func (o LambdaRuntimeOutput) ToLambdaRuntimeOutput() LambdaRuntimeOutput {
	return o
}

func (o LambdaRuntimeOutput) ToLambdaRuntimeOutputWithContext(ctx context.Context) LambdaRuntimeOutput {
	return o
}

func (o LambdaRuntimeOutput) ToLambdaRuntimePtrOutput() LambdaRuntimePtrOutput {
	return o.ToLambdaRuntimePtrOutputWithContext(context.Background())
}

func (o LambdaRuntimeOutput) ToLambdaRuntimePtrOutputWithContext(ctx context.Context) LambdaRuntimePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v LambdaRuntime) *LambdaRuntime {
		return &v
	}).(LambdaRuntimePtrOutput)
}

func (o LambdaRuntimeOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o LambdaRuntimeOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e LambdaRuntime) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o LambdaRuntimeOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o LambdaRuntimeOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e LambdaRuntime) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type LambdaRuntimePtrOutput struct{ *pulumi.OutputState }

func (LambdaRuntimePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**LambdaRuntime)(nil)).Elem()
}

func (o LambdaRuntimePtrOutput) ToLambdaRuntimePtrOutput() LambdaRuntimePtrOutput {
	return o
}

func (o LambdaRuntimePtrOutput) ToLambdaRuntimePtrOutputWithContext(ctx context.Context) LambdaRuntimePtrOutput {
	return o
}

func (o LambdaRuntimePtrOutput) Elem() LambdaRuntimeOutput {
	return o.ApplyT(func(v *LambdaRuntime) LambdaRuntime {
		if v != nil {
			return *v
		}
		var ret LambdaRuntime
		return ret
	}).(LambdaRuntimeOutput)
}

func (o LambdaRuntimePtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o LambdaRuntimePtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *LambdaRuntime) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// LambdaRuntimeInput is an input type that accepts values of the LambdaRuntime enum
// A concrete instance of `LambdaRuntimeInput` can be one of the following:
//
//	LambdaRuntime_Nodejs24_x
//	LambdaRuntime_Nodejs22_x
type LambdaRuntimeInput interface {
	pulumi.Input

	ToLambdaRuntimeOutput() LambdaRuntimeOutput
	ToLambdaRuntimeOutputWithContext(context.Context) LambdaRuntimeOutput
}

var lambdaRuntimePtrType = reflect.TypeOf((**LambdaRuntime)(nil)).Elem()

type LambdaRuntimePtrInput interface {
	pulumi.Input

	ToLambdaRuntimePtrOutput() LambdaRuntimePtrOutput
	ToLambdaRuntimePtrOutputWithContext(context.Context) LambdaRuntimePtrOutput
}

type lambdaRuntimePtr string

func LambdaRuntimePtr(v string) LambdaRuntimePtrInput {
	return (*lambdaRuntimePtr)(&v)
}

func (*lambdaRuntimePtr) ElementType() reflect.Type {
	return lambdaRuntimePtrType
}

func (in *lambdaRuntimePtr) ToLambdaRuntimePtrOutput() LambdaRuntimePtrOutput {
	return pulumi.ToOutput(in).(LambdaRuntimePtrOutput)
}

func (in *lambdaRuntimePtr) ToLambdaRuntimePtrOutputWithContext(ctx context.Context) LambdaRuntimePtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(LambdaRuntimePtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*LambdaArchitectureInput)(nil)).Elem(), LambdaArchitecture("arm64"))
	pulumi.RegisterInputType(reflect.TypeOf((*LambdaArchitecturePtrInput)(nil)).Elem(), LambdaArchitecture("arm64"))
	pulumi.RegisterInputType(reflect.TypeOf((*LambdaLogRetentionInput)(nil)).Elem(), LambdaLogRetention("7d"))
	pulumi.RegisterInputType(reflect.TypeOf((*LambdaLogRetentionPtrInput)(nil)).Elem(), LambdaLogRetention("7d"))
	pulumi.RegisterInputType(reflect.TypeOf((*LambdaRuntimeInput)(nil)).Elem(), LambdaRuntime("nodejs24.x"))
	pulumi.RegisterInputType(reflect.TypeOf((*LambdaRuntimePtrInput)(nil)).Elem(), LambdaRuntime("nodejs24.x"))
	pulumi.RegisterOutputType(LambdaArchitectureOutput{})
	pulumi.RegisterOutputType(LambdaArchitecturePtrOutput{})
	pulumi.RegisterOutputType(LambdaLogRetentionOutput{})
	pulumi.RegisterOutputType(LambdaLogRetentionPtrOutput{})
	pulumi.RegisterOutputType(LambdaRuntimeOutput{})
	pulumi.RegisterOutputType(LambdaRuntimePtrOutput{})
}
