// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package aws

import (
	"context"
	"reflect"

	"github.com/DamienPace15/anvil/sdk/go/anvil/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// An Anvil-managed AWS WAF WebACL with researched defaults: a per-client rate limit (2000 requests / 5 min) and AWS managed rule groups for IP reputation, known bad inputs, the OWASP core rule set and SQL injection. Starts in count mode — matches are logged, not blocked — until mode is set to "block". Attach it to a site with waf: { arn } or to a Cognito user pool with waf: { arn }.
type Waf struct {
	pulumi.ResourceState

	// The WebACL ARN. Pass it to a site's waf.arn (cloudfront scope) or a Cognito user pool's waf.arn (regional scope).
	Arn pulumi.StringOutput `pulumi:"arn"`
	// The CloudWatch log group receiving WAF logs. Empty when logging is off.
	LogGroupName pulumi.StringOutput `pulumi:"logGroupName"`
	// The physical WebACL name.
	Name pulumi.StringOutput `pulumi:"name"`
	// "cloudfront" or "regional".
	Scope pulumi.StringOutput `pulumi:"scope"`
	// The WebACL ID.
	WebAclId pulumi.StringOutput `pulumi:"webAclId"`
}

// NewWaf registers a new resource with the given unique name, arguments, and options.
func NewWaf(ctx *pulumi.Context,
	name string, args *WafArgs, opts ...pulumi.ResourceOption) (*Waf, error) {
	if args == nil {
		args = &WafArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Waf
	err := ctx.RegisterRemoteComponentResource("anvil:aws:Waf", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type wafArgs struct {
	// Two-letter ISO 3166 country codes to block, e.g. ["KP"]. Follows mode.
	BlockCountries []string `pulumi:"blockCountries"`
	// Header carrying the real visitor IP when the site sits behind a proxy, e.g. "CF-Connecting-IP" for Cloudflare. The rate limit, IP lists and country blocking then use the visitor's IP instead of the proxy's. AWS's ipReputation and anonymousIp rule groups can't read this header, so they default to off when it's set.
	ClientIpHeader *string `pulumi:"clientIpHeader"`
	// IP addresses or CIDRs (IPv4 and IPv6) that are always allowed, skipping every other rule — e.g. office networks or uptime monitors.
	IpAllowList []string `pulumi:"ipAllowList"`
	// IP addresses or CIDRs (IPv4 and IPv6) that are always blocked.
	IpBlockList []string `pulumi:"ipBlockList"`
	// Logging to CloudWatch Logs. On by default: blocked and counted requests only, kept 30 days, with the authorization, cookie and x-origin-secret headers redacted.
	Logging *WafLoggingArgs `pulumi:"logging"`
	// AWS managed rule groups. On by default: core, knownBadInputs, ipReputation, sqli. Off by default: anonymousIp, adminProtection.
	ManagedRules *WafManagedRulesArgs `pulumi:"managedRules"`
	// What rules do when they match. "count" (default): log the match without blocking — use this to check for false positives on live traffic. "block": block matching requests. The IP allow and block lists always allow / block regardless of mode.
	Mode *WafMode `pulumi:"mode"`
	// Per-client rate limit. On by default: 2000 requests per client per 5 minutes.
	RateLimit *WafRateLimitArgs `pulumi:"rateLimit"`
	// Override the action of individual AWS managed rules, keyed by exact AWS rule name: "count", "block" or "allow". Default: { SizeRestrictions_BODY: "count" } — that rule blocks any body over 8 KB, which breaks forms, JSON APIs and uploads. Set it to "block" to restore it.
	RuleOverrides map[string]string `pulumi:"ruleOverrides"`
	// What the WAF protects. "cloudfront" (default): sites and other CloudFront distributions; created in us-east-1 as AWS requires. "regional": regional resources such as Cognito user pools; created in the stack's region.
	Scope     *WafScope         `pulumi:"scope"`
	Transform *WafTransformArgs `pulumi:"transform"`
}

// The set of arguments for constructing a Waf resource.
type WafArgs struct {
	// Two-letter ISO 3166 country codes to block, e.g. ["KP"]. Follows mode.
	BlockCountries pulumi.StringArrayInput
	// Header carrying the real visitor IP when the site sits behind a proxy, e.g. "CF-Connecting-IP" for Cloudflare. The rate limit, IP lists and country blocking then use the visitor's IP instead of the proxy's. AWS's ipReputation and anonymousIp rule groups can't read this header, so they default to off when it's set.
	ClientIpHeader pulumi.StringPtrInput
	// IP addresses or CIDRs (IPv4 and IPv6) that are always allowed, skipping every other rule — e.g. office networks or uptime monitors.
	IpAllowList pulumi.StringArrayInput
	// IP addresses or CIDRs (IPv4 and IPv6) that are always blocked.
	IpBlockList pulumi.StringArrayInput
	// Logging to CloudWatch Logs. On by default: blocked and counted requests only, kept 30 days, with the authorization, cookie and x-origin-secret headers redacted.
	Logging WafLoggingArgsPtrInput
	// AWS managed rule groups. On by default: core, knownBadInputs, ipReputation, sqli. Off by default: anonymousIp, adminProtection.
	ManagedRules WafManagedRulesArgsPtrInput
	// What rules do when they match. "count" (default): log the match without blocking — use this to check for false positives on live traffic. "block": block matching requests. The IP allow and block lists always allow / block regardless of mode.
	Mode WafModePtrInput
	// Per-client rate limit. On by default: 2000 requests per client per 5 minutes.
	RateLimit WafRateLimitArgsPtrInput
	// Override the action of individual AWS managed rules, keyed by exact AWS rule name: "count", "block" or "allow". Default: { SizeRestrictions_BODY: "count" } — that rule blocks any body over 8 KB, which breaks forms, JSON APIs and uploads. Set it to "block" to restore it.
	RuleOverrides pulumi.StringMapInput
	// What the WAF protects. "cloudfront" (default): sites and other CloudFront distributions; created in us-east-1 as AWS requires. "regional": regional resources such as Cognito user pools; created in the stack's region.
	Scope     WafScopePtrInput
	Transform WafTransformArgsPtrInput
}

func (WafArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*wafArgs)(nil)).Elem()
}

type WafInput interface {
	pulumi.Input

	ToWafOutput() WafOutput
	ToWafOutputWithContext(ctx context.Context) WafOutput
}

func (*Waf) ElementType() reflect.Type {
	return reflect.TypeOf((**Waf)(nil)).Elem()
}

func (i *Waf) ToWafOutput() WafOutput {
	return i.ToWafOutputWithContext(context.Background())
}

func (i *Waf) ToWafOutputWithContext(ctx context.Context) WafOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WafOutput)
}

// WafArrayInput is an input type that accepts WafArray and WafArrayOutput values.
// You can construct a concrete instance of `WafArrayInput` via:
//
//	WafArray{ WafArgs{...} }
type WafArrayInput interface {
	pulumi.Input

	ToWafArrayOutput() WafArrayOutput
	ToWafArrayOutputWithContext(context.Context) WafArrayOutput
}

type WafArray []WafInput

func (WafArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Waf)(nil)).Elem()
}

func (i WafArray) ToWafArrayOutput() WafArrayOutput {
	return i.ToWafArrayOutputWithContext(context.Background())
}

func (i WafArray) ToWafArrayOutputWithContext(ctx context.Context) WafArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WafArrayOutput)
}

// WafMapInput is an input type that accepts WafMap and WafMapOutput values.
// You can construct a concrete instance of `WafMapInput` via:
//
//	WafMap{ "key": WafArgs{...} }
type WafMapInput interface {
	pulumi.Input

	ToWafMapOutput() WafMapOutput
	ToWafMapOutputWithContext(context.Context) WafMapOutput
}

type WafMap map[string]WafInput

func (WafMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Waf)(nil)).Elem()
}

func (i WafMap) ToWafMapOutput() WafMapOutput {
	return i.ToWafMapOutputWithContext(context.Background())
}

func (i WafMap) ToWafMapOutputWithContext(ctx context.Context) WafMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WafMapOutput)
}

type WafOutput struct{ *pulumi.OutputState }

func (WafOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Waf)(nil)).Elem()
}

func (o WafOutput) ToWafOutput() WafOutput {
	return o
}

func (o WafOutput) ToWafOutputWithContext(ctx context.Context) WafOutput {
	return o
}

// The WebACL ARN. Pass it to a site's waf.arn (cloudfront scope) or a Cognito user pool's waf.arn (regional scope).
func (o WafOutput) Arn() pulumi.StringOutput {
	return o.ApplyT(func(v *Waf) pulumi.StringOutput { return v.Arn }).(pulumi.StringOutput)
}

// The CloudWatch log group receiving WAF logs. Empty when logging is off.
func (o WafOutput) LogGroupName() pulumi.StringOutput {
	return o.ApplyT(func(v *Waf) pulumi.StringOutput { return v.LogGroupName }).(pulumi.StringOutput)
}

// The physical WebACL name.
func (o WafOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Waf) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// "cloudfront" or "regional".
func (o WafOutput) Scope() pulumi.StringOutput {
	return o.ApplyT(func(v *Waf) pulumi.StringOutput { return v.Scope }).(pulumi.StringOutput)
}

// The WebACL ID.
func (o WafOutput) WebAclId() pulumi.StringOutput {
	return o.ApplyT(func(v *Waf) pulumi.StringOutput { return v.WebAclId }).(pulumi.StringOutput)
}

type WafArrayOutput struct{ *pulumi.OutputState }

func (WafArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Waf)(nil)).Elem()
}

func (o WafArrayOutput) ToWafArrayOutput() WafArrayOutput {
	return o
}

func (o WafArrayOutput) ToWafArrayOutputWithContext(ctx context.Context) WafArrayOutput {
	return o
}

func (o WafArrayOutput) Index(i pulumi.IntInput) WafOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Waf {
		return vs[0].([]*Waf)[vs[1].(int)]
	}).(WafOutput)
}

type WafMapOutput struct{ *pulumi.OutputState }

func (WafMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Waf)(nil)).Elem()
}

func (o WafMapOutput) ToWafMapOutput() WafMapOutput {
	return o
}

func (o WafMapOutput) ToWafMapOutputWithContext(ctx context.Context) WafMapOutput {
	return o
}

func (o WafMapOutput) MapIndex(k pulumi.StringInput) WafOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Waf {
		return vs[0].(map[string]*Waf)[vs[1].(string)]
	}).(WafOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*WafInput)(nil)).Elem(), &Waf{})
	pulumi.RegisterInputType(reflect.TypeOf((*WafArrayInput)(nil)).Elem(), WafArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*WafMapInput)(nil)).Elem(), WafMap{})
	pulumi.RegisterOutputType(WafOutput{})
	pulumi.RegisterOutputType(WafArrayOutput{})
	pulumi.RegisterOutputType(WafMapOutput{})
}
