# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
import pulumi_gcp

__all__ = [
    'BucketOverridesArgs',
    'BucketOverridesArgsDict',
    'BucketTransformArgsArgs',
    'BucketTransformArgsArgsDict',
    'FunctionOverridesArgs',
    'FunctionOverridesArgsDict',
    'FunctionTransformArgsArgs',
    'FunctionTransformArgsArgsDict',
]

class BucketOverridesArgsDict(TypedDict):
    autoclass: NotRequired[pulumi.Input['pulumi_gcp.storage.BucketAutoclassArgsDict']]
    """
    The bucket's [Autoclass](https://cloud.google.com/storage/docs/autoclass) configuration.  Structure is documented below.
    """
    cors: NotRequired[pulumi.Input[Sequence[pulumi.Input['pulumi_gcp.storage.BucketCorArgsDict']]]]
    """
    The bucket's [Cross-Origin Resource Sharing (CORS)](https://www.w3.org/TR/cors/) configuration. Multiple blocks of this type are permitted. Structure is documented below.
    """
    custom_placement_config: NotRequired[pulumi.Input['pulumi_gcp.storage.BucketCustomPlacementConfigArgsDict']]
    """
    The bucket's custom location configuration, which specifies the individual regions that comprise a dual-region bucket. If the bucket is designated a single or multi-region, the parameters are empty. Structure is documented below.
    """
    default_event_based_hold: NotRequired[pulumi.Input[_builtins.bool]]
    """
    Whether or not to automatically apply an eventBasedHold to new objects added to the bucket.
    """
    enable_object_retention: NotRequired[pulumi.Input[_builtins.bool]]
    """
    Enables [object retention](https://cloud.google.com/storage/docs/object-lock) on a storage bucket.
    """
    encryption: NotRequired[pulumi.Input['pulumi_gcp.storage.BucketEncryptionArgsDict']]
    """
    The bucket's encryption configuration. Structure is documented below.
    """
    force_destroy: NotRequired[pulumi.Input[_builtins.bool]]
    """
    When true, before deleting a bucket, delete all objects within the bucket, or Anywhere Caches caching data for that bucket. Otherwise, buckets with objects/caches will fail. Anywhere Cache requires additional permissions to interact with and will be assumed not present when the provider is not permissioned, attempting to delete the bucket anyways. This may result in the objects in the bucket getting destroyed but not the bucket itself if there is a cache in use with the bucket. Force deletion may take a long time to delete buckets with lots of objects or with any Anywhere Caches (80m+).
    """
    hierarchical_namespace: NotRequired[pulumi.Input['pulumi_gcp.storage.BucketHierarchicalNamespaceArgsDict']]
    """
    The bucket's hierarchical namespace policy, which defines the bucket capability to handle folders in logical structure. Structure is documented below. To use this configuration, <span pulumi-lang-nodejs="`uniformBucketLevelAccess`" pulumi-lang-dotnet="`UniformBucketLevelAccess`" pulumi-lang-go="`uniformBucketLevelAccess`" pulumi-lang-python="`uniform_bucket_level_access`" pulumi-lang-yaml="`uniformBucketLevelAccess`" pulumi-lang-java="`uniformBucketLevelAccess`">`uniform_bucket_level_access`</span> must be enabled on bucket.
    """
    ip_filter: NotRequired[pulumi.Input['pulumi_gcp.storage.BucketIpFilterArgsDict']]
    """
    The bucket IP filtering configuration. Specifies the network sources that can access the bucket, as well as its underlying objects. Structure is documented below.
    """
    labels: NotRequired[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]
    """
    A map of key/value label pairs to assign to the bucket.
    """
    lifecycle_rules: NotRequired[pulumi.Input[Sequence[pulumi.Input['pulumi_gcp.storage.BucketLifecycleRuleArgsDict']]]]
    """
    The bucket's [Lifecycle Rules](https://cloud.google.com/storage/docs/lifecycle#configuration) configuration. Multiple blocks of this type are permitted. Structure is documented below.
    """
    location: NotRequired[pulumi.Input[_builtins.str]]
    """
    The [GCS location](https://cloud.google.com/storage/docs/bucket-locations).

    - - -
    """
    logging: NotRequired[pulumi.Input['pulumi_gcp.storage.BucketLoggingArgsDict']]
    """
    The bucket's [Access & Storage Logs](https://cloud.google.com/storage/docs/access-logs) configuration. Structure is documented below.
    """
    name: NotRequired[pulumi.Input[_builtins.str]]
    """
    The name of the bucket. Bucket names must be in lowercase and no more than 63 characters long. You can find the complete list of bucket naming rules [here](https://cloud.google.com/storage/docs/buckets#naming).
    """
    project: NotRequired[pulumi.Input[_builtins.str]]
    """
    The ID of the project in which the resource belongs. If it
    is not provided, the provider project is used.
    """
    public_access_prevention: NotRequired[pulumi.Input[_builtins.str]]
    """
    Prevents public access to a bucket. Acceptable values are "inherited" or "enforced". If "inherited", the bucket uses [public access prevention](https://cloud.google.com/storage/docs/public-access-prevention) only if the bucket is subject to the public access prevention organization policy constraint. Defaults to "inherited".
    """
    requester_pays: NotRequired[pulumi.Input[_builtins.bool]]
    """
    Enables [Requester Pays](https://cloud.google.com/storage/docs/requester-pays) on a storage bucket.
    """
    retention_policy: NotRequired[pulumi.Input['pulumi_gcp.storage.BucketRetentionPolicyArgsDict']]
    """
    Configuration of the bucket's data retention policy for how long objects in the bucket should be retained. Structure is documented below.
    """
    rpo: NotRequired[pulumi.Input[_builtins.str]]
    """
    The recovery point objective for cross-region replication of the bucket. Applicable only for dual and multi-region buckets. `"DEFAULT"` sets default replication. `"ASYNC_TURBO"` value enables turbo replication, valid for dual-region buckets only. See [Turbo Replication](https://cloud.google.com/storage/docs/managing-turbo-replication) for more information. If rpo is not specified at bucket creation, it defaults to `"DEFAULT"` for dual and multi-region buckets. **NOTE** If used with single-region bucket, It will throw an error.
    """
    soft_delete_policy: NotRequired[pulumi.Input['pulumi_gcp.storage.BucketSoftDeletePolicyArgsDict']]
    """
    The bucket's soft delete policy, which defines the period of time that soft-deleted objects will be retained, and cannot be permanently deleted. If the block is not provided, Server side value will be kept which means removal of block won't generate any terraform change. Structure is documented below.
    """
    storage_class: NotRequired[pulumi.Input[_builtins.str]]
    """
    The [Storage Class](https://cloud.google.com/storage/docs/storage-classes) of the new bucket. Supported values include: `STANDARD`, `MULTI_REGIONAL`, `REGIONAL`, `NEARLINE`, `COLDLINE`, `ARCHIVE`.
    """
    uniform_bucket_level_access: NotRequired[pulumi.Input[_builtins.bool]]
    """
    Enables [Uniform bucket-level access](https://cloud.google.com/storage/docs/uniform-bucket-level-access) access to a bucket.
    """
    versioning: NotRequired[pulumi.Input['pulumi_gcp.storage.BucketVersioningArgsDict']]
    """
    The bucket's [Versioning](https://cloud.google.com/storage/docs/object-versioning) configuration.  Structure is documented below.
    """
    website: NotRequired[pulumi.Input['pulumi_gcp.storage.BucketWebsiteArgsDict']]
    """
    Configuration if the bucket acts as a website. Structure is documented below.
    """

@pulumi.input_type
class BucketOverridesArgs:
    def __init__(__self__, *,
                 autoclass: Optional[pulumi.Input['pulumi_gcp.storage.BucketAutoclassArgs']] = None,
                 cors: Optional[pulumi.Input[Sequence[pulumi.Input['pulumi_gcp.storage.BucketCorArgs']]]] = None,
                 custom_placement_config: Optional[pulumi.Input['pulumi_gcp.storage.BucketCustomPlacementConfigArgs']] = None,
                 default_event_based_hold: Optional[pulumi.Input[_builtins.bool]] = None,
                 enable_object_retention: Optional[pulumi.Input[_builtins.bool]] = None,
                 encryption: Optional[pulumi.Input['pulumi_gcp.storage.BucketEncryptionArgs']] = None,
                 force_destroy: Optional[pulumi.Input[_builtins.bool]] = None,
                 hierarchical_namespace: Optional[pulumi.Input['pulumi_gcp.storage.BucketHierarchicalNamespaceArgs']] = None,
                 ip_filter: Optional[pulumi.Input['pulumi_gcp.storage.BucketIpFilterArgs']] = None,
                 labels: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 lifecycle_rules: Optional[pulumi.Input[Sequence[pulumi.Input['pulumi_gcp.storage.BucketLifecycleRuleArgs']]]] = None,
                 location: Optional[pulumi.Input[_builtins.str]] = None,
                 logging: Optional[pulumi.Input['pulumi_gcp.storage.BucketLoggingArgs']] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 project: Optional[pulumi.Input[_builtins.str]] = None,
                 public_access_prevention: Optional[pulumi.Input[_builtins.str]] = None,
                 requester_pays: Optional[pulumi.Input[_builtins.bool]] = None,
                 retention_policy: Optional[pulumi.Input['pulumi_gcp.storage.BucketRetentionPolicyArgs']] = None,
                 rpo: Optional[pulumi.Input[_builtins.str]] = None,
                 soft_delete_policy: Optional[pulumi.Input['pulumi_gcp.storage.BucketSoftDeletePolicyArgs']] = None,
                 storage_class: Optional[pulumi.Input[_builtins.str]] = None,
                 uniform_bucket_level_access: Optional[pulumi.Input[_builtins.bool]] = None,
                 versioning: Optional[pulumi.Input['pulumi_gcp.storage.BucketVersioningArgs']] = None,
                 website: Optional[pulumi.Input['pulumi_gcp.storage.BucketWebsiteArgs']] = None):
        """
        :param pulumi.Input['pulumi_gcp.storage.BucketAutoclassArgs'] autoclass: The bucket's [Autoclass](https://cloud.google.com/storage/docs/autoclass) configuration.  Structure is documented below.
        :param pulumi.Input[Sequence[pulumi.Input['pulumi_gcp.storage.BucketCorArgs']]] cors: The bucket's [Cross-Origin Resource Sharing (CORS)](https://www.w3.org/TR/cors/) configuration. Multiple blocks of this type are permitted. Structure is documented below.
        :param pulumi.Input['pulumi_gcp.storage.BucketCustomPlacementConfigArgs'] custom_placement_config: The bucket's custom location configuration, which specifies the individual regions that comprise a dual-region bucket. If the bucket is designated a single or multi-region, the parameters are empty. Structure is documented below.
        :param pulumi.Input[_builtins.bool] default_event_based_hold: Whether or not to automatically apply an eventBasedHold to new objects added to the bucket.
        :param pulumi.Input[_builtins.bool] enable_object_retention: Enables [object retention](https://cloud.google.com/storage/docs/object-lock) on a storage bucket.
        :param pulumi.Input['pulumi_gcp.storage.BucketEncryptionArgs'] encryption: The bucket's encryption configuration. Structure is documented below.
        :param pulumi.Input[_builtins.bool] force_destroy: When true, before deleting a bucket, delete all objects within the bucket, or Anywhere Caches caching data for that bucket. Otherwise, buckets with objects/caches will fail. Anywhere Cache requires additional permissions to interact with and will be assumed not present when the provider is not permissioned, attempting to delete the bucket anyways. This may result in the objects in the bucket getting destroyed but not the bucket itself if there is a cache in use with the bucket. Force deletion may take a long time to delete buckets with lots of objects or with any Anywhere Caches (80m+).
        :param pulumi.Input['pulumi_gcp.storage.BucketHierarchicalNamespaceArgs'] hierarchical_namespace: The bucket's hierarchical namespace policy, which defines the bucket capability to handle folders in logical structure. Structure is documented below. To use this configuration, <span pulumi-lang-nodejs="`uniformBucketLevelAccess`" pulumi-lang-dotnet="`UniformBucketLevelAccess`" pulumi-lang-go="`uniformBucketLevelAccess`" pulumi-lang-python="`uniform_bucket_level_access`" pulumi-lang-yaml="`uniformBucketLevelAccess`" pulumi-lang-java="`uniformBucketLevelAccess`">`uniform_bucket_level_access`</span> must be enabled on bucket.
        :param pulumi.Input['pulumi_gcp.storage.BucketIpFilterArgs'] ip_filter: The bucket IP filtering configuration. Specifies the network sources that can access the bucket, as well as its underlying objects. Structure is documented below.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: A map of key/value label pairs to assign to the bucket.
        :param pulumi.Input[Sequence[pulumi.Input['pulumi_gcp.storage.BucketLifecycleRuleArgs']]] lifecycle_rules: The bucket's [Lifecycle Rules](https://cloud.google.com/storage/docs/lifecycle#configuration) configuration. Multiple blocks of this type are permitted. Structure is documented below.
        :param pulumi.Input[_builtins.str] location: The [GCS location](https://cloud.google.com/storage/docs/bucket-locations).
               
               - - -
        :param pulumi.Input['pulumi_gcp.storage.BucketLoggingArgs'] logging: The bucket's [Access & Storage Logs](https://cloud.google.com/storage/docs/access-logs) configuration. Structure is documented below.
        :param pulumi.Input[_builtins.str] name: The name of the bucket. Bucket names must be in lowercase and no more than 63 characters long. You can find the complete list of bucket naming rules [here](https://cloud.google.com/storage/docs/buckets#naming).
        :param pulumi.Input[_builtins.str] project: The ID of the project in which the resource belongs. If it
               is not provided, the provider project is used.
        :param pulumi.Input[_builtins.str] public_access_prevention: Prevents public access to a bucket. Acceptable values are "inherited" or "enforced". If "inherited", the bucket uses [public access prevention](https://cloud.google.com/storage/docs/public-access-prevention) only if the bucket is subject to the public access prevention organization policy constraint. Defaults to "inherited".
        :param pulumi.Input[_builtins.bool] requester_pays: Enables [Requester Pays](https://cloud.google.com/storage/docs/requester-pays) on a storage bucket.
        :param pulumi.Input['pulumi_gcp.storage.BucketRetentionPolicyArgs'] retention_policy: Configuration of the bucket's data retention policy for how long objects in the bucket should be retained. Structure is documented below.
        :param pulumi.Input[_builtins.str] rpo: The recovery point objective for cross-region replication of the bucket. Applicable only for dual and multi-region buckets. `"DEFAULT"` sets default replication. `"ASYNC_TURBO"` value enables turbo replication, valid for dual-region buckets only. See [Turbo Replication](https://cloud.google.com/storage/docs/managing-turbo-replication) for more information. If rpo is not specified at bucket creation, it defaults to `"DEFAULT"` for dual and multi-region buckets. **NOTE** If used with single-region bucket, It will throw an error.
        :param pulumi.Input['pulumi_gcp.storage.BucketSoftDeletePolicyArgs'] soft_delete_policy: The bucket's soft delete policy, which defines the period of time that soft-deleted objects will be retained, and cannot be permanently deleted. If the block is not provided, Server side value will be kept which means removal of block won't generate any terraform change. Structure is documented below.
        :param pulumi.Input[_builtins.str] storage_class: The [Storage Class](https://cloud.google.com/storage/docs/storage-classes) of the new bucket. Supported values include: `STANDARD`, `MULTI_REGIONAL`, `REGIONAL`, `NEARLINE`, `COLDLINE`, `ARCHIVE`.
        :param pulumi.Input[_builtins.bool] uniform_bucket_level_access: Enables [Uniform bucket-level access](https://cloud.google.com/storage/docs/uniform-bucket-level-access) access to a bucket.
        :param pulumi.Input['pulumi_gcp.storage.BucketVersioningArgs'] versioning: The bucket's [Versioning](https://cloud.google.com/storage/docs/object-versioning) configuration.  Structure is documented below.
        :param pulumi.Input['pulumi_gcp.storage.BucketWebsiteArgs'] website: Configuration if the bucket acts as a website. Structure is documented below.
        """
        if autoclass is not None:
            pulumi.set(__self__, "autoclass", autoclass)
        if cors is not None:
            pulumi.set(__self__, "cors", cors)
        if custom_placement_config is not None:
            pulumi.set(__self__, "custom_placement_config", custom_placement_config)
        if default_event_based_hold is not None:
            pulumi.set(__self__, "default_event_based_hold", default_event_based_hold)
        if enable_object_retention is not None:
            pulumi.set(__self__, "enable_object_retention", enable_object_retention)
        if encryption is not None:
            pulumi.set(__self__, "encryption", encryption)
        if force_destroy is not None:
            pulumi.set(__self__, "force_destroy", force_destroy)
        if hierarchical_namespace is not None:
            pulumi.set(__self__, "hierarchical_namespace", hierarchical_namespace)
        if ip_filter is not None:
            pulumi.set(__self__, "ip_filter", ip_filter)
        if labels is not None:
            pulumi.set(__self__, "labels", labels)
        if lifecycle_rules is not None:
            pulumi.set(__self__, "lifecycle_rules", lifecycle_rules)
        if location is not None:
            pulumi.set(__self__, "location", location)
        if logging is not None:
            pulumi.set(__self__, "logging", logging)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if project is not None:
            pulumi.set(__self__, "project", project)
        if public_access_prevention is not None:
            pulumi.set(__self__, "public_access_prevention", public_access_prevention)
        if requester_pays is not None:
            pulumi.set(__self__, "requester_pays", requester_pays)
        if retention_policy is not None:
            pulumi.set(__self__, "retention_policy", retention_policy)
        if rpo is not None:
            pulumi.set(__self__, "rpo", rpo)
        if soft_delete_policy is not None:
            pulumi.set(__self__, "soft_delete_policy", soft_delete_policy)
        if storage_class is not None:
            pulumi.set(__self__, "storage_class", storage_class)
        if uniform_bucket_level_access is not None:
            pulumi.set(__self__, "uniform_bucket_level_access", uniform_bucket_level_access)
        if versioning is not None:
            pulumi.set(__self__, "versioning", versioning)
        if website is not None:
            pulumi.set(__self__, "website", website)

    @_builtins.property
    @pulumi.getter
    def autoclass(self) -> Optional[pulumi.Input['pulumi_gcp.storage.BucketAutoclassArgs']]:
        """
        The bucket's [Autoclass](https://cloud.google.com/storage/docs/autoclass) configuration.  Structure is documented below.
        """
        return pulumi.get(self, "autoclass")

    @autoclass.setter
    def autoclass(self, value: Optional[pulumi.Input['pulumi_gcp.storage.BucketAutoclassArgs']]):
        pulumi.set(self, "autoclass", value)

    @_builtins.property
    @pulumi.getter
    def cors(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['pulumi_gcp.storage.BucketCorArgs']]]]:
        """
        The bucket's [Cross-Origin Resource Sharing (CORS)](https://www.w3.org/TR/cors/) configuration. Multiple blocks of this type are permitted. Structure is documented below.
        """
        return pulumi.get(self, "cors")

    @cors.setter
    def cors(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['pulumi_gcp.storage.BucketCorArgs']]]]):
        pulumi.set(self, "cors", value)

    @_builtins.property
    @pulumi.getter(name="customPlacementConfig")
    def custom_placement_config(self) -> Optional[pulumi.Input['pulumi_gcp.storage.BucketCustomPlacementConfigArgs']]:
        """
        The bucket's custom location configuration, which specifies the individual regions that comprise a dual-region bucket. If the bucket is designated a single or multi-region, the parameters are empty. Structure is documented below.
        """
        return pulumi.get(self, "custom_placement_config")

    @custom_placement_config.setter
    def custom_placement_config(self, value: Optional[pulumi.Input['pulumi_gcp.storage.BucketCustomPlacementConfigArgs']]):
        pulumi.set(self, "custom_placement_config", value)

    @_builtins.property
    @pulumi.getter(name="defaultEventBasedHold")
    def default_event_based_hold(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether or not to automatically apply an eventBasedHold to new objects added to the bucket.
        """
        return pulumi.get(self, "default_event_based_hold")

    @default_event_based_hold.setter
    def default_event_based_hold(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "default_event_based_hold", value)

    @_builtins.property
    @pulumi.getter(name="enableObjectRetention")
    def enable_object_retention(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Enables [object retention](https://cloud.google.com/storage/docs/object-lock) on a storage bucket.
        """
        return pulumi.get(self, "enable_object_retention")

    @enable_object_retention.setter
    def enable_object_retention(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "enable_object_retention", value)

    @_builtins.property
    @pulumi.getter
    def encryption(self) -> Optional[pulumi.Input['pulumi_gcp.storage.BucketEncryptionArgs']]:
        """
        The bucket's encryption configuration. Structure is documented below.
        """
        return pulumi.get(self, "encryption")

    @encryption.setter
    def encryption(self, value: Optional[pulumi.Input['pulumi_gcp.storage.BucketEncryptionArgs']]):
        pulumi.set(self, "encryption", value)

    @_builtins.property
    @pulumi.getter(name="forceDestroy")
    def force_destroy(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        When true, before deleting a bucket, delete all objects within the bucket, or Anywhere Caches caching data for that bucket. Otherwise, buckets with objects/caches will fail. Anywhere Cache requires additional permissions to interact with and will be assumed not present when the provider is not permissioned, attempting to delete the bucket anyways. This may result in the objects in the bucket getting destroyed but not the bucket itself if there is a cache in use with the bucket. Force deletion may take a long time to delete buckets with lots of objects or with any Anywhere Caches (80m+).
        """
        return pulumi.get(self, "force_destroy")

    @force_destroy.setter
    def force_destroy(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "force_destroy", value)

    @_builtins.property
    @pulumi.getter(name="hierarchicalNamespace")
    def hierarchical_namespace(self) -> Optional[pulumi.Input['pulumi_gcp.storage.BucketHierarchicalNamespaceArgs']]:
        """
        The bucket's hierarchical namespace policy, which defines the bucket capability to handle folders in logical structure. Structure is documented below. To use this configuration, <span pulumi-lang-nodejs="`uniformBucketLevelAccess`" pulumi-lang-dotnet="`UniformBucketLevelAccess`" pulumi-lang-go="`uniformBucketLevelAccess`" pulumi-lang-python="`uniform_bucket_level_access`" pulumi-lang-yaml="`uniformBucketLevelAccess`" pulumi-lang-java="`uniformBucketLevelAccess`">`uniform_bucket_level_access`</span> must be enabled on bucket.
        """
        return pulumi.get(self, "hierarchical_namespace")

    @hierarchical_namespace.setter
    def hierarchical_namespace(self, value: Optional[pulumi.Input['pulumi_gcp.storage.BucketHierarchicalNamespaceArgs']]):
        pulumi.set(self, "hierarchical_namespace", value)

    @_builtins.property
    @pulumi.getter(name="ipFilter")
    def ip_filter(self) -> Optional[pulumi.Input['pulumi_gcp.storage.BucketIpFilterArgs']]:
        """
        The bucket IP filtering configuration. Specifies the network sources that can access the bucket, as well as its underlying objects. Structure is documented below.
        """
        return pulumi.get(self, "ip_filter")

    @ip_filter.setter
    def ip_filter(self, value: Optional[pulumi.Input['pulumi_gcp.storage.BucketIpFilterArgs']]):
        pulumi.set(self, "ip_filter", value)

    @_builtins.property
    @pulumi.getter
    def labels(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        A map of key/value label pairs to assign to the bucket.
        """
        return pulumi.get(self, "labels")

    @labels.setter
    def labels(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "labels", value)

    @_builtins.property
    @pulumi.getter(name="lifecycleRules")
    def lifecycle_rules(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['pulumi_gcp.storage.BucketLifecycleRuleArgs']]]]:
        """
        The bucket's [Lifecycle Rules](https://cloud.google.com/storage/docs/lifecycle#configuration) configuration. Multiple blocks of this type are permitted. Structure is documented below.
        """
        return pulumi.get(self, "lifecycle_rules")

    @lifecycle_rules.setter
    def lifecycle_rules(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['pulumi_gcp.storage.BucketLifecycleRuleArgs']]]]):
        pulumi.set(self, "lifecycle_rules", value)

    @_builtins.property
    @pulumi.getter
    def location(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The [GCS location](https://cloud.google.com/storage/docs/bucket-locations).

        - - -
        """
        return pulumi.get(self, "location")

    @location.setter
    def location(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "location", value)

    @_builtins.property
    @pulumi.getter
    def logging(self) -> Optional[pulumi.Input['pulumi_gcp.storage.BucketLoggingArgs']]:
        """
        The bucket's [Access & Storage Logs](https://cloud.google.com/storage/docs/access-logs) configuration. Structure is documented below.
        """
        return pulumi.get(self, "logging")

    @logging.setter
    def logging(self, value: Optional[pulumi.Input['pulumi_gcp.storage.BucketLoggingArgs']]):
        pulumi.set(self, "logging", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the bucket. Bucket names must be in lowercase and no more than 63 characters long. You can find the complete list of bucket naming rules [here](https://cloud.google.com/storage/docs/buckets#naming).
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def project(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The ID of the project in which the resource belongs. If it
        is not provided, the provider project is used.
        """
        return pulumi.get(self, "project")

    @project.setter
    def project(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "project", value)

    @_builtins.property
    @pulumi.getter(name="publicAccessPrevention")
    def public_access_prevention(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Prevents public access to a bucket. Acceptable values are "inherited" or "enforced". If "inherited", the bucket uses [public access prevention](https://cloud.google.com/storage/docs/public-access-prevention) only if the bucket is subject to the public access prevention organization policy constraint. Defaults to "inherited".
        """
        return pulumi.get(self, "public_access_prevention")

    @public_access_prevention.setter
    def public_access_prevention(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "public_access_prevention", value)

    @_builtins.property
    @pulumi.getter(name="requesterPays")
    def requester_pays(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Enables [Requester Pays](https://cloud.google.com/storage/docs/requester-pays) on a storage bucket.
        """
        return pulumi.get(self, "requester_pays")

    @requester_pays.setter
    def requester_pays(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "requester_pays", value)

    @_builtins.property
    @pulumi.getter(name="retentionPolicy")
    def retention_policy(self) -> Optional[pulumi.Input['pulumi_gcp.storage.BucketRetentionPolicyArgs']]:
        """
        Configuration of the bucket's data retention policy for how long objects in the bucket should be retained. Structure is documented below.
        """
        return pulumi.get(self, "retention_policy")

    @retention_policy.setter
    def retention_policy(self, value: Optional[pulumi.Input['pulumi_gcp.storage.BucketRetentionPolicyArgs']]):
        pulumi.set(self, "retention_policy", value)

    @_builtins.property
    @pulumi.getter
    def rpo(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The recovery point objective for cross-region replication of the bucket. Applicable only for dual and multi-region buckets. `"DEFAULT"` sets default replication. `"ASYNC_TURBO"` value enables turbo replication, valid for dual-region buckets only. See [Turbo Replication](https://cloud.google.com/storage/docs/managing-turbo-replication) for more information. If rpo is not specified at bucket creation, it defaults to `"DEFAULT"` for dual and multi-region buckets. **NOTE** If used with single-region bucket, It will throw an error.
        """
        return pulumi.get(self, "rpo")

    @rpo.setter
    def rpo(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "rpo", value)

    @_builtins.property
    @pulumi.getter(name="softDeletePolicy")
    def soft_delete_policy(self) -> Optional[pulumi.Input['pulumi_gcp.storage.BucketSoftDeletePolicyArgs']]:
        """
        The bucket's soft delete policy, which defines the period of time that soft-deleted objects will be retained, and cannot be permanently deleted. If the block is not provided, Server side value will be kept which means removal of block won't generate any terraform change. Structure is documented below.
        """
        return pulumi.get(self, "soft_delete_policy")

    @soft_delete_policy.setter
    def soft_delete_policy(self, value: Optional[pulumi.Input['pulumi_gcp.storage.BucketSoftDeletePolicyArgs']]):
        pulumi.set(self, "soft_delete_policy", value)

    @_builtins.property
    @pulumi.getter(name="storageClass")
    def storage_class(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The [Storage Class](https://cloud.google.com/storage/docs/storage-classes) of the new bucket. Supported values include: `STANDARD`, `MULTI_REGIONAL`, `REGIONAL`, `NEARLINE`, `COLDLINE`, `ARCHIVE`.
        """
        return pulumi.get(self, "storage_class")

    @storage_class.setter
    def storage_class(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "storage_class", value)

    @_builtins.property
    @pulumi.getter(name="uniformBucketLevelAccess")
    def uniform_bucket_level_access(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Enables [Uniform bucket-level access](https://cloud.google.com/storage/docs/uniform-bucket-level-access) access to a bucket.
        """
        return pulumi.get(self, "uniform_bucket_level_access")

    @uniform_bucket_level_access.setter
    def uniform_bucket_level_access(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "uniform_bucket_level_access", value)

    @_builtins.property
    @pulumi.getter
    def versioning(self) -> Optional[pulumi.Input['pulumi_gcp.storage.BucketVersioningArgs']]:
        """
        The bucket's [Versioning](https://cloud.google.com/storage/docs/object-versioning) configuration.  Structure is documented below.
        """
        return pulumi.get(self, "versioning")

    @versioning.setter
    def versioning(self, value: Optional[pulumi.Input['pulumi_gcp.storage.BucketVersioningArgs']]):
        pulumi.set(self, "versioning", value)

    @_builtins.property
    @pulumi.getter
    def website(self) -> Optional[pulumi.Input['pulumi_gcp.storage.BucketWebsiteArgs']]:
        """
        Configuration if the bucket acts as a website. Structure is documented below.
        """
        return pulumi.get(self, "website")

    @website.setter
    def website(self, value: Optional[pulumi.Input['pulumi_gcp.storage.BucketWebsiteArgs']]):
        pulumi.set(self, "website", value)


class BucketTransformArgsArgsDict(TypedDict):
    bucket: NotRequired[pulumi.Input['BucketOverridesArgsDict']]

@pulumi.input_type
class BucketTransformArgsArgs:
    def __init__(__self__, *,
                 bucket: Optional[pulumi.Input['BucketOverridesArgs']] = None):
        if bucket is not None:
            pulumi.set(__self__, "bucket", bucket)

    @_builtins.property
    @pulumi.getter
    def bucket(self) -> Optional[pulumi.Input['BucketOverridesArgs']]:
        return pulumi.get(self, "bucket")

    @bucket.setter
    def bucket(self, value: Optional[pulumi.Input['BucketOverridesArgs']]):
        pulumi.set(self, "bucket", value)


class FunctionOverridesArgsDict(TypedDict):
    build_config: NotRequired[pulumi.Input['pulumi_gcp.cloudfunctionsv2.FunctionBuildConfigArgsDict']]
    """
    Describes the Build step of the function that builds a container
    from the given source.
    Structure is documented below.
    """
    description: NotRequired[pulumi.Input[_builtins.str]]
    """
    User-provided description of a function.
    """
    event_trigger: NotRequired[pulumi.Input['pulumi_gcp.cloudfunctionsv2.FunctionEventTriggerArgsDict']]
    """
    An Eventarc trigger managed by Google Cloud Functions that fires events in
    response to a condition in another service.
    Structure is documented below.
    """
    kms_key_name: NotRequired[pulumi.Input[_builtins.str]]
    """
    Resource name of a KMS crypto key (managed by the user) used to encrypt/decrypt function resources.
    It must match the pattern projects/{project}/locations/{location}/keyRings/{key_ring}/cryptoKeys/{crypto_key}.
    """
    labels: NotRequired[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]
    """
    A set of key/value label pairs associated with this Cloud Function.

    **Note**: This field is non-authoritative, and will only manage the labels present in your configuration.
    Please refer to the field <span pulumi-lang-nodejs="`effectiveLabels`" pulumi-lang-dotnet="`EffectiveLabels`" pulumi-lang-go="`effectiveLabels`" pulumi-lang-python="`effective_labels`" pulumi-lang-yaml="`effectiveLabels`" pulumi-lang-java="`effectiveLabels`">`effective_labels`</span> for all of the labels present on the resource.
    """
    location: NotRequired[pulumi.Input[_builtins.str]]
    """
    The location of this cloud function.
    """
    name: NotRequired[pulumi.Input[_builtins.str]]
    """
    A user-defined name of the function. Function names must
    be unique globally and match pattern `projects/*/locations/*/functions/*`.
    """
    project: NotRequired[pulumi.Input[_builtins.str]]
    """
    The ID of the project in which the resource belongs.
    If it is not provided, the provider project is used.
    """
    service_config: NotRequired[pulumi.Input['pulumi_gcp.cloudfunctionsv2.FunctionServiceConfigArgsDict']]
    """
    Describes the Service being deployed.
    Structure is documented below.
    """

@pulumi.input_type
class FunctionOverridesArgs:
    def __init__(__self__, *,
                 build_config: Optional[pulumi.Input['pulumi_gcp.cloudfunctionsv2.FunctionBuildConfigArgs']] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 event_trigger: Optional[pulumi.Input['pulumi_gcp.cloudfunctionsv2.FunctionEventTriggerArgs']] = None,
                 kms_key_name: Optional[pulumi.Input[_builtins.str]] = None,
                 labels: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 location: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 project: Optional[pulumi.Input[_builtins.str]] = None,
                 service_config: Optional[pulumi.Input['pulumi_gcp.cloudfunctionsv2.FunctionServiceConfigArgs']] = None):
        """
        :param pulumi.Input['pulumi_gcp.cloudfunctionsv2.FunctionBuildConfigArgs'] build_config: Describes the Build step of the function that builds a container
               from the given source.
               Structure is documented below.
        :param pulumi.Input[_builtins.str] description: User-provided description of a function.
        :param pulumi.Input['pulumi_gcp.cloudfunctionsv2.FunctionEventTriggerArgs'] event_trigger: An Eventarc trigger managed by Google Cloud Functions that fires events in
               response to a condition in another service.
               Structure is documented below.
        :param pulumi.Input[_builtins.str] kms_key_name: Resource name of a KMS crypto key (managed by the user) used to encrypt/decrypt function resources.
               It must match the pattern projects/{project}/locations/{location}/keyRings/{key_ring}/cryptoKeys/{crypto_key}.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: A set of key/value label pairs associated with this Cloud Function.
               
               **Note**: This field is non-authoritative, and will only manage the labels present in your configuration.
               Please refer to the field <span pulumi-lang-nodejs="`effectiveLabels`" pulumi-lang-dotnet="`EffectiveLabels`" pulumi-lang-go="`effectiveLabels`" pulumi-lang-python="`effective_labels`" pulumi-lang-yaml="`effectiveLabels`" pulumi-lang-java="`effectiveLabels`">`effective_labels`</span> for all of the labels present on the resource.
        :param pulumi.Input[_builtins.str] location: The location of this cloud function.
        :param pulumi.Input[_builtins.str] name: A user-defined name of the function. Function names must
               be unique globally and match pattern `projects/*/locations/*/functions/*`.
        :param pulumi.Input[_builtins.str] project: The ID of the project in which the resource belongs.
               If it is not provided, the provider project is used.
        :param pulumi.Input['pulumi_gcp.cloudfunctionsv2.FunctionServiceConfigArgs'] service_config: Describes the Service being deployed.
               Structure is documented below.
        """
        if build_config is not None:
            pulumi.set(__self__, "build_config", build_config)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if event_trigger is not None:
            pulumi.set(__self__, "event_trigger", event_trigger)
        if kms_key_name is not None:
            pulumi.set(__self__, "kms_key_name", kms_key_name)
        if labels is not None:
            pulumi.set(__self__, "labels", labels)
        if location is not None:
            pulumi.set(__self__, "location", location)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if project is not None:
            pulumi.set(__self__, "project", project)
        if service_config is not None:
            pulumi.set(__self__, "service_config", service_config)

    @_builtins.property
    @pulumi.getter(name="buildConfig")
    def build_config(self) -> Optional[pulumi.Input['pulumi_gcp.cloudfunctionsv2.FunctionBuildConfigArgs']]:
        """
        Describes the Build step of the function that builds a container
        from the given source.
        Structure is documented below.
        """
        return pulumi.get(self, "build_config")

    @build_config.setter
    def build_config(self, value: Optional[pulumi.Input['pulumi_gcp.cloudfunctionsv2.FunctionBuildConfigArgs']]):
        pulumi.set(self, "build_config", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        User-provided description of a function.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="eventTrigger")
    def event_trigger(self) -> Optional[pulumi.Input['pulumi_gcp.cloudfunctionsv2.FunctionEventTriggerArgs']]:
        """
        An Eventarc trigger managed by Google Cloud Functions that fires events in
        response to a condition in another service.
        Structure is documented below.
        """
        return pulumi.get(self, "event_trigger")

    @event_trigger.setter
    def event_trigger(self, value: Optional[pulumi.Input['pulumi_gcp.cloudfunctionsv2.FunctionEventTriggerArgs']]):
        pulumi.set(self, "event_trigger", value)

    @_builtins.property
    @pulumi.getter(name="kmsKeyName")
    def kms_key_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Resource name of a KMS crypto key (managed by the user) used to encrypt/decrypt function resources.
        It must match the pattern projects/{project}/locations/{location}/keyRings/{key_ring}/cryptoKeys/{crypto_key}.
        """
        return pulumi.get(self, "kms_key_name")

    @kms_key_name.setter
    def kms_key_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "kms_key_name", value)

    @_builtins.property
    @pulumi.getter
    def labels(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        A set of key/value label pairs associated with this Cloud Function.

        **Note**: This field is non-authoritative, and will only manage the labels present in your configuration.
        Please refer to the field <span pulumi-lang-nodejs="`effectiveLabels`" pulumi-lang-dotnet="`EffectiveLabels`" pulumi-lang-go="`effectiveLabels`" pulumi-lang-python="`effective_labels`" pulumi-lang-yaml="`effectiveLabels`" pulumi-lang-java="`effectiveLabels`">`effective_labels`</span> for all of the labels present on the resource.
        """
        return pulumi.get(self, "labels")

    @labels.setter
    def labels(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "labels", value)

    @_builtins.property
    @pulumi.getter
    def location(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The location of this cloud function.
        """
        return pulumi.get(self, "location")

    @location.setter
    def location(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "location", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        A user-defined name of the function. Function names must
        be unique globally and match pattern `projects/*/locations/*/functions/*`.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def project(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The ID of the project in which the resource belongs.
        If it is not provided, the provider project is used.
        """
        return pulumi.get(self, "project")

    @project.setter
    def project(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "project", value)

    @_builtins.property
    @pulumi.getter(name="serviceConfig")
    def service_config(self) -> Optional[pulumi.Input['pulumi_gcp.cloudfunctionsv2.FunctionServiceConfigArgs']]:
        """
        Describes the Service being deployed.
        Structure is documented below.
        """
        return pulumi.get(self, "service_config")

    @service_config.setter
    def service_config(self, value: Optional[pulumi.Input['pulumi_gcp.cloudfunctionsv2.FunctionServiceConfigArgs']]):
        pulumi.set(self, "service_config", value)


class FunctionTransformArgsArgsDict(TypedDict):
    function: NotRequired[pulumi.Input['FunctionOverridesArgsDict']]

@pulumi.input_type
class FunctionTransformArgsArgs:
    def __init__(__self__, *,
                 function: Optional[pulumi.Input['FunctionOverridesArgs']] = None):
        if function is not None:
            pulumi.set(__self__, "function", function)

    @_builtins.property
    @pulumi.getter
    def function(self) -> Optional[pulumi.Input['FunctionOverridesArgs']]:
        return pulumi.get(self, "function")

    @function.setter
    def function(self, value: Optional[pulumi.Input['FunctionOverridesArgs']]):
        pulumi.set(self, "function", value)


