// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));


// Export sub-modules:
import * as aws from "./aws";
import * as gcp from "./gcp";
import * as types from "./types";

export {
    aws,
    gcp,
    types,
};
pulumi.runtime.registerResourcePackage("anvil", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:anvil") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});

// Hand-written App class
export { App, AppConfig, Context, AwsProviderConfig, GcpProviderConfig, DefaultsConfig } from "./app";

// Hand-written Block class
export { Block, BlockArgs } from "./block";

// Re-exported Pulumi primitives
// Users can import anvil.Output, anvil.ComponentResource, etc. without @pulumi/pulumi
export {
  ComponentResource,
  ComponentResourceOptions,
  CustomResource,
  ResourceOptions,
  ProviderResource,
  Config,
  output,
  all,
  secret,
  interpolate,
  concat,
  getProject,
  getStack,
} from "@pulumi/pulumi";
export type { Output, Input, Inputs } from "@pulumi/pulumi";


// Escape hatch — full Pulumi namespace for anything not re-exported
export { pulumi };
